### ISSUE TITLE
Stuck after killing an enemy

### ISSUE THREAD

**Issue by ruddles** [DexterHuang/CyberCodeOnline#1]
After killing an enemy I got "Enemy does not exist" and I don't have any links to follow to leave the battle.

![image](https://user-images.githubusercontent.com/325764/89827858-1b4b2e80-db50-11ea-8321-5ce30aa6e161.png)

**Comment by ruddles** [comment]
Seems refreshing the page does give me a go back link.

**Comment by DexterHuang** [comment]
yeah i think what happened was i just pushed a fix and when you refresh you updated to the new version with back link haha

**Comment by ruddles** [comment]
Ah yeah that'll do it.  Great game though, really enjoying it so far.

**Comment by maxdevos49** [comment]
I had this same issue multiple times yesterday but also had the back link. It would say "Enemy does not exist" or something close when I clicked the back button. Perhaps it should be reopened or more research into it?
