### ISSUE TITLE
Secondary & destructive weapons display "YOU DO NOT HAVE ENOUGH {AMMO}" on hover

### ISSUE THREAD

**Issue by kimileta** [DexterHuang/CyberCodeOnline#10]
During combat, hovering over useSpecialWeapon or useDestructiveWeapon displays YOU DO NOT HAVE ENOUGH ENERGY_CELL/ANTI_MATTER_CHARGE when I have ammo in my inventory; clicking on either weapon still successfully uses it and expends ammo

**Comment by DexterHuang** [comment]
Fixed :D
