### ISSUE TITLE
Health resets in dungeon when another player joins the fight

### ISSUE THREAD

**Issue by wizarduss** [DexterHuang/CyberCodeOnline#100]
I've noticed that if I've already hit an enemy and gotten damage myself, as soon as another player joins that fight, it reset both my shield and health, while the enemy remained where it is health-wise.

**Comment by DexterHuang** [comment]
I was not able to reproduce this issue, are you sure it happens? or am I missing something

**Comment by wizarduss** [comment]
it may have been that the other player was way overleveled and was one hitting the enemies, perhaps that caused it to reset?

**Comment by tripplehelix** [comment]
This was fixed, shield issue came back then was fixed.
