### ISSUE TITLE
"Uh oh, My bad" after defeating boss in the first area with co-op challenge, can't reconnect

### ISSUE THREAD

**Issue by IuryPiva** [DexterHuang/CyberCodeOnline#101]
Everything was fine until the last hit when I clicked to attack it refreshed the page and I'm not being able to reconnect. All I get is that message saying "Uh oh, My bad.. Something went wrong 😢"

**Comment by DexterHuang** [comment]
Hey thanks so much for reporting this big bug lol

Are could you paste the console error here?

Do you know how to check error?

**Comment by IuryPiva** [comment]
`polyfills-dom.fea3c675.chunk.js:1 TypeError: Cannot read property 'toString' of undefined
    at main.48e31e1c.chunk.js:1
    at Array.some (<anonymous>)
    at e.value (main.48e31e1c.chunk.js:1)
    at e.value (main.48e31e1c.chunk.js:1)
    at AppLayoutDesktop.feae6eab.chunk.js:1
    at polyfills-dom.fea3c675.chunk.js:1
    at at (polyfills-dom.fea3c675.chunk.js:1)
    at t.track (polyfills-dom.fea3c675.chunk.js:1)
    at p (polyfills-dom.fea3c675.chunk.js:1)
    at hn (AppLayoutDesktop.feae6eab.chunk.js:1)
rs @ polyfills-dom.fea3c675.chunk.js:1
n.payload @ polyfills-dom.fea3c675.chunk.js:1
fo @ polyfills-dom.fea3c675.chunk.js:1
Ua @ polyfills-dom.fea3c675.chunk.js:1
bs @ polyfills-dom.fea3c675.chunk.js:1
bu @ polyfills-dom.fea3c675.chunk.js:1
gu @ polyfills-dom.fea3c675.chunk.js:1
cu @ polyfills-dom.fea3c675.chunk.js:1
(anonymous) @ polyfills-dom.fea3c675.chunk.js:1
e.unstable_runWithPriority @ polyfills-dom.fea3c675.chunk.js:1
Wi @ polyfills-dom.fea3c675.chunk.js:1
Qi @ polyfills-dom.fea3c675.chunk.js:1
Ki @ polyfills-dom.fea3c675.chunk.js:1
lu @ polyfills-dom.fea3c675.chunk.js:1
Ut @ polyfills-dom.fea3c675.chunk.js:1
Vt @ polyfills-dom.fea3c675.chunk.js:1
Rt @ polyfills-dom.fea3c675.chunk.js:1
t.reportChanged @ polyfills-dom.fea3c675.chunk.js:1
e.setNewValue @ polyfills-dom.fea3c675.chunk.js:1
t.write @ polyfills-dom.fea3c675.chunk.js:1
set @ polyfills-dom.fea3c675.chunk.js:1
(anonymous) @ main.48e31e1c.chunk.js:1
u @ testing-library.js:90
(anonymous) @ testing-library.js:90
forEach.e.<computed> @ testing-library.js:90
w @ main.48e31e1c.chunk.js:1
a @ main.48e31e1c.chunk.js:1
(anonymous) @ main.48e31e1c.chunk.js:1
(anonymous) @ main.48e31e1c.chunk.js:1
(anonymous) @ main.48e31e1c.chunk.js:1
(anonymous) @ polyfills-dom.fea3c675.chunk.js:1
U @ polyfills-dom.fea3c675.chunk.js:1
t.raise @ polyfills-dom.fea3c675.chunk.js:1
t.raiseQueuedEventsMatchingPredicate_ @ polyfills-dom.fea3c675.chunk.js:1
t.raiseEventsForChangedPath @ polyfills-dom.fea3c675.chunk.js:1
t.onDataUpdate_ @ polyfills-dom.fea3c675.chunk.js:1
e.onDataPush_ @ polyfills-dom.fea3c675.chunk.js:1
e.onDataMessage_ @ polyfills-dom.fea3c675.chunk.js:1
t.onDataMessage_ @ polyfills-dom.fea3c675.chunk.js:1
t.onPrimaryMessageReceived_ @ polyfills-dom.fea3c675.chunk.js:1
(anonymous) @ polyfills-dom.fea3c675.chunk.js:1
t.appendFrame_ @ polyfills-dom.fea3c675.chunk.js:1
t.handleIncomingFrame @ polyfills-dom.fea3c675.chunk.js:1
mySock.onmessage @ polyfills-dom.fea3c675.chunk.js:1
Show 14 more frames
main.48e31e1c.chunk.js:1 TypeError: Cannot read property 'toString' of undefined
    at main.48e31e1c.chunk.js:1
    at Array.some (<anonymous>)
    at e.value (main.48e31e1c.chunk.js:1)
    at e.value (main.48e31e1c.chunk.js:1)
    at AppLayoutDesktop.feae6eab.chunk.js:1
    at polyfills-dom.fea3c675.chunk.js:1
    at at (polyfills-dom.fea3c675.chunk.js:1)
    at t.track (polyfills-dom.fea3c675.chunk.js:1)
    at p (polyfills-dom.fea3c675.chunk.js:1)
    at hn (AppLayoutDesktop.feae6eab.chunk.js:1) {componentStack: "↵    in hn↵    in ne↵    in ue↵    in mt↵    in di…in o↵    in MobXProvider↵    in Ze↵    in Unknown"}`

**Comment by IuryPiva** [comment]
Well, after I got a console log saying that server version was 125 and local version 124 I reloaded the page and was able to reconnect to my account

**Comment by DexterHuang** [comment]
ah, I am guessing it just happened because I pushed an update just now, 
so no problem already right? 👍
