### ISSUE TITLE
Stuck on the "Uh oh, My bad.. Something went wrong" overlay

### ISSUE THREAD

**Issue by benjschro** [DexterHuang/CyberCodeOnline#102]
Per the title, every time I refresh the page, the overlay comes up and prevents me from playing. I've tried logging out and then back in, clearing cookies, and even logging in from a private browsing session (using Firefox, mind you).

I have noticed there is a brief amount of time sometimes that I can interact with the game before the overlay comes up. If I quickly click another view (e.g. Inventory.ts) it allows me to keep the game up. The moment I click on Surroundings.ts, the overlay immediately comes up.

Maybe check server side to see the state of my account: SirCarrotCake

**Comment by DexterHuang** [comment]
Hi, thank you for the reporting,

could you paste the console error here so I could debug?

**Comment by benjschro** [comment]
Hopefully this is helpful

TypeError: e.type is undefined
    value https://cybercodeonline.com/static/js/main.d18ef58a.chunk.js:1
    value https://cybercodeonline.com/static/js/main.d18ef58a.chunk.js:1
    value https://cybercodeonline.com/static/js/main.d18ef58a.chunk.js:1
    En https://cybercodeonline.com/static/js/AppLayoutDesktop.aca2cae1.chunk.js:1
    p https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    at https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    track https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    p https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    En https://cybercodeonline.com/static/js/AppLayoutDesktop.aca2cae1.chunk.js:1
    Yo https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    Fa https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    bs https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    bu https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    gu https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    cu https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    Qi https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    unstable_runWithPriority https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    Wi https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    Qi https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    Ki https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    lu https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    Ut https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    Vt https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    Rt https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    reportChanged https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    setNewValue https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    write https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    set https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    n https://cybercodeonline.com/static/js/main.d18ef58a.chunk.js:1
    l https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    _invoke https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    T https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    w https://cybercodeonline.com/static/js/main.d18ef58a.chunk.js:1
    a https://cybercodeonline.com/static/js/main.d18ef58a.chunk.js:1
    E https://cybercodeonline.com/static/js/main.d18ef58a.chunk.js:1
    E https://cybercodeonline.com/static/js/main.d18ef58a.chunk.js:1
    e https://cybercodeonline.com/static/js/main.d18ef58a.chunk.js:1
    getEventRunner https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    U https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    raise https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    raiseQueuedEventsMatchingPredicate_ https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    raiseEventsForChangedPath https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    onDataUpdate_ https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    onDataPush_ https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    onDataMessage_ https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    onDataMessage_ https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    onPrimaryMessageReceived_ https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    connReceiver_ https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    appendFrame_ https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    handleIncomingFrame https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
    onmessage https://cybercodeonline.com/static/js/polyfills-dom.eb6ffbe8.chunk.js:1
polyfills-dom.eb6ffbe8.chunk.js:1:329828

**Comment by benjschro** [comment]
Here is more thorough export:
https://pastebin.com/r1DRYtgN

While I myself am a software dev, I don't do web stuff, so I don't know what is interesting for you to look at!

**Comment by DexterHuang** [comment]
is it possible you jump to the source code and builtify it using the build-in browser tool and post a screenshot for me? i am struggling to  find the source since its minified, I only can guess its at position 329828 lol

**Comment by DexterHuang** [comment]
you should be able to jump to source by clicking `https://cybercodeonline.com/static/js/main.d18ef58a.chunk.js:1` while holding ctrl

**Comment by benjschro** [comment]
I imagine the problem is here?
![image](https://user-images.githubusercontent.com/20567645/94589567-67167c00-0253-11eb-9e10-41c6c2f5bba6.png)

**Comment by DexterHuang** [comment]
aright i have deployed a patch, could you try if the issue is fixed?

**Comment by benjschro** [comment]
You seem to have gotten it! I'm still not sure what it was in the first place. I _think_ I might have clicked to join someone's dungeon, but cannot recall.

Thanks!

**Comment by DexterHuang** [comment]
hmmm I see I see 🤔
thank you for reporting! hopefully not many other players experienced this issue 👍
