### ISSUE TITLE
Bug - Items Lore

### ISSUE THREAD

**Issue by ManzTellen** [DexterHuang/CyberCodeOnline#1029]
$tierName doesn't show any text other than its variable.
Not only that, since $itemName fetches its result from the item's full name, it adds more confusion when you add $tierName before so. for example:

> #### basic:
> a ${tierName} ${itemName} that shoots a bullet
> 
> #### result:
> a Legendary Legendary Powerful X Desctruction that shoots a bullet

It might be helpful to either notify the contributor regarding the redundancy or delete the first initial $itemName word if it's the same as $tierName

**Comment by DexterHuang** [comment]
ahh yeah because the item name already includes the tier name
