### ISSUE TITLE
Android: Back button can end up creating an authentication loop

### ISSUE THREAD

**Issue by sammykun** [DexterHuang/CyberCodeOnline#106]
On a Pixel 3a, running Android 11.

I logged in using Google, and was in the 3D Printing area. I had hit the Android back button, and it got me into an authentication loop (kept asking me to sign in).

I can try to repro it later after my idle farming is done ;)

**Comment by DexterHuang** [comment]
thanks for reporting :) 
oh does restarting the app fix it?
did you click the back button very fast?
does it happen every time?

**Comment by DexterHuang** [comment]
this issue should be fixed :) do let me know if you still experience it 👍
