### ISSUE TITLE
Mobile Refresh Feature

### ISSUE THREAD

**Issue by M-Cry** [DexterHuang/CyberCodeOnline#107]
### This is a simple suggestion for the mobile app:
Adding a refresh feature to get the mobile app to sync with the progress made in the PC (browser), this is to make it that someone just keeps the app open and refreshes the app to skip time using ads.

A good idea to implement this is "pull to refresh" (like the one in mobile browsers).

**Comment by DexterHuang** [comment]
pull to refresh added ;)
