### ISSUE TITLE
Open API - Statistics, Scores, Players

### ISSUE THREAD

**Issue by elementh** [DexterHuang/CyberCodeOnline#108]
First and foremost, thank you for your hard work. It's a beautiful game and has a lot of potential!

My suggestion resolves around a public open API which developers can target to build an ecosystem around the game.

It would be nice to be able to build a telegram bot that notifies a group every time a certain player levels up, or that someone can share the details of their player, etc.

Thank you and please let me know if you need more explanation or help of any kind.

**Comment by DexterHuang** [comment]
yeah as long as the API will not destroy my server XD

do you have anything in mind? what kind of API is needed?

**Comment by elementh** [comment]
> yeah as long as the API will not destroy my server XD

Makes sense to have some kind of rate limiting, indeed!

> do you have anything in mind? what kind of API is needed?

It really depends on how much you are comfortable giving up to the public. For the use case I've discussed with my friends, player stats, levels and equipment are nice to have. Maybe we can start with that and build around it? 

It would be really cool to have Status and Location also, if you think is right, because I can see myself doing a telegram bot so others can check what our party is doing!

**Comment by DexterHuang** [comment]
Ohh I see 🤔 currently the client is capable of showing what each player is doing, but cuz I havnt implemented clan system yet, what kind of thing do you think clans should be about to do?
I'm not too clear on that, which is why I havnt implemented it yet, I think could get useful use case from you haha

**Comment by elementh** [comment]
First thing that comes to my mind is clan missions, clan-only caches, privately organized dungeons, etc. Then having a Status API could be really useful so for example we can check if we have enough free people (not AFK-ing in any task) to start a dungeon, etc.

Second is PvP but that is always so difficult to balance!!

**Comment by elementh** [comment]
Obviously that would be cool to have in-game, but having a bot in our telegram group which is always online is useful!

**Comment by DexterHuang** [comment]
That sounds cool!
Yeah for api I won't make a public portal cuz it's too much work, but if you gonna have some project I'm happy to collaborate, like setting up a hook for to your server for notification or info :D

**Comment by DexterHuang** [comment]
@elementh btw I have setup a clan suggestion thread, if you have any more ideas for what the app should provide for you to play with friend easily and more fun way, please feel free to comment on that one :D I think it would be good idea I work on clan as the next system to implement

**Comment by elementh** [comment]
> That sounds cool!
> Yeah for api I won't make a public portal cuz it's too much work, but if you gonna have some project I'm happy to collaborate, like setting up a hook for to your server for notification or info :D

Cool!! Let me think about a set of funcionalities to start and let's discuss that :)

**Comment by elementh** [comment]
> @elementh btw I have setup a clan suggestion thread, if you have any more ideas for what the app should provide for you to play with friend easily and more fun way, please feel free to comment on that one :D I think it would be good idea I work on clan as the next system to implement

Sure!!

**Comment by tripplehelix** [comment]
Added to spreadsheet
