### ISSUE TITLE
An electron App.

### ISSUE THREAD

**Issue by geoolson** [DexterHuang/CyberCodeOnline#11]
This looks convincingly like vscode, except that it's running in the browser. an Electron version would make this look even more like vscode.

**Comment by DexterHuang** [comment]
that is not a bad idea, initially i didnt think much of using electron, cuz then you will need to install on office computer, which leaves hard evidence of the app LOL 
but I suppose it become even more stealthy with electron

**Comment by hildjj** [comment]
maybe "just" a [PWA](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs)?  In Chrome, you can install them on the destktop.

**Comment by geoolson** [comment]
With the PWA can you make the window frameless or add a menu to the frame like vscode?

**Comment by hildjj** [comment]
It's at least frameless.  Go to `twitter.com`, log in, and click the little plus that shows up to the right of the URL.

**Comment by tripplehelix** [comment]
You can create a PWA manually by going to the 
Chrome Menu > More Tools > Create Shortcut

Doesn't look too far off at all.
