### ISSUE TITLE
Quest requirements not showing (Browser)

### ISSUE THREAD

**Issue by M-Cry** [DexterHuang/CyberCodeOnline#111]
Quest requirements not showing in the browser game, but it shows in the mobile app. 
**I mean how much is left to finish the quest is not showing in the browser game**
![image](https://user-images.githubusercontent.com/42918650/95661064-544a5400-0b3d-11eb-82fe-49eef8f830cb.png) 
![image](https://user-images.githubusercontent.com/42918650/95661111-b5722780-0b3d-11eb-8d6d-46eb3754a4db.png)

This is on V0.143

**Comment by DexterHuang** [comment]
Hii thanks for reporting, I think it is showed when you hover with your cursor

**Comment by M-Cry** [comment]
In the picture I was hovering with the cursor but the capture tool does not show it, is this an issue from my side or it is a bug?

**Comment by DexterHuang** [comment]
ah! sorry i didnt see it clearly, It is a bug, its also not showing on my side.
thanks, will fix that :)

**Comment by DexterHuang** [comment]
fixed :)
