### ISSUE TITLE
Enemy names

### ISSUE THREAD

**Issue by steventhorne** [DexterHuang/CyberCodeOnline#113]
Prepend non-named enemies (e.g. murderer, thief, thug, etc.) with "a" or "an" so that the name still makes sense when used in a sentence. 

Currently, when these names are used in a sentence they don't make grammatical sense.

For example:
`You were killed by murderer.`
`murderer deals 68 damage to you.`
`You killed murderer.`

Would change to:
`You were killed by a murderer.`
`A murderer deals 68 damage to you.`
`You killed a murderer.`

**Comment by DexterHuang** [comment]
thanks :) the change will include in the next update 👍
