### ISSUE TITLE
Enemy name modifiers

### ISSUE THREAD

**Issue by steventhorne** [DexterHuang/CyberCodeOnline#114]
It would be cool if enemy modifiers such as `Strong`, `Tough`, `Angry`, `Shielded`, etc. were distinguishable from the rest of the name. This would make it easier to differentiate the enemies in a list at a glance. 

One suggestion for this would be to do the following:
`Thug`
`Strong Thug`
`Burgler`
`Shielded Murderer`
`Angry Street Shark`

Would change to:
`Thug`
`(Strong) Thug`
`Burgler`
`(Shielded) Murderer`
`(Angry) Street Shark`

Additionally, coloring the modifiers would also help to view things at a glance. For example, coloring (Shielded) in blue, (Angry) in red, (Strong) in yellow, etc..

**Comment by DexterHuang** [comment]
feature is implemeanted :)
