### ISSUE TITLE
Mobile Loot UI

### ISSUE THREAD

**Issue by steventhorne** [DexterHuang/CyberCodeOnline#115]
This may be controversial, but I think that the loot UI on mobile should list out the items from the bottom so that it's easy to tap them. Most of the other common interactions are at the bottom of the screen, but when I want to pick out some of the items, I have to reach all the way to the top of the screen.

**Comment by DexterHuang** [comment]
Hey I think that's big brain

**Comment by tripplehelix** [comment]
I think this would be a great change

**Comment by tripplehelix** [comment]
Added to discord #suggestions
