### ISSUE TITLE
Server error on https://us-central1-codegame-dcb3b.cloudfunctions.net/api/map/interactTile

### ISSUE THREAD

**Issue by twiernik** [DexterHuang/CyberCodeOnline#117]
{
   "ok":false,
   "stack":"TypeError: Cannot read property 'id' of null\n    at Function.getPlayerDungeonRoom (/workspace/dist/bundle.js:369:11508)\n    at interactTile (/workspace/dist/bundle.js:369:14423)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async /workspace/dist/bundle.js:369:3940",
   "headers":{
      "host":"us-central1-codegame-dcb3b.cloudfunctions.net",
      "user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
      "transfer-encoding":"chunked",
      "accept":"application/json, text/plain, */*",
      "accept-encoding":"gzip, deflate, br",
      "accept-language":"en,pl-PL;q=0.9,pl;q=0.8,en-US;q=0.7",
      "authorization":"...",
      "cache-control":"no-cache",
      "content-type":"application/json;charset=UTF-8",
      "forwarded":"for=\"31.11.131.8\";proto=https",
      "function-execution-id":"3gwrvv0rpgqr",
      "origin":"https://cybercodeonline.com",
      "pragma":"no-cache",
      "referer":"https://cybercodeonline.com/",
      "sec-fetch-dest":"empty",
      "sec-fetch-mode":"cors",
      "sec-fetch-site":"cross-site",
      "traceparent":"00",
      "x-appengine-city":"wroclaw",
      "x-appengine-citylatlong":"51.107885,17.038538",
      "x-appengine-country":"PL",
      "x-appengine-default-version-hostname":"o3657711ac5a93775-tp.appspot.com",
      "x-appengine-https":"on",
      "x-appengine-region":"ds",
      "x-appengine-request-log-id":"5f8c728400ff02661e7a9187d00001737e6f333635373731316163356139333737352d7470000134356434653736346338656165323133373032663339303639353834643531653a33383200010101",
      "x-appengine-timeout-ms":"599999",
      "x-appengine-user-ip":"31.11.131.8",
      "x-client-data":"CgTHzpsV",
      "x-cloud-trace-context":"f130d2d5b53e3074e3ae20e1995cfcc4/6565574506467036857",
      "x-forwarded-for":"31.11.131.8",
      "x-forwarded-proto":"https",
      "connection":"close",
      "if-none-match":"no-match-for-this"
   },
   "url":"/map/interactTile",
   "requestBody":"",
   "urlParams":{
      
   },
   "queryStrings":{
      
   },
   "message":"TypeError: Cannot read property 'id' of null"
}

**Comment by twiernik** [comment]
currentLocation=Location.FALLEN_RESEARCH_FACILITY;

status=PlayerStatus.IDLE;

/**
*If you wish your friend to join your dungeon,
*send them your dungeon ID
*/
dungeonId="EBux3LWJ";

**Comment by twiernik** [comment]
it seems that dungeon just disappeared?

**Comment by DexterHuang** [comment]
hello yeah, it can happen, are you stuck? are you able to leave the dungeon?

**Comment by twiernik** [comment]
After refreshing I was able to play the game without problems.

**Comment by DexterHuang** [comment]
good good :) this is a known issue, only happens if you are in the dungeon when server updates :)
