### ISSUE TITLE
Spelling & Grammar Corrections

### ISSUE THREAD

**Issue by jcolcord** [DexterHuang/CyberCodeOnline#12]
### Inventory.Ts
**Currently**
  // Automatically scraps all weak equipments
**Correction**
  // Automatically scraps all weak equipment

### System Message
**Currently**
You have level up your MOLECULAR PRINT skill
**Correction**
  You have leveled up your MOLECULAR PRINT skill
  **Or**
  You leveled up your MOLECULAR PRINT skill

###  SOURCE CONTROL
**Currently**
  Hi, CyberCode Online is still under heavy development, if you have any suggestion or constructive critics, they are very welcome.
**Correction**
  Hi, CyberCode Online is still under heavy development, if you have any suggestions or constructive criticism, they are very welcome.

### DISCORD

**Currently**
  If you want to connect with other players, or there is something you want to talk to me about you can find me at CyberCode Online's Discrod Channel
**Correction**
If you want to connect with other players, or there is something you want to talk to me about you can find me at CyberCode Online's Discord Channel

**Currently**
(for bugs it's encourage to create a issue on our github page)
**Correction**
(for bugs and suggestions you are encouraged to create a issue on our github page)

**Currently**
TO DISCROD
**Correction**
TO DISCORD

### currentLocation=Location.SHANGRI_LA_CITY_CENTER;
**Currently**
*One of the most busy city in the nation,
*at this place, all sort of people gathers from around the planet.
**Correction**
*One of the most busy cities in the nation,
*at this place, all sorts of people gather from around the planet.

**Comment by DexterHuang** [comment]
this is super helpful! thank you so much
all these change will be deployed soon 👍

**Comment by DexterHuang** [comment]
fix deployed :)
