### ISSUE TITLE
Not clear memory reward

### ISSUE THREAD

**Issue by twiernik** [DexterHuang/CyberCodeOnline#120]
![image](https://user-images.githubusercontent.com/1544483/96572543-3a430b00-12cd-11eb-9855-cc439bf6b0f7.png)

**Comment by twiernik** [comment]
System and item info is different

**Comment by DexterHuang** [comment]
reward list has been updated 👍

**Comment by twiernik** [comment]
![obraz](https://user-images.githubusercontent.com/1544483/98448675-03bf1a00-212e-11eb-8c7b-6610926e7250.png)

**Comment by twiernik** [comment]
@DexterHuang I think this should be reopened

**Comment by DexterHuang** [comment]
Oh the alignment is off? Sorry I didn't noticed your reply before haha
