### ISSUE TITLE
Error code?!? 

### ISSUE THREAD

**Issue by tinamilford** [DexterHuang/CyberCodeOnline#123]
PjpyLHk6aX0pLHM9dC50eXBlO3UmJihzPXUudHlwZSx0PXUpO3ZhciBmPVtdO3QudHlwZT09PW8uYS5FTkVNWSYmKGY9dC5nZXRDbGFzc09iamVjdChjLmEsImVuZW15IikuZ2V0SW5Db21iYXRQbGF5ZXJzKCkpO3ZhciBwPXMuaXNJbnRlcmFjdGFibGUoKTtyZXR1cm4gcy5pc1BlclBsYXllcigpJiZ0LnBsYXllckludGVyYWN0ZWQoYSkmJihwPSExKSx7dGlsZTp0LHRpbGVUeXBlOnMsaW5Db21iYXRQbGF5ZXJzOmYsaXNJbnRlcmFjdGFibGU6cH19fV0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IHVuZGVmaW5lZCBpcyBub3QgYW4gb2JqZWN0IChldmFsdWF0aW5nICdzLmlzSW50ZXJhY3RhYmxlJykKdmFsdWVAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjdmYzA5ODk3LmNodW5rLmpzOjE6MzMwMzc1Cmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0TW9iaWxlLjI4NWRjMTU1LmNodW5rLmpzOjE6NzY4OTkKbWFwQFtuYXRpdmUgY29kZV0KaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuMjg1ZGMxNTUuY2h1bmsuanM6MTo3Njg2MAptYXBAW25hdGl2ZSBjb2RlXQpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL0FwcExheW91dE1vYmlsZS4yODVkYzE1NS5jaHVuay5qczoxOjc2NzQ4Cmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvZmlyZXN0b3JlLjljNWRjNjhiLmNodW5rLmpzOjE6NjUwODgKYWVAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9maXJlc3RvcmUuOWM1ZGM2OGIuY2h1bmsuanM6MTo5NDg2Cmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvZmlyZXN0b3JlLjljNWRjNjhiLmNodW5rLmpzOjE6MjAxNjUKcEBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL2ZpcmVzdG9yZS45YzVkYzY4Yi5jaHVuay5qczoxOjY1MDY5ClhvQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvZmlyZXN0b3JlLjljNWRjNjhiLmNodW5rLmpzOjE6MzI5NTM5CkJhQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvZmlyZXN0b3JlLjljNWRjNjhiLmNodW5rLmpzOjE6MzM4NDI4Cm1zQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvZmlyZXN0b3JlLjljNWRjNjhiLmNodW5rLmpzOjE6MzY4Njk0CmJzQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvZmlyZXN0b3JlLjljNWRjNjhiLmNodW5rLmpzOjE6MzY4NjE5CmNzQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvZmlyZXN0b3JlLjljNWRjNjhiLmNodW5rLmpzOjE6MzY1NjIxCmNzQFtuYXRpdmUgY29kZV0KaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9maXJlc3RvcmUuOWM1ZGM2OGIuY2h1bmsuanM6MTozMTY4MTAKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9maXJlc3RvcmUuOWM1ZGM2OGIuY2h1bmsuanM6MTozOTI0ODAKWWlAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9maXJlc3RvcmUuOWM1ZGM2OGIuY2h1bmsuanM6MTozMTY3NTcKR2lAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9maXJlc3RvcmUuOWM1ZGM2OGIuY2h1bmsuanM6MTozMTY2OTIKbHNAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9maXJlc3RvcmUuOWM1ZGM2OGIuY2h1bmsuanM6MTozNjU5MTQKRmVAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9maXJlc3RvcmUuOWM1ZGM2OGIuY2h1bmsuanM6MToyMTU4NApSZUBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL2ZpcmVzdG9yZS45YzVkYzY4Yi5jaHVuay5qczoxOjE3ODIyCmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvZmlyZXN0b3JlLjljNWRjNjhiLmNodW5rLmpzOjE6Mzk4MApodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL2ZpcmVzdG9yZS45YzVkYzY4Yi5jaHVuay5qczoxOjEyMjI3Cmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvZmlyZXN0b3JlLjljNWRjNjhiLmNodW5rLmpzOjE6NDE3NjEKc2V0QGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvZmlyZXN0b3JlLjljNWRjNjhiLmNodW5rLmpzOjE6NDI0MjIKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjdmYzA5ODk3LmNodW5rLmpzOjE6MzI2NjkxCmxAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9maXJlc3RvcmUuOWM1ZGM2OGIuY2h1bmsuanM6MToyNTk5MjYKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9maXJlc3RvcmUuOWM1ZGM2OGIuY2h1bmsuanM6MToyNTk3MTEKd0BodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uN2ZjMDk4OTcuY2h1bmsuanM6MTozMjUwMTAKYUBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uN2ZjMDk4OTcuY2h1bmsuanM6MTozMjUyMTMKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjdmYzA5ODk3LmNodW5rLmpzOjE6MzI1MjcyClByb21pc2VAW25hdGl2ZSBjb2RlXQpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uN2ZjMDk4OTcuY2h1bmsuanM6MTozMjUxNjQKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfmZpcmViYXNlLWRhdGFiYXNlLjgyZmZmZjBlLmNodW5rLmpzOjE6NDQyNjgKUUBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+ZmlyZWJhc2UtZGF0YWJhc2UuODJmZmZmMGUuY2h1bmsuanM6MTo0NTA3Cmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35maXJlYmFzZS1kYXRhYmFzZS44MmZmZmYwZS5jaHVuay5qczoxOjEwMDQzNApodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+ZmlyZWJhc2UtZGF0YWJhc2UuODJmZmZmMGUuY2h1bmsuanM6MToxMDAwNTMKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfmZpcmViYXNlLWRhdGFiYXNlLjgyZmZmZjBlLmNodW5rLmpzOjE6OTk3OTgKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfmZpcmViYXNlLWRhdGFiYXNlLjgyZmZmZjBlLmNodW5rLmpzOjE6MTQwODMzCltuYXRpdmUgY29kZV0KaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfmZpcmViYXNlLWRhdGFiYXNlLjgyZmZmZjBlLmNodW5rLmpzOjE6MTMwMDUzCmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35maXJlYmFzZS1kYXRhYmFzZS44MmZmZmYwZS5jaHVuay5qczoxOjEyOTk0MApbbmF0aXZlIGNvZGVdCmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35maXJlYmFzZS1kYXRhYmFzZS44MmZmZmYwZS5jaHVuay5qczoxOjExOTk5OApodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+ZmlyZWJhc2UtZGF0YWJhc2UuODJmZmZmMGUuY2h1bmsuanM6MToxMTk5MTMKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfmZpcmViYXNlLWRhdGFiYXNlLjgyZmZmZjBlLmNodW5rLmpzOjE6MTE4MTM2Cmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35maXJlYmFzZS1kYXRhYmFzZS44MmZmZmYwZS5jaHVuay5qczoxOjExMzU4NwpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+ZmlyZWJhc2UtZGF0YWJhc2UuODJmZmZmMGUuY2h1bmsuanM6MToxMTQxOTgKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfmZpcmViYXNlLWRhdGFiYXNlLjgyZmZmZjBlLmNodW5rLmpzOjE6MTEyNzY4

**Comment by DexterHuang** [comment]
hey, thanks for the report :) it should be fixed, could you try again?
