### ISSUE TITLE
Stuck on Dungeon

### ISSUE THREAD

**Issue by alfaice** [DexterHuang/CyberCodeOnline#124]
Hi, I was playing on a dungeon with another player and after killing an enemy the game crashed. Right now I can't really play anymore because whenever I go to "Area" the game crashes.

This happens on Android.

The error code is:

`PnIseTppfSkscz10LnR5cGU7dSYmKHM9dS50eXBlLHQ9dSk7dmFyIGY9W107dC50eXBlPT09by5hLkVORU1ZJiYoZj10LmdldENsYXNzT2JqZWN0KGMuYSwiZW5lbXkiKS5nZXRJbkNvbWJhdFBsYXllcnMoKSk7dmFyIHA9cy5pc0ludGVyYWN0YWJsZSgpO3JldHVybiBzLmlzUGVyUGxheWVyKCkmJnQucGxheWVySW50ZXJhY3RlZChhKSYmKHA9ITEpLHt0aWxlOnQsdGlsZVR5cGU6cyxpbkNvbWJhdFBsYXllcnM6Zixpc0ludGVyYWN0YWJsZTpwfX19XSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IENhbm5vdCByZWFkIHByb3BlcnR5ICdpc0ludGVyYWN0YWJsZScgb2YgdW5kZWZpbmVkClR5cGVFcnJvcjogQ2Fubm90IHJlYWQgcHJvcGVydHkgJ2lzSW50ZXJhY3RhYmxlJyBvZiB1bmRlZmluZWQKICAgIGF0IEZ1bmN0aW9uLnZhbHVlIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uN2ZjMDk4OTcuY2h1bmsuanM6MTozMzAzNzYpCiAgICBhdCBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL0FwcExheW91dE1vYmlsZS4yODVkYzE1NS5jaHVuay5qczoxOjc2ODg4CiAgICBhdCBBcnJheS5tYXAgKDxhbm9ueW1vdXM+KQogICAgYXQgaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuMjg1ZGMxNTUuY2h1bmsuanM6MTo3Njg1NwogICAgYXQgQXJyYXkubWFwICg8YW5vbnltb3VzPikKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0TW9iaWxlLjI4NWRjMTU1LmNodW5rLmpzOjE6NzY3NDUKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvZmlyZXN0b3JlLjljNWRjNjhiLmNodW5rLmpzOjE6NjUwODcKICAgIGF0IGFlIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL2ZpcmVzdG9yZS45YzVkYzY4Yi5jaHVuay5qczoxOjk0ODIpCiAgICBhdCBlLnRyYWNrIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL2ZpcmVzdG9yZS45YzVkYzY4Yi5jaHVuay5qczoxOjIwMTYzKQogICAgYXQgcCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9maXJlc3RvcmUuOWM1ZGM2OGIuY2h1bmsuanM6MTo2NTA2NCk=`

**Comment by DexterHuang** [comment]
hey, thanks for the report :) it should be fixed, could you try again?

**Comment by alfaice** [comment]
Works now, thanks!
