### ISSUE TITLE
Dungeon Player revive

### ISSUE THREAD

**Issue by BetaAndroid** [DexterHuang/CyberCodeOnline#127]
Instead of getting revived in the city another player can revive the downed player by defeating the enemy that beat the other player, and useing a heal item so they can continue on.

**Comment by DexterHuang** [comment]
but they can "give up" and fail the dungeon thus cannot be revived anymore right?

**Comment by BetaAndroid** [comment]
Right

**Comment by tripplehelix** [comment]
Added to discord #suggestions
