### ISSUE TITLE
Don't prompt for qty when only 1 of item exists

### ISSUE THREAD

**Issue by donburks** [DexterHuang/CyberCodeOnline#13]
When clicking on an item that would prompt the qty modal (How many of X do you want to do?), if there is only 1 item, do not prompt that modal.

Example: 
Molecular3dPrinter
I have trashHelmentCache_x1
I click on Molecular Print
It should just print it, it should not prompt me for how many I want to print. I only have 1. It's an extra, unnecessary click now.

**Comment by DexterHuang** [comment]
implemented in pre-release
