### ISSUE TITLE
Discord chat 🔄 Cco chat

### ISSUE THREAD

**Issue by BetaAndroid** [DexterHuang/CyberCodeOnline#131]
It could be possible to make it so that discord and Cco players can talk to each other.
Main idea is that in Cco there is a new channel added named "discord" and in discord a channel named "CyberCode-Online". Then a discord bot that connects to an Cco account to read the discord chat and put it on Cco and the other way around. When someone on discord types in this channel it will put there name in Cco (example: "Beta#4374 (discord)") and when someone types on Cco it will put there name in discord (example: "Beta (CyberCode Online)"). I think this would make it so much easier to communicate for people who don't want to sign into discord or join the group and for people who don't want to play Cco but can still talk to Cco players.

**Comment by DexterHuang** [comment]
nice idea 👍 
and totally possible technically, just its a bit more troublesome ~ this will be in backlog 👍

**Comment by tripplehelix** [comment]
This would be ace, can have it's own discord channel. seen other games do this before.

**Comment by tripplehelix** [comment]
Moved to #suggestions on discord
