### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by BetaAndroid** [DexterHuang/CyberCodeOnline#135]
PiAwIT09YXJndW1lbnRzWzFdP2FyZ3VtZW50c1sxXToxLG49KGFyZ3VtZW50cy5sZW5ndGg+MiYmdm9pZCAwIT09YXJndW1lbnRzWzJdP2FyZ3VtZW50c1syXTp7fSkuaWdub3JlTW9uZXkscj12b2lkIDAhPT1uJiZuLGk9ZS5nZXRNaXNzaW5nQ29zdHModGhpcy5nZXRDb3N0cygpLHQpO3JldHVybiByJiYoaT1pLmZpbHRlcihmdW5jdGlvbihlKXtyZXR1cm4iTU9ORVkiIT09ZS50eXBlfSkpLDA9PT1pLmxlbmd0aH19LHtrZXk6ImdldFRpbWVOZWVkZWQKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IENhbm5vdCByZWFkIHByb3BlcnR5ICdnZXRNaXNzaW5nQ29zdHMnIG9mIG51bGwKVHlwZUVycm9yOiBDYW5ub3QgcmVhZCBwcm9wZXJ0eSAnZ2V0TWlzc2luZ0Nvc3RzJyBvZiBudWxsCiAgICBhdCB1LnZhbHVlIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMDk5NjYxYmMuY2h1bmsuanM6MToyMzk0NjEpCiAgICBhdCB1LnZhbHVlIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMDk5NjYxYmMuY2h1bmsuanM6MToyMzkyMzIpCiAgICBhdCBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL0FwcExheW91dE1vYmlsZS42YjdkODdhNS5jaHVuay5qczoxOjQwMzU5CiAgICBhdCBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL2ZpcmVzdG9yZS5hNTViYTgwZC5jaHVuay5qczoxOjY1MDg2CiAgICBhdCBhZSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9maXJlc3RvcmUuYTU1YmE4MGQuY2h1bmsuanM6MTo5MjkxKQogICAgYXQgZS50cmFjayAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9maXJlc3RvcmUuYTU1YmE4MGQuY2h1bmsuanM6MToxOTk3MikKICAgIGF0IHAgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvZmlyZXN0b3JlLmE1NWJhODBkLmNodW5rLmpzOjE6NjUwNjMpCiAgICBhdCB5dCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuNmI3ZDg3YTUuY2h1bmsuanM6MTo0MDI5OSkKICAgIGF0IFFpIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL2ZpcmVzdG9yZS5hNTViYTgwZC5jaHVuay5qczoxOjMyNzY4OCkKICAgIGF0IEZhIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL2ZpcmVzdG9yZS5hNTViYTgwZC5jaHVuay5qczoxOjMzNjU3Nik=

The only thing i did was log out of my account.

**Comment by DexterHuang** [comment]
issue is fixed :)
