### ISSUE TITLE
Printing while mining

### ISSUE THREAD

**Issue by twiernik** [DexterHuang/CyberCodeOnline#136]
1. Open printing tab
2. Change location and start mining
3. Click printing tab and choose item to print

Effect:
one can click print and nothing happens 

Desired:
User shouldn't be able to print anything

**Comment by DexterHuang** [comment]
doesnt it show a popup says there is no molecular printer nearby?

**Comment by twiernik** [comment]
no popup

**Comment by twiernik** [comment]
![image](https://user-images.githubusercontent.com/1544483/97087381-03048f00-162a-11eb-91c0-4faef95b619e.png)

**Comment by DexterHuang** [comment]
Ah thanks! the issue is fixed :)
