### ISSUE TITLE
Cannot collect duengon reward

### ISSUE THREAD

**Issue by twiernik** [DexterHuang/CyberCodeOnline#137]
![image](https://user-images.githubusercontent.com/1544483/97117856-bc389700-1706-11eb-916d-d83c27ddedb4.png)

**Comment by DexterHuang** [comment]
What happens if you restart? We're you switching back and forth from web to app? Or your have multiple tabs of the website open?

**Comment by twiernik** [comment]
Refreshing page helps, I have only one tab open.
