### ISSUE TITLE
A Story !!!

### ISSUE THREAD

**Issue by M-Cry** [DexterHuang/CyberCodeOnline#141]
I have a suggestion of adding a bit of a story to the game at least for the first 30-50 levels.

I'm not that good with coming-up with stories, but I think this can be contributed.

Thoughts ?

**Comment by DexterHuang** [comment]
Yeah I think so, maybe some bits of lore items you can get during progression? That would be very easy for anyone to contribute I think 🤔

**Comment by BetaAndroid** [comment]
I think it should start off like "you wake up on the curb of a street. Nothing is on you so you must have been robbed."
