### ISSUE TITLE
Suggestion: Keyboard shortcuts

### ISSUE THREAD

**Issue by Heartia** [DexterHuang/CyberCodeOnline#147]
I think keyboard shortcuts would greatly improve user experience,
especially during combat.

These are just some ideas:
[1] for Primary attack
[2] for Special weapon
[3] for Destructive weapon
[Esc] for escape
[4] for 1st healing item in list
[5] for 2nd healing item in list
and so on...

I found using the mouse particularly tedious when fighting
the challenge dungeon bosses, as I constantly have to
move the mouse cursor up and down, up and down
to heal myself every one to two turns between the attacks.
(It feels a little bit like when I have to use my mouse to
use on-screen keyboards to enter passwords, or
when I am forced to right click and choose "copy",
then right click again somewhere else to "paste".)

Also, there is a slight delay before I can actually click on the
healing items, because the click doesn't register before the
item description pop-up appears on the screen.  This has resulted in
occasional accidents where I thought I had healed myself,
but the system had not registered that mouse click.

I believe having keyboard shortcuts would make the
whole process much smoother and stress-free.

Perhaps shortcuts could be beneficial to other areas of the UI,
such as "take all", "confirming molecular printing" or "accepting quests",
but my main concern is combat as mentioned above.

**Comment by Heartia** [comment]
I just realized that the "delay for healing" mentioned above had already been fixed.
Sorry about that!

**Comment by DexterHuang** [comment]
keyboard shortcut makes its too easy for bot to be created :(

**Comment by Heartia** [comment]
Oh, I see...
Thank you for the feedback :)
