### ISSUE TITLE
Clicking on the player name gives this bug report link: 

### ISSUE THREAD

**Issue by CMDR7** [DexterHuang/CyberCodeOnline#148]
PiE9PWU/ZS5tZW1vaXplZFN0YXRlOm51bGx9ZWxzZSBlPVdpLm5leHQ7dmFyIHQ9bnVsbD09PUdpP3FpLm1lbW9pemVkU3RhdGU6R2kubmV4dDtpZihudWxsIT09dClHaT10LFdpPWU7ZWxzZXtpZihudWxsPT09ZSl0aHJvdyBFcnJvcihhKDMxMCkpO2U9e21lbW9pemVkU3RhdGU6KFdpPWUpLm1lbW9pemVkU3RhdGUsYmFzZVN0YXRlOldpLmJhc2VTdGF0ZSxiYXNlUXVldWU6V2kuYmFzZVF1ZXVlLHF1ZXVlOldpLnF1ZXVlLG5leHQ6bnVsbH0sbnVsbD0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpFcnJvcjogTWluaWZpZWQgUmVhY3QgZXJyb3IgIzMxMDsgdmlzaXQgaHR0cHM6Ly9yZWFjdGpzLm9yZy9kb2NzL2Vycm9yLWRlY29kZXIuaHRtbD9pbnZhcmlhbnQ9MzEwIGZvciB0aGUgZnVsbCBtZXNzYWdlIG9yIHVzZSB0aGUgbm9uLW1pbmlmaWVkIGRldiBlbnZpcm9ubWVudCBmb3IgZnVsbCBlcnJvcnMgYW5kIGFkZGl0aW9uYWwgaGVscGZ1bCB3YXJuaW5ncy4KRXJyb3I6IE1pbmlmaWVkIFJlYWN0IGVycm9yICMzMTA7IHZpc2l0IGh0dHBzOi8vcmVhY3Rqcy5vcmcvZG9jcy9lcnJvci1kZWNvZGVyLmh0bWw/aW52YXJpYW50PTMxMCBmb3IgdGhlIGZ1bGwgbWVzc2FnZSBvciB1c2UgdGhlIG5vbi1taW5pZmllZCBkZXYgZW52aXJvbm1lbnQgZm9yIGZ1bGwgZXJyb3JzIGFuZCBhZGRpdGlvbmFsIGhlbHBmdWwgd2FybmluZ3MuCiAgICBhdCBKaSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9maXJlc3RvcmUuMzZiZDM3YjEuY2h1bmsuanM6MTozMjgyOTEpCiAgICBhdCBlYSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9maXJlc3RvcmUuMzZiZDM3YjEuY2h1bmsuanM6MTozMjg1NDMpCiAgICBhdCBPYmplY3QudXNlU3RhdGUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvZmlyZXN0b3JlLjM2YmQzN2IxLmNodW5rLmpzOjE6MzMzMzcyKQogICAgYXQgT2JqZWN0LnQudXNlU3RhdGUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvZmlyZXN0b3JlLjM2YmQzN2IxLmNodW5rLmpzOjE6MjY5NTA1KQogICAgYXQgaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuNTA4N2ZhODIuY2h1bmsuanM6MToxMDYxODYKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvZmlyZXN0b3JlLjM2YmQzN2IxLmNodW5rLmpzOjE6NjUwODYKICAgIGF0IGFlIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL2ZpcmVzdG9yZS4zNmJkMzdiMS5jaHVuay5qczoxOjkyOTEpCiAgICBhdCBlLnRyYWNrIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL2ZpcmVzdG9yZS4zNmJkMzdiMS5jaHVuay5qczoxOjE5OTcyKQogICAgYXQgcCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9maXJlc3RvcmUuMzZiZDM3YjEuY2h1bmsuanM6MTo2NTA2MykKICAgIGF0IHFyIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL0FwcExheW91dE1vYmlsZS41MDg3ZmE4Mi5jaHVuay5qczoxOjEwNTk4NCk=

**Comment by DexterHuang** [comment]
Haha you are very quick lol the fix is being deployed right now
