### ISSUE TITLE
New quest ideas

### ISSUE THREAD

**Issue by hildjj** [DexterHuang/CyberCodeOnline#15]
- Kill a monster of level X (based on character level or print level)
- Kill a monster named X (something that should be available at the right level)
- Travel to area X
- Reverse engineer scraps (some number)
- Train printing
- Find an item named X (areas could have items you can find on the ground)
- Gift an item (now that you can see other players)
- Die in combat

**Comment by hildjj** [comment]
- team-based objectives:
  - generate X xp by [date]
  - generate X btc by [date]

**Comment by hildjj** [comment]
- craft an item of level X

**Comment by hildjj** [comment]
- gather N items of (quality|type)

**Comment by tripplehelix** [comment]
Added to discord
