### ISSUE TITLE
Bank/Storage Pricing

### ISSUE THREAD

**Issue by TehRayinator** [DexterHuang/CyberCodeOnline#151]
Rather than having it cost 1000 bitcoins to put an item into storage, maybe change it so that you start out with only a few slots (perhaps 1 - 5) and have the player pay to expand their storage. This would definitely give more incentive into using the storage system since right now the cost for storage is too high to be worth it.

**Comment by DexterHuang** [comment]
:) I already reduced the price for storage just now,
and will be adding a way to expend the slots for the bank in near future too ~
