### ISSUE TITLE
gang.md file not used in the mobile tutorial

### ISSUE THREAD

**Issue by Jeremy2801** [DexterHuang/CyberCodeOnline#1518]
The file gang.md in /contribution/mobile// is not used in the tutorial.

This file explains everything that new players constantly ask about how the gang system works an it seems that the social.md file is completely out of date.

Perhaps replacing social.md by gang.md could be a good idea.

**Comment by tnox** [comment]
It is in social for both PC and mobile I just found it after reading this and creating another gang page thank you for posting this please confirm you can find it and close this.

**Comment by Jeremy2801** [comment]
Yep, I can find the gang page by using the link in the social page. That's nicely done ;)
