### ISSUE TITLE
Typo on 'Crafting' page

### ISSUE THREAD

**Issue by twystd** [DexterHuang/CyberCodeOnline#152]
The 13'th item on the _Crafting_ page is "_militaryNanoMedicDrone_" - it should be "_advancedNanoMedicDrone_" (which is what it actually crafts).

<img width="391" alt="screenshot" src="https://user-images.githubusercontent.com/7932356/99741649-90e76480-2a86-11eb-8931-e6cc27f339df.png">

**Comment by tripplehelix** [comment]
Is this still an issue?

**Comment by twystd** [comment]
Seems to be worse now - military, advanced, high quality and rare are all labelled `militaryNanoDrone` (crafts the right thing, just the label is wrong):

<img width="426" alt="Screenshot 2021-01-21 at 12 25 07" src="https://user-images.githubusercontent.com/7932356/105408399-c40fb680-5be3-11eb-8159-51c5abf8d0cd.png">

**Comment by tripplehelix** [comment]
dex says he#s fixed this. Let me know if it isn't

**Comment by twystd** [comment]
Looks like it's still a problem - this is a screenshot from a couple of minutes ago:

<img width="440" alt="Screenshot 2021-02-24 at 08 31 37" src="https://user-images.githubusercontent.com/7932356/109043863-9f957700-7686-11eb-8b91-7b0971e0accc.png">

**Comment by twystd** [comment]
Ok, seems to be fixed now:

<img width="441" alt="Screenshot 2021-02-24 at 11 43 13" src="https://user-images.githubusercontent.com/7932356/109056608-7f20e900-7695-11eb-80d0-06d08174bdc6.png">
