### ISSUE TITLE
Base building

### ISSUE THREAD

**Issue by BetaAndroid** [DexterHuang/CyberCodeOnline#153]
I have a small thought of people being able to build homes, same layout as dungeon but it allows you to change where you want things to go, including the size and rooms. 
You can also send an invite in public just like Dungeon, or send it in messages. And a local chat for the house your in

It costs a decent amount of bitcoins to buy a house/items/decorations.

(My suggestion is also in discord)

**Comment by DexterHuang** [comment]
very interesting idea!
!

**Comment by BetaAndroid** [comment]
Also to add to my idea you can create a dungeon in the basement of your house for others to try and solve puzzles and fight robots (witch you can make with spare parts) 
For a good pricing of 750 BTC per player (not for use just if you put chests for people to loot and to repair the robots after)

**Comment by tripplehelix** [comment]
This is/was being voted for on discord
