### ISSUE TITLE
Update job timers with estimated times 

### ISSUE THREAD

**Issue by alexgamadev** [DexterHuang/CyberCodeOnline#154]
During jobs the times don't update so even with a job only having 570 seconds left (Around 9 and a half minutes) the estimated time is still "About an hour".

Would help with longer times where it's not as immediately obvious how long is left without converting the seconds online.
![TimerIssue](https://user-images.githubusercontent.com/65301737/99920787-bb9f1a80-2d1d-11eb-9b5d-97d805bc0c9a.png)

**Comment by DexterHuang** [comment]
Do you mean it doesn't change at all? Or just the about an hour should include second? @@
Are you stuck at the place?

**Comment by alexgamadev** [comment]
The about 1 hour doesn't change at all. Even when there was only 30 seconds left it still said about an hour. It works fine on mobile though so it must just be a bug?

**Comment by DexterHuang** [comment]
Ah I see, yes I think it's a display bug🙂 will fix it haha thanks for reporting!

**Comment by tripplehelix** [comment]
This was fixed
