### ISSUE TITLE
More interesting combat mechanics/weapons/upgrades

### ISSUE THREAD

**Issue by alexgamadev** [DexterHuang/CyberCodeOnline#155]
I know it would complicate things massively and create some balancing issues but it'd be really interesting to see some more interesting updates to the combat side of the game. For example one of the first things I did within the first couple of hours was click on a level 100+ player to look at what awesome gear they had. At first glance the weapon names seem really cool but when you look they're effectively just the exact same stuff as low level weapons with bigger numbers. I thought there might be more interesting weapons with things like damage over time effects or special abilities that really change the combat a lot at the later game. Now obviously I might be being ignorant here because I'm not that high a level so there might be massive changes in combat later on but it was a slight bummer seeing it was effectively just a numbers game and there was nothing new weapons wise. I also believe that maybe there should be the ability to fight groups of enemies at the same time. I asked in the game if there were any fights with more than one enemy (Since I'm low level I might not have reached them) but apparently there isn't. Groups of enemies could bring more interesting mechanics too like AoE upgrades or weapons. 

Obviously adding stuff like this would mean a pretty big overhaul of the game and balancing so I understand if it's a no but I think it could add some depth to the game in the long run and make looking at a high level player's items much more intriguing as a newbie.

**Comment by tripplehelix** [comment]
These ideas have all been submitted to #suggestions on discord, don't know if any got approved.
