### ISSUE TITLE
Scrapped crafted items and got nothing

### ISSUE THREAD

**Issue by tripplehelix** [DexterHuang/CyberCodeOnline#158]
Just scrapped 20 crafted items and recieved nothing back. Was expecting tech scrap. Used the multi select if that matters.

**Comment by DexterHuang** [comment]
Hey thanks for reporting, will investigate 👍

**Comment by DexterHuang** [comment]
Was it equipment you scrapped?

**Comment by tripplehelix** [comment]
Yes

**Comment by DexterHuang** [comment]
still unsure of how this happened @@ if happen again do let me know, closing the issue for now 👍
