### ISSUE TITLE
iOS Testing - Inventory  Screen

### ISSUE THREAD

**Issue by l33t4ng3l** [DexterHuang/CyberCodeOnline#159]
**Multi Select doesn't work on iOS**
When in the inventory menu, long press of an item triggers haptic feedback click, but doesn't do anything. No multi select available. This is also the same in browser version on iOS. 

**Item detail closing the panel**
Clicking the back button is unintuitive... iOS users are very used to swiping things closed. should add a swipe left to close the item detail modal and return to main inventory screen

**Comment by DexterHuang** [comment]
is the swipe left, from right edge swipe to left gesture ?@@

**Comment by DexterHuang** [comment]
this is fixed
