### ISSUE TITLE
iOS Testing - General 

### ISSUE THREAD

**Issue by l33t4ng3l** [DexterHuang/CyberCodeOnline#160]
**Click interaction not being picked up everytime**
Sometimes having to click multiple times as click will trigger the ripple effect, but not actually the button. super frustrating, also happens in browser version on iOS. Leads to multiple clicks in dungeons, selling unintended items, frustration when trying to navigate.

**Tutorial modals should be optional**
Tutorials being active on every new device I play on can be frustrating. Should add a toggle in the Me tab to turn on/off. 

**Chat badge doesn't go away**
Chat badge doesn't go away when I open the chat log... I have to switch from Chat to Mail tab and back for it to go away, even if I don't have any mail. This is also the same on the iOS Browser version.

**Comment by DexterHuang** [comment]
on which button specifically it sometimes doesnt register?
