### ISSUE TITLE
iOS Testing - Dungeons, Battles & Quests

### ISSUE THREAD

**Issue by l33t4ng3l** [DexterHuang/CyberCodeOnline#161]
**Size of dungeons and surrounding content forces scroll offscreen**
It would be great if the dungeons all fit to the space of the screen... along with the title and buttons (Quit, Send Invite)

**Dungeon Room level not showing up on mobile**
The level of the dungeon room doesn't show, frustrating when not knowing whether or not you can interact with loot.

**Messaging timing is too long**
The messaging for errors or receiving loot is too long... needs to be shortened. I don't want to have to actively close the dialogues every time... 

**Levels don't show for enemies in the dungeon battle**
I don't know what level enemy is when in battle screen in dungeon

**When you don't receive something from battle/loot box**
No messaging around when nothing is received from either battle or a loot box is super frustrating. Why did it not give something from loot box? Why is loot box there if it is empty? Does it always show a message if it does give you something? Doesn't give feeling of satisfaction, and leaves open the question of "did something just go wrong"?

**Discarding Quests**
The tiny x in the corner of a quest box on the Quest tab is hard to see. It is also unintuitive as the accepted quests behave differently from the mandatory quests (can't discard the system generated one... which - that would be a nice feature - even if it costs something). Should make anything being deleted or discarded also interactive with left swipe gesture

**Comment by DexterHuang** [comment]
hey fixed some of the annoying issues :) 
swipe gesture is not very easy to implement@@
