### ISSUE TITLE
[Suggestion] Player Avatars/Mob Avatars

### ISSUE THREAD

**Issue by MaryCybercode** [DexterHuang/CyberCodeOnline#174]
I suggest instead of the @ and username, we can have personalized avatars that are customizable, either showing the gear we have equiped or the ability to purchase clothing for our avatars, and maybe mobs have a look aswell, it'll make it feel more lively. Thank you for reviewing my suggestion, happy gaming.

**Comment by BetaAndroid** [comment]
If we had pfp to replace are name there should be a setting to turn off pfp to those who don't like seeing pfp's

**Comment by DexterHuang** [comment]
yeah, that could be a thing, but I am not an artist myself, but I would like to try find some asset for it online in future 👍
