### ISSUE TITLE
Arabic in chat + mods

### ISSUE THREAD

**Issue by tripplehelix** [DexterHuang/CyberCodeOnline#175]
When using Arabic in chat the window is then able to be scrolled to the right and text overflows the chat box.

Also is it about time you added some moderators to the chat?

**Comment by DexterHuang** [comment]
yeah, need to implement moderator features and find some good players willing to help :) 
the overflow issue, is it on web?

**Comment by tripplehelix** [comment]
It's on mobile, didn't look at the web ui

**Comment by tripplehelix** [comment]
It's this fixed?

**Comment by tripplehelix** [comment]
![Screenshot 2021-01-22 at 14 51 38](https://user-images.githubusercontent.com/16861223/105505935-6d78aa00-5cc1-11eb-9846-e9c230b5ba08.png)
![Screenshot 2021-01-22 at 14 51 48](https://user-images.githubusercontent.com/16861223/105505942-6e114080-5cc1-11eb-94e3-3bc9852d39ea.png)

This is still an issue.
Can't test text direction for Arabic.
