### ISSUE TITLE
No quest update if no loot

### ISSUE THREAD

**Issue by MagicZDS** [DexterHuang/CyberCodeOnline#176]
There is no update of the quest called "Kill Enemy" when you kill an enemy which does not provide any loot. The number stays at 3/6 even if you kill 5 enemies. It is the same problem with the quest "Deal Damage" : No loot -> No update.

![image](https://user-images.githubusercontent.com/40262363/100981019-7a411300-3546-11eb-8c99-b252859c1344.png)

**Comment by DexterHuang** [comment]
Hey does it happen when you kill enemy in dungeon?

**Comment by MagicZDS** [comment]
For now, I have not met any enemy which does not have any loot, so I can't confirm it.
But I have more infos to give about this "bug" : it is just a display problem, if you refresh your screen it shows the right value
- before F5 : "Kill Enemy" 3/6
- after F5 : "Kill Enemy" 6/6 "Claim"

**Comment by DexterHuang** [comment]
hmm interesting 0.0
