### ISSUE TITLE
Pve Dodge. 

### ISSUE THREAD

**Issue by BetaAndroid** [DexterHuang/CyberCodeOnline#180]
As the names says. Dodging in Pve. When you have Evade and successfully roll it, it shouldn't just let you dodge it. Insted you get set to a grid (3×3) and have to dodge projectiles and dangerous floors.

Made some examples in google docs
![Screenshot_20201203-110608~2.png](https://user-images.githubusercontent.com/73261982/101077374-9c905c00-3559-11eb-8120-390cc9b25548.png)
![Screenshot_20201203-110717~2.png](https://user-images.githubusercontent.com/73261982/101077407-a3b76a00-3559-11eb-899a-cf57cb1babbd.png)
![Screenshot_20201203-111043~2.png](https://user-images.githubusercontent.com/73261982/101077419-a74af100-3559-11eb-895d-d38acf6b991a.png)

**Comment by DexterHuang** [comment]
essentially like a mini game? @@

**Comment by tripplehelix** [comment]
Negatively voted on Discord
