### ISSUE TITLE
Status points system

### ISSUE THREAD

**Issue by WolfAlpha13** [DexterHuang/CyberCodeOnline#183]
I think it also good to have a status point as you level up, so you can add it either on your STR, DEF, VIT, DEX, EVA, LUCK. etc...

**Comment by DexterHuang** [comment]
yes @WolfAlpha13 , this game was originally designed so that you wont have fixed class, and everything is depending on what items you equip, but its worth to look into:)

**Comment by robbyt1414** [comment]
I like the no fixed class system. Is it frustrating?  Yes it is but it shakes things up and stops players being over powered  constantly .  If it was fixed upgrade modules would soon be useless

**Comment by tripplehelix** [comment]
Moved to #suggestions on discord
