### ISSUE TITLE
Gang supplies have not been taken

### ISSUE THREAD

**Issue by AmeliaN** [DexterHuang/CyberCodeOnline#1878]
Hello there! 
I've attached a screen shot, but our gang upkeep was supposed to go out on the 9th but we haven't had it taken! As much as I love free supplies im letting you know haha
![Screenshot_20220211-093639_CyberCode Online](https://user-images.githubusercontent.com/3429024/153568935-98dc0930-4719-472f-9a89-c7dc29e2cc45.jpg)

**Comment by AmeliaN** [comment]
This is for the gang Hungarians <HUN>

**Comment by DexterHuang** [comment]
thank you:)
