### ISSUE TITLE
アカウントの件

### ISSUE THREAD

**Issue by wakasagi1024** [DexterHuang/CyberCodeOnline#1903]
Earlier, reloading occurred frequently in the game, but after improvement, I could not log in.
I haven't linked my account with my email address, etc.
Is it difficult to return the account?
Account name wakasagi lv30

**Comment by DexterHuang** [comment]
hello this is already fixed :)

**Comment by wakasagi1024** [comment]
I'm not good at English

for now, I reinstalled the app

Stop at the screen before logging in

Please give instructions if there is anything you need to do

2022年2月12日(土) 午後5:08 DexterHuang ***@***.***>:

**Comment by DexterHuang** [comment]
hi, there is nothing you need to do :) 
just login to your account, it should work
