### ISSUE TITLE
Suggestion market place 

### ISSUE THREAD

**Issue by robbyt1414** [DexterHuang/CyberCodeOnline#197]
Create weapon only slots that we can buy or earn. The market for weapons is really lacking right now. The current slots are more valuable for storage of consumables meaning players would rather scrap a weapon instead of listing it.

Ideas like 1 weapon slot for every 5 levels 
Ability to buy addition slot at certain levels.
Max cap of 20 weapons. 

Any other suggestions or ideas on this would love to hear them. But should really be separate weapon only slots to stop being used as storage.
I think the market needs something right now

**Comment by DexterHuang** [comment]
I am not sure what you mean, do you mean we should increase the allowed concurrent item amount player can put in market?

**Comment by robbyt1414** [comment]
Yes but not consumables

**Comment by tripplehelix** [comment]
Extra slots have been added
