### ISSUE TITLE
Text displays wrong on Safari

### ISSUE THREAD

**Issue by maxdevos49** [DexterHuang/CyberCodeOnline#2]
The text in both the "Messages" and "System" tabs displays without any scroll height in Safari. I tested in chrome and it worked properly.

Possible guess fix could be just adding the ```--webkit-``` prefix for the specific CSS but could be displaying wrong for other reasons also. 

Image of the Issue:
<img width="763" alt="Screen Shot 2020-08-10 at 3 32 23 PM" src="https://user-images.githubusercontent.com/6227942/89828906-58e39380-db1f-11ea-851c-00cf7ecf1746.png">

**Comment by DexterHuang** [comment]
jesus that looks cool haha!

**Comment by maxdevos49** [comment]
I would be happy to test the fix

**Comment by DexterHuang** [comment]
hmmm i am not sure how to fix this, 
could you help me try using inspect to see where to add css attribute to fix this issue?

**Comment by DexterHuang** [comment]
fixed :D

**Comment by maxdevos49** [comment]
I could figure out a solution with inspect element. If you have pushed your fix then it unfortunately did not work D:

**Comment by DexterHuang** [comment]
turns out its because flex shrink stuff

i havent push to prod yet :D thats why you dont see the fix

**Comment by maxdevos49** [comment]
Oh that makes sense why I don't see a change and also with the fix
