### ISSUE TITLE
Wrong Upgrade removed from Multi-Slot-Item

### ISSUE THREAD

**Issue by JoachimBergt** [DexterHuang/CyberCodeOnline#20]
When using an Item with two upgrade-slots, there is a bug when removing the second upgrade.
I had attached an `healthUpgrade` (first) and a `damageUpgrade` (second).
When removing the `damageUpgrade`, I received a copy of the `healthUpgrade` in my Inventory, instead of the `damageUpgrade`.

**Comment by DexterHuang** [comment]
Fixed :)
