### ISSUE TITLE
Banner Display Error  - English

### ISSUE THREAD

**Issue by Olympianna** [DexterHuang/CyberCodeOnline#2102]
When I clean into a new lobby this appears instead of the normal banner
![Screenshot_20220220-010045_CyberCode Online](https://user-images.githubusercontent.com/100054000/154824755-1441778a-6889-40b5-8501-57b3af7f06e6.jpg)

**Comment by DexterHuang** [comment]
this is not a bug @@ the top gang shows here, now shows Ukraine stuff
