### ISSUE TITLE
8000 pieces stored bug

### ISSUE THREAD

**Issue by HASOON1234** [DexterHuang/CyberCodeOnline#2107]
There are more than 8,000 parts engineering pieces, so they cannot be stored in the inventory. Is there a way?
![Screenshot_20220220-175557_CyberCode Online](https://user-images.githubusercontent.com/100067929/154835891-f48cb168-e613-456d-89c1-960612691798.jpg)

**Comment by SSKubyshkin** [comment]
@HASOON1234, 

> ### 2022/02/22 v0.780
> - UPDATE - Item stack max amount is increased to 10,000

[Update 2022/02/22 v0.780](https://github.com/DexterHuang/CyberCodeOnline/blob/master/UpdateNote.md#20220222-v0780)
