### ISSUE TITLE
Error item in dungeon crate / Item not found

### ISSUE THREAD

**Issue by TargetCode1** [DexterHuang/CyberCodeOnline#220]
![Screenshot_20201215-213148](https://user-images.githubusercontent.com/76101883/102336449-c28b1700-3fc3-11eb-8dc0-f3a1073d71d5.jpg)

Error in collecting the item from crate in dungeon
Item not found.

**Comment by DexterHuang** [comment]
Hey have you try restart? I think this might be server desync issue, are you playing on multiple devices?

**Comment by TargetCode1** [comment]
After I tried restarting it the item is gone like it disappeared, I only play on one device
