### ISSUE TITLE
Impossible to login via Google account

### ISSUE THREAD

**Issue by igorek-sm** [DexterHuang/CyberCodeOnline#2200]
In CCO android version I can't connect via google account. After pressing "sign in with google account" window is popping up then hide. Video evidence is attached below. My phone is Unihertz Titan, rooted by Magisk. I also disabled Minminguard module (ads blocker) with no effect.

https://user-images.githubusercontent.com/100712709/156215438-b4546eec-3ff7-46d0-b76f-df53640dc582.mp4

**Comment by stevelle** [comment]
Same issue. This seems to have broken around Feb 24th or 25th, it worked on the 23rd when I last logged in on one of my devices. It wouldn't work on the 26th when I tried on another device.

**Comment by DexterHuang** [comment]
hi @stevelle  are you also located in Russia?

**Comment by DexterHuang** [comment]
hmmm I have just tried with my account it seem to work, try to reinstall?

**Comment by DexterHuang** [comment]
clear app cache

**Comment by igorek-sm** [comment]
Guys, I tried to clear cache and data, tried to reinstall app, tried to make CCO as a system app - no results. Today, at evening I will try to install CCO on my PC (bluestacks), then login (if possible) then backup via lucky patcher and install on phone. I'll write a message here if login successfully.

**Comment by DexterHuang** [comment]
Could you also try to visit cybercodeonline.com?

**Comment by igorek-sm** [comment]
> Could you also try to visit cybercodeonline.com?

Yes, on the site I enter my account successfully. But because of many little lags it is uncomfortable to play.

I tried all my ways to login in app. I gained root access in my Bluestacks on PC, then installed Lucky Patcher, backed up apk, backed up all the data (in /data/user/0/com.cybercodeonline.cybercode folder), transferred all of this to my phone. Then restored app, restored data and... CCO just closes up, no popping up windows, no errors. It seems that google account data is linked with hardware too, not only with software. The problem still the same.

P.S. I also tried to install CCO on my old phone - Realme C21 - and I can't log in.... My head is blown up...

**Comment by DexterHuang** [comment]
I see... Seems could you try just not using any unconventional stuff like
lucky patcher? If you just clear app data and cache and have a fresh
install, google should ask you which account you want to login with right?

**Comment by igorek-sm** [comment]
> 

Yes, on first run Google asked me for an account, after choosing it popping up window just hides, that's it.

**Comment by igorek-sm** [comment]
> Same issue. This seems to have broken around Feb 24th or 25th, it worked on the 23rd when I last logged in on one of my devices. It wouldn't work on the 26th when I tried on another device.

I have solved this problem!!! It appears when device is rooted. I just activated "CyberCode" item in DenyList of Magisk (do not apply DenyList!!!) and successfully logged in. No reboot needed.

**Comment by igorek-sm** [comment]
P.S. If you have Magisk < v23 then you should activate CyberCode in Magisk Hide option.

**Comment by stevelle** [comment]
I figured out what was breaking for me, getting this error on desktop.

<img width="928" alt="Screen Shot 2022-03-16 at 11 45 13 PM" src="https://user-images.githubusercontent.com/539741/158753400-62d428c5-ad4e-4b4b-86db-5f498b18934b.png">

I had this privacy setting on "All cookies" and sure enough it caused the OpenID Connect cookie from Google to be refused.
