### ISSUE TITLE
Fireproofed site yet I can't log in. 

### ISSUE THREAD

**Issue by CyberMechani** [DexterHuang/CyberCodeOnline#2243]
So I fireproofed the site using DuckDuckGo and I went ahead and deleted my tabs and data thinking that the site would be safe and I'd be able to log back in again. 

Apparently fireproofing sites doesn't do crap and when I tried to log back in it said to create a character. 

My previous character's (Blair_) account is still on the site because I can't use the name again and it says the name already belongs to a user. 

Edit: If the only thing the Dev can do is delete my account then I'm completely fine with that. As long as I get to use the same name it's fine.

**Comment by DexterHuang** [comment]
I think this should be caused by you logged in with wrong account

**Comment by CyberMechani** [comment]
> I think this should be caused by you logged in with wrong account

I didn't log in with the wrong account though. I used the same account I used to create the character in the first place.

**Comment by CyberMechani** [comment]
Since I don't think this can really be fixed, can you judt delete my characters profile so I can reuse the name? The name is Blair_ and my character's lvl 11 with a couple of green equipment.
