### ISSUE TITLE
Replace equipment crash

### ISSUE THREAD

**Issue by pfederighi** [DexterHuang/CyberCodeOnline#2245]
Started in inventory.
Unloaded upgrade from primary weapon.
Pressed back.
Pressed primary weapon.
Pressed replace equipment.
Crashed 

Pn19LHtrZXk6InNldFJvb3QiLHZhbHVlOmZ1bmN0aW9uKCl7T2JqZWN0KGkuYikoKS5nbygwKX19LHtrZXk6ImdldFF1ZXJ5U3RyaW5nIix2YWx1ZTpmdW5jdGlvbigpe3ZhciBlPWMuYi5xdWVyeVN0cmluZztyZXR1cm4gZS5zdGFydHNXaXRoKCI/IikmJihlPWUuc3Vic3RyaW5nKDEsZS5sZW5ndGgpKSxhLmEucGFyc2UoZSl9fV0sKG49bnVsbCkmJmwodC5wcm90b3R5cGUsbiksciYmbCh0LHIpLGV9KCk7dS5zdGF0ZT17fSx1Lm1hcFBhZ2VDb250YWkKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IENhbm5vdCByZWFkIHByb3BlcnRpZXMgb2YgdW5kZWZpbmVkIChyZWFkaW5nICdzdGFydHNXaXRoJykKVHlwZUVycm9yOiBDYW5ub3QgcmVhZCBwcm9wZXJ0aWVzIG9mIHVuZGVmaW5lZCAocmVhZGluZyAnc3RhcnRzV2l0aCcpCiAgICBhdCBGdW5jdGlvbi52YWx1ZSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXQuNmMxYzZhYTAuY2h1bmsuanM6MTozNDAxMikKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0LjZjMWM2YWEwLmNodW5rLmpzOjE6MTQ0MDIzNwogICAgYXQgaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5hMDliMDFjZi5jaHVuay5qczoxOjM0NzIKICAgIGF0IEplIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMzI2ZTIzYjMuY2h1bmsuanM6MTo0MTg4MikKICAgIGF0IGUudC50cmFjayAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjMyNmUyM2IzLmNodW5rLmpzOjE6NDYyMTQpCiAgICBhdCBrIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+QXBwTGF5b3V0LmEwOWIwMWNmLmNodW5rLmpzOjE6MzQ0OSkKICAgIGF0IEEgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35BcHBMYXlvdXQuYTA5YjAxY2YuY2h1bmsuanM6MTo0MzYwKQogICAgYXQgU2IgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0LjZjMWM2YWEwLmNodW5rLmpzOjE6MTQ0MDEyOSkKICAgIGF0IFhvIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMzI2ZTIzYjMuY2h1bmsuanM6MToxOTc5NzApCiAgICBhdCBqYSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjMyNmUyM2IzLmNodW5rLmpzOjE6MjA2ODU4KQ==

**Comment by DexterHuang** [comment]
fixed :)
