### ISSUE TITLE
Bug in the new upper/lower level limit dialog for market

### ISSUE THREAD

**Issue by AndroMi** [DexterHuang/CyberCodeOnline#2246]
It's practically impossible to enter a numerical value for the upper limit, as it immediately corrects the text to the value of the lower limit.
For instance: lower limit is set at "71", the user tries to input "75", but as soon as the user starts to type over the suggested (and preselected) value of "71", the code corrects the newly typed text "7" to "71". If one continues typing after that, the value will be cut at "420". It's not possible to type any alternative value - only the slider and spinner control can be used.

**Comment by DexterHuang** [comment]
yes, you might need to use slider for now
