### ISSUE TITLE
Add scrap() and destroy() to class ItemStack

### ISSUE THREAD

**Issue by donburks** [DexterHuang/CyberCodeOnline#23]
Add `scrap()` and `destroy()` functions to `class ItemStack` screen. 

This facilitates the gameplay scenario where an equipped item with upgrades attached is being unequipped, stripped of upgrades, and then scrapped. In the current workflow, you have to enter the Details screen to remove the upgrades, then close that screen, go to Inventory/Stats, hover, and scrap from there.

**Comment by DexterHuang** [comment]
good idea, will implement

**Comment by tripplehelix** [comment]
This is in the game no?
