### ISSUE TITLE
Suggestion on dungeons

### ISSUE THREAD

**Issue by Omnipotent-God** [DexterHuang/CyberCodeOnline#237]
![image](https://user-images.githubusercontent.com/76561796/103134544-cd236b80-46a9-11eb-85e2-2b8a63d31e05.png)

And also make the loot of boss slightly better. A good idea would be that boss drops blessing points, and for example blessing points can be used to bless (enhance) a gear, which can be only enhanced once per gear.

**Comment by Omnipotent-God** [comment]
bless is probably not the right word. To make it more stylized, perhaps use 'digital boosted'

**Comment by Omnipotent-God** [comment]
@DexterHuang read my suggestion! :( 

rofl
read it when you have time, if you dont please not to worry

**Comment by DexterHuang** [comment]
Oh I saw it just now, hm yeah locked door could be something to work on, feels like dungeon do need more features 🙂

**Comment by Omnipotent-God** [comment]
yeahh thx ;)

**Comment by tripplehelix** [comment]
This is in discord
