### ISSUE TITLE
Close tabs with middle mouse button.

### ISSUE THREAD

**Issue by Fribergz** [DexterHuang/CyberCodeOnline#25]
I would like to have the feature of closing tabs with the middle mouse button.

**Comment by DexterHuang** [comment]
i didnt even know there is this feature in VS Code lol good idea, i can implement that

**Comment by kleith** [comment]
Also with `ctrl`+ `w` it will be great.

**Comment by lostdesign** [comment]
Yeah or right click -> Close all. 

CTRL+W intercepts with the native feature to close the tab, wouldn't recommend that.

**Comment by tripplehelix** [comment]
This is implemented.
