### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Ragaru** [DexterHuang/CyberCodeOnline#253]
Got this issue when i was in the dungeon and opend a box/crate. (Player ID: Mosaic)

Pm9pZCAwOnQudHlwZSl8fChvPXRoaXMubnVsbFRpbGUpO3ZhciBwPXUuZ2V0KHt4OmMseTpsfSksZD1udWxsIT09KG49by50eXBlKSYmdm9pZCAwIT09bj9uOmEuYS5OVUxMO3AmJihkPXAudHlwZSxvPXApO3ZhciBoPVtdO2QudG9TdHJpbmcoKT09PWEuYS5FTkVNWS50b1N0cmluZygpJiYoaD1vLmdldENsYXNzT2JqZWN0KHMuYSwiZW5lbXkiKS5nZXRJbkNvbWJhdFBsYXllcnMoKSk7dmFyIHk9bnVsbD09PShyPWQpfHx2b2lkIDA9PT1yP3ZvaWQgMDoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IHVuZGVmaW5lZCBpcyBub3QgYW4gb2JqZWN0IChldmFsdWF0aW5nICdkLnRvU3RyaW5nJykKdmFsdWVAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmZiOTA0ZjMzLmNodW5rLmpzOjE6NjAwMDAwCmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0TW9iaWxlLjVhM2Q4YjgzLmNodW5rLmpzOjE6MTA5MDg3Cm1hcEBbbmF0aXZlIGNvZGVdCmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0TW9iaWxlLjVhM2Q4YjgzLmNodW5rLmpzOjE6MTA5MDQ2Cm1hcEBbbmF0aXZlIGNvZGVdCmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0TW9iaWxlLjVhM2Q4YjgzLmNodW5rLmpzOjE6MTA4OTMxCmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5mYjkwNGYzMy5jaHVuay5qczoxOjIyODMxMAphZUBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZmI5MDRmMzMuY2h1bmsuanM6MToyNTE0MwpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZmI5MDRmMzMuY2h1bmsuanM6MTozNTgyMgpkQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5mYjkwNGYzMy5jaHVuay5qczoxOjIyODI5MQokb0BodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZmI5MDRmMzMuY2h1bmsuanM6MTo3MzQzNTkKemFAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmZiOTA0ZjMzLmNodW5rLmpzOjE6NzQzMjQ4CmdjQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5mYjkwNGYzMy5jaHVuay5qczoxOjc3MzUxNAptY0BodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZmI5MDRmMzMuY2h1bmsuanM6MTo3NzM0MzkKc2NAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmZiOTA0ZjMzLmNodW5rLmpzOjE6NzcwNDQxCnNjQFtuYXRpdmUgY29kZV0KaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmZiOTA0ZjMzLmNodW5rLmpzOjE6NzIxNjMwCmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5mYjkwNGYzMy5jaHVuay5qczoxOjc5NzMwMApZaUBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZmI5MDRmMzMuY2h1bmsuanM6MTo3MjE1NzcKS2lAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmZiOTA0ZjMzLmNodW5rLmpzOjE6NzIxNTEyCmxjQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5mYjkwNGYzMy5jaHVuay5qczoxOjc3MDczNApGZUBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZmI5MDRmMzMuY2h1bmsuanM6MTozNzI0MQpOZUBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZmI5MDRmMzMuY2h1bmsuanM6MTozMzQ3OQpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZmI5MDRmMzMuY2h1bmsuanM6MToxOTYzNwpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZmI5MDRmMzMuY2h1bmsuanM6MToyNzg4NApodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZmI5MDRmMzMuY2h1bmsuanM6MTo1NzQxOApzZXRAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmZiOTA0ZjMzLmNodW5rLmpzOjE6NTgwNzkKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmZiOTA0ZjMzLmNodW5rLmpzOjE6NTk2MzA0CmxAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmZiOTA0ZjMzLmNodW5rLmpzOjE6NjY0NzQ2Cmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5mYjkwNGYzMy5jaHVuay5qczoxOjY2NDUzMQpfQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5mYjkwNGYzMy5jaHVuay5qczoxOjU5NDYyMwphQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5mYjkwNGYzMy5jaHVuay5qczoxOjU5NDgyNgpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZmI5MDRmMzMuY2h1bmsuanM6MTo1OTQ4ODUKUHJvbWlzZUBbbmF0aXZlIGNvZGVdCmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5mYjkwNGYzMy5jaHVuay5qczoxOjU5NDc3NwpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+ZmlyZWJhc2UtZGF0YWJhc2UuNDljZTI2OTkuY2h1bmsuanM6MTo0NDIxOQpRQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35maXJlYmFzZS1kYXRhYmFzZS40OWNlMjY5OS5jaHVuay5qczoxOjQ0NTgKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfmZpcmViYXNlLWRhdGFiYXNlLjQ5Y2UyNjk5LmNodW5rLmpzOjE6MTAwMzg1Cmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35maXJlYmFzZS1kYXRhYmFzZS40OWNlMjY5OS5jaHVuay5qczoxOjEwMDAwNApodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+ZmlyZWJhc2UtZGF0YWJhc2UuNDljZTI2OTkuY2h1bmsuanM6MTo5OTc0OQpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+ZmlyZWJhc2UtZGF0YWJhc2UuNDljZTI2OTkuY2h1bmsuanM6MToxNDA3ODQKW25hdGl2ZSBjb2RlXQpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+ZmlyZWJhc2UtZGF0YWJhc2UuNDljZTI2OTkuY2h1bmsuanM6MToxMzAwNDcKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfmZpcmViYXNlLWRhdGFiYXNlLjQ5Y2UyNjk5LmNodW5rLmpzOjE6MTI5ODkxCltuYXRpdmUgY29kZV0KaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfmZpcmViYXNlLWRhdGFiYXNlLjQ5Y2UyNjk5LmNodW5rLmpzOjE6MTE5OTQ5Cmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35maXJlYmFzZS1kYXRhYmFzZS40OWNlMjY5OS5jaHVuay5qczoxOjExOTg2NApodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+ZmlyZWJhc2UtZGF0YWJhc2UuNDljZTI2OTkuY2h1bmsuanM6MToxMTgwODcKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfmZpcmViYXNlLWRhdGFiYXNlLjQ5Y2UyNjk5LmNodW5rLmpzOjE6MTEzNTM4Cmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35maXJlYmFzZS1kYXRhYmFzZS40OWNlMjY5OS5jaHVuay5qczoxOjExNDE0OQpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+ZmlyZWJhc2UtZGF0YWJhc2UuNDljZTI2OTkuY2h1bmsuanM6MToxMTI3MTk=

**Comment by Ragaru** [comment]
Next Bug also happend in dungeon when i walekd into next room


PmxsPT09KHQ9aSl8fHZvaWQgMD09PXQ/dm9pZCAwOnQudHlwZSl8fChpPXRoaXMubnVsbFRpbGUpO3ZhciBmPW8uZ2V0KHt4OnUseTpjfSkscD1pLnR5cGV8fGEuYS5OVUxMO2YmJihwPWYudHlwZSxpPWYpO3ZhciBkPVtdO3AudG9TdHJpbmcoKT09PWEuYS5FTkVNWS50b1N0cmluZygpJiYoZD1pLmdldENsYXNzT2JqZWN0KHMuYSwiZW5lbXkiKS5nZXRJbkNvbWJhdFBsYXllcnMoKSk7dmFyIGg9bnVsbD09PShuPXApfHx2b2lkIDA9PT1uP3ZvaWQgMDoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IHVuZGVmaW5lZCBpcyBub3QgYW4gb2JqZWN0IChldmFsdWF0aW5nICdwLnRvU3RyaW5nJykKdmFsdWVAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjE4NDk5YjEwLmNodW5rLmpzOjE6NjAwMDQ4Cmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0TW9iaWxlLjdkZmMzMWQ3LmNodW5rLmpzOjE6MTA5MDg3Cm1hcEBbbmF0aXZlIGNvZGVdCmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0TW9iaWxlLjdkZmMzMWQ3LmNodW5rLmpzOjE6MTA5MDQ2Cm1hcEBbbmF0aXZlIGNvZGVdCmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0TW9iaWxlLjdkZmMzMWQ3LmNodW5rLmpzOjE6MTA4OTMxCmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi4xODQ5OWIxMC5jaHVuay5qczoxOjIyODMxMAphZUBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMTg0OTliMTAuY2h1bmsuanM6MToyNTE0MwpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMTg0OTliMTAuY2h1bmsuanM6MTozNTgyMgpkQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi4xODQ5OWIxMC5jaHVuay5qczoxOjIyODI5MQokb0BodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMTg0OTliMTAuY2h1bmsuanM6MTo3MzQ0MDcKemFAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjE4NDk5YjEwLmNodW5rLmpzOjE6NzQzMjk2CmdjQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi4xODQ5OWIxMC5jaHVuay5qczoxOjc3MzU2MgptY0BodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMTg0OTliMTAuY2h1bmsuanM6MTo3NzM0ODcKc2NAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjE4NDk5YjEwLmNodW5rLmpzOjE6NzcwNDg5CnNjQFtuYXRpdmUgY29kZV0KaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjE4NDk5YjEwLmNodW5rLmpzOjE6NzIxNjc4Cmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi4xODQ5OWIxMC5jaHVuay5qczoxOjc5NzM0OApZaUBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMTg0OTliMTAuY2h1bmsuanM6MTo3MjE2MjUKS2lAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjE4NDk5YjEwLmNodW5rLmpzOjE6NzIxNTYwCmxjQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi4xODQ5OWIxMC5jaHVuay5qczoxOjc3MDc4MgpGZUBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMTg0OTliMTAuY2h1bmsuanM6MTozNzI0MQpOZUBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMTg0OTliMTAuY2h1bmsuanM6MTozMzQ3OQpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMTg0OTliMTAuY2h1bmsuanM6MToxOTYzNwpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMTg0OTliMTAuY2h1bmsuanM6MToyNzg4NApodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMTg0OTliMTAuY2h1bmsuanM6MTo1NzQxOApzZXRAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjE4NDk5YjEwLmNodW5rLmpzOjE6NTgwNzkKdmFsdWVAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjE4NDk5YjEwLmNodW5rLmpzOjE6NjY2OQpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMTg0OTliMTAuY2h1bmsuanM6MToxNDEyNjAKbEBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMTg0OTliMTAuY2h1bmsuanM6MTo2NjQ3OTQKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjE4NDk5YjEwLmNodW5rLmpzOjE6NjY0NTc5CmdAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjE4NDk5YjEwLmNodW5rLmpzOjE6MTM5MTgzCmFAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjE4NDk5YjEwLmNodW5rLmpzOjE6MTM5Mzg2Cmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi4xODQ5OWIxMC5jaHVuay5qczoxOjEzOTQ0NQpQcm9taXNlQFtuYXRpdmUgY29kZV0KaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjE4NDk5YjEwLmNodW5rLmpzOjE6MTM5MzM3Cmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi4xODQ5OWIxMC5jaHVuay5qczoxOjE0MDQ1NwpsQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi4xODQ5OWIxMC5jaHVuay5qczoxOjY2NDc5NApodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMTg0OTliMTAuY2h1bmsuanM6MTo2NjQ1NzkKZ0BodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMTg0OTliMTAuY2h1bmsuanM6MToxMzkxODMKYUBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMTg0OTliMTAuY2h1bmsuanM6MToxMzkzODYKcHJvbWlzZVJlYWN0aW9uSm9iQFtuYXRpdmUgY29kZV0=

**Comment by tripplehelix** [comment]
Are these issues still there?
