### ISSUE TITLE
Abandon Quest

### ISSUE THREAD

**Issue by donburks** [DexterHuang/CyberCodeOnline#26]
Please give the ability to abandon a quest (ex. Join Dungeon). It's highly dependent on others to do it. And if no one is up for sharing a dungeon code, you're unable to do any other quests. Giving the ability to abandon the quest allows the player to pursue any of the others that randomly come up.

It's understood that Join Dungeon is a co-op gameplay mechanic, and having the quest there is to promote people playing together... however if I'm > lvl 30 and someone shares a lvl3 dungeon code...I'm just joining and exiting. I can't even benefit from the dungeon.

**Comment by DexterHuang** [comment]
yeah thats ture,
i am thinking of a way to resolve this... because if you can abandon people gonna keep refreshing it till they find the easiest onelol

**Comment by ryanadiaz** [comment]
@DexterHuang 
What about different types of quests? You could split it into 2 different categories: Daily Quests, and Advanced Quests.  Daily Quests, easier and there is a certain number of them per day, and you just keep doing them daily.  Advanced Quests, take longer, possibly span multiple days, and you are able to abandon up to 1 per day.

**Comment by DexterHuang** [comment]
@ryanadiaz oh that's awesome idea, I also have plan to add handmade and generated quests

**Comment by DexterHuang** [comment]
yoo, quests now can be abandoned and refreshed 👍
