### ISSUE TITLE
Muting certain users in chat

### ISSUE THREAD

**Issue by jmfiebak** [DexterHuang/CyberCodeOnline#287]
Hi!

I'm fairly new to this game but today I happened to notice a user just being unpleasanly rude in the chat using foul language and stuff like that. A few users mentioned that it wasn't the first time that this particular user behaved this way and they already issued this on discord. I'm issuing this here ust so it doesn't get lost somewhere in the chat. A simple "block user" feature would be very helpful for this kinda stuff.

Cheers
Joshua

**Comment by tripplehelix** [comment]
Added to discord
