### ISSUE TITLE
Game Suggestion: Fleshing out Dungeons

### ISSUE THREAD

**Issue by macniel** [DexterHuang/CyberCodeOnline#29]
Currently running a Dungeon with multiple People is a pain, as the only coordination is via chat which is global for everyone. It would improve coordination when on the Dungeon Map you can see which mob is being targetted by.

It would also be great to see the actual Healthbars of other people inside a Dungeon (currently the bar reflect the health of the current player).

It would be great if a player could use PainAway on others to facilitate the role of a supporter/healer/buffer.

**Comment by DexterHuang** [comment]
yeah good idea, I have added the feature allowing you to see players in combat,
real time player health and supporting other player is very nice idea and mechanic, 
i will think of some way to implement it 👍

**Comment by DexterHuang** [comment]
health bar is there now

using item on other players is being implemented soon
