### ISSUE TITLE
Dungeon Party List and dungeon exit confirm

### ISSUE THREAD

**Issue by byakkozen** [DexterHuang/CyberCodeOnline#293]
Ok a. I see a lot of people accidentally clicking Quit Dungeon. Add a Are you sure you want to exit? Y/N dialogue when u hit quit dungeon 

B. Add a party list in the dungeon screen that way you can keep track of who is in your dungeon (greyed out if they arent in the same room, white if they are) as well as their HP

C. In the combat screen, do the same thing so u can see who is fighting the same enemy as you and it would make it easier to heal other players
 > Use Item
 > select item 
> Use item on who?
No player option if its just you, player option if theres multiple people fighting the same enemy 

Optional but maybe create a chat inside the dungone that way ppl in the same dungeon can communicate easier especially to coordinate something like killing the challenge boss
@DexterHuang

**Comment by tripplehelix** [comment]
There's already a suggestion about listing players in dungeons. Added C to that suggestion :)
