### ISSUE TITLE
Crafting Suggestion

### ISSUE THREAD

**Issue by Zephyr8965** [DexterHuang/CyberCodeOnline#297]
For crafting, I feel like it might become very daunting as more content is added to the game, so it might help to open separate crafting menus by clicking on crafting skills instead of opening a single crafting file that has everything.

For example: clicking on my ammo crafting could bring up crafting recipes for ammo, specifically. It could even be dynamically generated by pulling up a crafting list and simply filtering it to only recipes that require ammo crafting (so if a recipe requires multiple skills, it will show up regardless of which of those required skills is clicked).

**Comment by tripplehelix** [comment]
Moved to #suggestions on discord
