### ISSUE TITLE
Upgrade Modules Streamline Suggestion

### ISSUE THREAD

**Issue by Zephyr8965** [DexterHuang/CyberCodeOnline#299]
I've noticed that upgrade modules can be a bit daunting to manage when updating gear. Something that might help is the tooltip that pops up when hovering over equipment could actually be widened to have a section that shows all upgrade modules in your inventory. Then, you can just click the upgrade modules to attach/detach them as if in the upgrade menu for the item.

This would prevent needing to go into a separate page every time we need to alter the upgrade modules on an item.

Also, a "detatch all" button might even be nice to just auto remove all upgrade modules from all equipment would be really nice. Then, I can just remove all my upgrades, compare equipment, pick it all out, then attach upgrades to my new set.

**Comment by tripplehelix** [comment]
This has already been suggested.
