### ISSUE TITLE
no way to view stats on player

### ISSUE THREAD

**Issue by suark** [DexterHuang/CyberCodeOnline#3]
It would be helpful to have a stats screen of your current overall stats.

**Comment by hildjj** [comment]
add a method to invite a person to a fight?

**Comment by hildjj** [comment]
and another method to teleport to where they currently are.

**Comment by hildjj** [comment]
`whisper("[type message here]")`

**Comment by suark** [comment]
really liking the new stats screen!

**Comment by DexterHuang** [comment]
> `whisper("[type message here]")`

yeah this should be in the stats page :D so you can DM people easily

**Comment by DexterHuang** [comment]
> really liking the new stats screen!
> 
> How is the damage stat calculated?

thanks~
the damage is simply the sum of all damage + base damage
