### ISSUE TITLE
Remove "homeless" and "outcast" from list of enemies.

### ISSUE THREAD

**Issue by jeremy-j-ackso** [DexterHuang/CyberCodeOnline#30]
The game shouldn't suggest that homeless and outcast people are enemies who should be attacked.

...Unless you're also going to add a "morality" trait to the game that can lead players down different paths.

**Comment by DexterHuang** [comment]
thanks for the issue :) homeless has been removed
but isnt outcast people bad? like they have done some criminal stuff so they been outcast by their government

**Comment by jeremy-j-ackso** [comment]
I guess it depends on how you interpret "outcast". "Outcast" doesn't really match a specific crime the way "murderer", "mugger", and others do. Maybe "fugitive" would be a good replacement?

For that matter, you could probably add "corrupt cop". A corrupt cop hasn't been outcast by their government, but is definitely a criminal, right?

I wouldn't define whether or not somebody is worthy of being an "enemy" just by whether or not they adhere to government dictates. If you did go by that definition, then maybe add "litterer", "speeder", and "jaywalker" to the list of enemies?

Also, this makes me wonder about who the players are? Are we styled after Judge Dredd, agents of the government tasked with being Judge, Jury, and Executioner? Are we independent vigilantes? Are we loosely organized bounty hunters taking on jobs?

**Comment by DexterHuang** [comment]
I will think about how we should implement more lore stuff, 
meanwhile i have removed the names mentioned
