### ISSUE TITLE
Resizable chat pane (and small monitor issues)

### ISSUE THREAD

**Issue by crosma** [DexterHuang/CyberCodeOnline#32]
I'm currently playing on a 13ish inch laptop (don't ask, it sucks) and I only get 3 lines of visible chat at a time but scrolling with the mouse wheel moves 4 lines. I know this is a problem on my end, I could make the mouse scroll less. But a good and generally useful solution would be to make it so you can drag/drop to resize the chat pane. 

If you use jQueryUI, their resizeable function has worked excellent for me in the past.

Another issue I've not come up with a good solution for is that the online players list is off the screen unless I collapse a section above it.

**Comment by DexterHuang** [comment]
feature implemented :)
