### ISSUE TITLE
Health is not rounded properly when healing multiplier is involved

### ISSUE THREAD

**Issue by greengrass17** [DexterHuang/CyberCodeOnline#323]
![Screenshot (4)](https://user-images.githubusercontent.com/7025841/104504508-3a605780-55eb-11eb-9719-b1231421efcc.png)

**Comment by DexterHuang** [comment]
Oh hey, thanks for reporting, what do you mean by amp?

**Comment by greengrass17** [comment]
Sorry i mean healing multiplier

**Comment by DexterHuang** [comment]
should be fixed now
