### ISSUE TITLE
Discord link in Readme.md does not work

### ISSUE THREAD

**Issue by Salman-Asif** [DexterHuang/CyberCodeOnline#3283]
Discord link in Readme.md does not work. I tried opening this in Google Chrome mobile browser. It says Bad gateway nginx error.

**Comment by TannerSchultz2006** [comment]
Can confirm. There is an error in some aspect of it. For anyone working on it current link is https://discord.link/cco and is on line 9 or README.md. I would fix myself except for myself lacking the discord link.

**Comment by TannerSchultz2006** [comment]
Note: I have put in a pull request for the solution of this error! For now @Salman-Asif  use https://discord.gg/kbjjdpWFPb to join CyberCodes official discord!

**Comment by Salman-Asif** [comment]
@TannerSchultz2006 Is it ok if I raise the PR?

**Comment by TannerSchultz2006** [comment]
I believe so? I am not sure. I don't know how they work their system here. I put in a PR, but they have not gotten to it yet.

**Comment by Lance0-32** [comment]
should probably get closed; discord link works fine now
