### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wilam0513** [DexterHuang/CyberCodeOnline#3350]
IC8qISBGb3IgbGljZW5zZSBpbmZvcm1hdGlvbiBwbGVhc2Ugc2VlIG1haW4uNjA0NDc5MjEuanMuTElDRU5TRS50eHQgKi8KPjtjbD1udWxsLGRsKGUsdCxuKSxmbD1pLG51bGwhPT0oY2w9cikmJihmbD8oZT1jbCxuPW4uc3RhdGVOb2RlLDg9PT1lLm5vZGVUeXBlP2UucGFyZW50Tm9kZS5yZW1vdmVDaGlsZChuKTplLnJlbW92ZUNoaWxkKG4pKTpjbC5yZW1vdmVDaGlsZChuLnN0YXRlTm9kZSkpO2JyZWFrO2Nhc2UgMTg6bnVsbCE9PWNsJiYoZmw/KGU9Y2wsbj1uLnN0YXRlTm9kZSw4PT09ZS5ub2RlVHlwZT9saShlLnBhcmVudE5vZGUsbik6MT09PWUubm9kZVR5cGUmJmxpKGUKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpOb3RGb3VuZEVycm9yOiBGYWlsZWQgdG8gZXhlY3V0ZSAncmVtb3ZlQ2hpbGQnIG9uICdOb2RlJzogVGhlIG5vZGUgdG8gYmUgcmVtb3ZlZCBpcyBub3QgYSBjaGlsZCBvZiB0aGlzIG5vZGUuCkVycm9yOiBGYWlsZWQgdG8gZXhlY3V0ZSAncmVtb3ZlQ2hpbGQnIG9uICdOb2RlJzogVGhlIG5vZGUgdG8gYmUgcmVtb3ZlZCBpcyBub3QgYSBjaGlsZCBvZiB0aGlzIG5vZGUuCiAgICBhdCBwbCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjYwNDQ3OTIxLmpzOjI6MjE2NTkzKQogICAgYXQgdmwgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi42MDQ0NzkyMS5qczoyOjIxNzg1MikKICAgIGF0IHlsIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uNjA0NDc5MjEuanM6MjoyMTgzMTIpCiAgICBhdCB2bCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjYwNDQ3OTIxLmpzOjI6MjE4MDAyKQogICAgYXQgeWwgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi42MDQ0NzkyMS5qczoyOjIxODMxMikKICAgIGF0IHZsIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uNjA0NDc5MjEuanM6MjoyMTgwMDIpCiAgICBhdCB5bCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjYwNDQ3OTIxLmpzOjI6MjE4MzEyKQogICAgYXQgdmwgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi42MDQ0NzkyMS5qczoyOjIxODAwMikKICAgIGF0IHlsIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uNjA0NDc5MjEuanM6MjoyMTgzMTIpCiAgICBhdCB2bCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjYwNDQ3OTIxLmpzOjI6MjE4MDAyKQ==

**Comment by HhinSTILLlearning** [comment]
Don't bother the developers, you idiots

**Comment by DexterHuang** [comment]
@HhinSTILLlearning he is sending error code for me don't worry.
thanks for the report, the issue should be fixed already
