### ISSUE TITLE
[Bug] AFK job Reverse Engineer Scraps

### ISSUE THREAD

**Issue by rivetheadf** [DexterHuang/CyberCodeOnline#343]
The first time I reverse engineered 10 scraps and the timer said 1 minute.  It wasn't enough to level, so I did 10 more and it said it would take 1 minute, but the timer was for two minutes.

I just did it again, but with 20 scraps the first time.  It said it would take 2 minutes and it did.  Again it wasn't enough to level so I did 20 more.  It said it would take 2 minutes, but the timer was for 4 minutes.

**Comment by tripplehelix** [comment]
Was this fixed? I know it was tasked about.

**Comment by rivetheadf** [comment]
I'll test it out when I'm done with my current afk mission and let you know.

**Comment by rivetheadf** [comment]
So I ran a few tests and the original problem is still there, here's what
happened:

1.  Reverse engineered 10 tech parts, it took the 1 minute it said it
would.  Went to the Me tab and back and did 10 more parts.  Before tapping
the confirm button, it said it would take 1 minute.  Tapped confirm and the
timer was at 2 minutes.  Comparing it to my clock, it took 2 minutes.

2.  Without doing anything else, I went to the chat tab and me tab then
back to run 10 more tech.  The timer said 1 minute before tapping confirm.
After confirming, it took 2 minutes.

3.  This time I went to the city center, then back to the commercial area
and reverse engineered 10 more tech.  The timer was back to the correct 1
minute.

4.  For curiosity's sake, I then went into each tab and back, without
leaving the commercial area.  I ran 20 tech, which before tapping confirm,
should take 2 minutes.  After tapping confirm, it took 3 minutes.

I would have tested starting with different quantities, but I'm maxed on xp
and out of tech.  So it seems reverse engineering more than once without
leaving the commercial area, will add the time to the first timer.  That
value isn't being reset until you leave the area first.

I hope that helps.  Thanks for making a great game!

**Comment by tripplehelix** [comment]
@DexterHuang Here's a bug that's still around ;)

**Comment by DexterHuang** [comment]
This is very weird but indeed lol checking now

**Comment by tripplehelix** [comment]
My latest 10 minute print is stated to now take 2 hours... that's not even an option when studying printing....

**Comment by tripplehelix** [comment]
Dex seems to think this might be fixed, let me know if it's not.
