### ISSUE TITLE
[Feature Request] Add "bank" icon to AFK screen for checking deposited inventory

### ISSUE THREAD

**Issue by cmenning** [DexterHuang/CyberCodeOnline#3489]
Under the "Finish Now" button, next to "Amadon" and "My Stall", please add a bank button. This should allow you to browse (but not interact) with the items you've deposited in the bank.

Often while AFK I'll want to check what I've saved in the bank, usually because of a conversation ongoing in chat. Many times, that knowledge is useful in the moment, but much less useful after a long time waiting for the AFK task to finish so I can go to the bank and check (ie, keeps the conversation flowing in the moment but becomes redundant later). Being able to check the bank inventory would not affect game balance in any way, but would be a substantial quality of life improvement.

**Comment by julohaq2** [comment]
[]()~~~~
