### ISSUE TITLE
More info on secondary levels

### ISSUE THREAD

**Issue by crosma** [DexterHuang/CyberCodeOnline#35]
It would be nice if there was more information available on what benefit there is to leveling secondary skills. Printing is pretty obviously but not immediately so. Medical/ammo/scavenge levels have no apparent benefit at all.

I think a good place to put this info would be comments on each level in Stats.ts.

**Comment by crosma** [comment]
Also, if there is currently no benefit, please say that in the comment.

**Comment by crosma** [comment]
Ah, I found there is more info in the comments for training each skill. It's still pretty vague and easy to miss though.

**Comment by tripplehelix** [comment]
This is now in the tutorial
