### ISSUE TITLE
Looting Inventory Bug

### ISSUE THREAD

**Issue by pinct** [DexterHuang/CyberCodeOnline#359]
I've noticed an annoying bug when trying to loot crates or enemies. Sometimes when you click take all, the inventory opens back up, and selecting either discard or take all responds woth the error "No Inventory open" and the only way to get unstuck is by closing and reopening the app. This can probably be fixed by closing any open inventories when the error is thrown.

**Comment by DexterHuang** [comment]
Issue fixed :)
