### ISSUE TITLE
Disincentivize killing much lower level enemies

### ISSUE THREAD

**Issue by crosma** [DexterHuang/CyberCodeOnline#37]
Currently there is good value in killing enemies much lower level than you because of the speed at which you can plow through them. You get loot and even XP faster because its only a couple clicks per kill. This can make it difficult for lower level players to get any kills.  

My suggestion would be to drastically reduce XP gain for enemies starting 3 levels below the players down to 5 levels at which zero XP is given. Also, do approximately the same for loot. You could even go so far as to make enemies that are too weak flee from a fight so the player does not even have the ability to kill them.

**Comment by lordpidey** [comment]
Bad idea.

Given how gear dependant the game is, this means if someone levels up, and doesn't have good gear, that they're going to be unable to progress.

**Comment by DexterHuang** [comment]
Hey, currently if the enemy is 3 level below your average level (average level of item you use) you won't get any loot. 
Is the feature bugged? I just added it yesterday, let me know if its not working

**Comment by crosma** [comment]
@DexterHuang, @lordpidey does have a point. Even at level 12 with decent gear I tend to attack level 8-9 enemies. And that's going to get worse because I'll probably need to be level 15 before I can earn my 3rd key to go to the next zone.

**Comment by DexterHuang** [comment]
Yeah that's why the exp and loot cap is bound to your item level not your player level

Do you mean you with level 15 Gears cannot defeat level 14-15 enemies? If so there is balance issue

**Comment by DexterHuang** [comment]
I have implemented another cap where player level cannot be 6 level above the enemy,
let me know if needs more adjustment
