### ISSUE TITLE
[FR]: Option to change colorscheme

### ISSUE THREAD

**Issue by lukesahula** [DexterHuang/CyberCodeOnline#40]
It would be handy to be able to change the colorscheme to match the one you use at work. :)

**Comment by crosma** [comment]
Does VSCode have exportable themes? Might be cool to make a parser for those that allows any theme.

**Comment by DexterHuang** [comment]
This might be not very easy to implement, but still possible
however I think this would be low priority for now

**Comment by tripplehelix** [comment]
Added to Discord
