### ISSUE TITLE
Clean up duplicate system messages

### ISSUE THREAD

**Issue by crosma** [DexterHuang/CyberCodeOnline#41]
Currently there are a lot of duplicate messages. 

> [system]: You received 8640 SCAVENGE experience points 
> [system]: You received 36 ammunition tech parts 
> [system]: You received 24 medical tech parts 
> [system]: You leveled up your scavenge skill 
> [system]: You received ammunition tech parts 
> [system]: You received medical tech parts 

While the XP gain and level up messages are different, they could also be combined into one line.

**Comment by DexterHuang** [comment]
I have cleaned it up abit, let me know if there are still some
