### ISSUE TITLE
Scrapping with module attached

### ISSUE THREAD

**Issue by donburks** [DexterHuang/CyberCodeOnline#42]
Scrapping an item with a module attached has two bugs:

1) It shouldn't let you do it in the first place. An error should be generated that you have to unequip modules before scrapping.

2) If you don't do #1, then you should get tech scraps back for both the item AND the module. Currently, you only get 1 tech scrap, for the item itself.

**Comment by danofsatx** [comment]
I (AdmiralDiemos) asked this in the chat last week. It also shouldn't let you sell the item with the upgrade modules attached to the weapon smith. It could be an added bonus to items being sold in the player's stall.

**Comment by DexterHuang** [comment]
@danofsatx yeah,hmm but why can't it be sold at player stall tho? I think is fine?

**Comment by tripplehelix** [comment]
Added to discord
