### ISSUE TITLE
AFK time reading is buggy

### ISSUE THREAD

**Issue by Felixkiller** [DexterHuang/CyberCodeOnline#428]
Sometimes when farming time is read wrong or just appears to be more hours than the original time 2 hours became 10 the back to 2 hours i use my android is it the code or my phones performance?

**Comment by tripplehelix** [comment]
It's a known bug, what you can do is make sure the time on your phone is correct. Otherwise restarting the app should fix it.

**Comment by Felixkiller** [comment]
ThanksSent from my Galaxy
-------- Original message --------From: tripplehelix <notifications@github.com> Date: 2/3/21  20:22  (GMT+07:00) To: DexterHuang/CyberCodeOnline <CyberCodeOnline@noreply.github.com> Cc: Felixkiller <felixjuatsa@gmail.com>, Author <author@noreply.github.com> Subject: Re: [DexterHuang/CyberCodeOnline] AFK time reading is buggy (#428) 
It's a known bug, what you can do is make sure the time on your phone is correct. Otherwise restarting the app should fix it.
