### ISSUE TITLE
Did not receive purchased units

### ISSUE THREAD

**Issue by homeofpoe** [DexterHuang/CyberCodeOnline#436]
I purchased 100 units but did not receive them in game.  There was an error about auto renew.  I was charged for the $1.

**Comment by DexterHuang** [comment]
@homeofpoe  hello, sorry about that, can i have your player name? 
was there something unusual happening when you were doing the purchase?
like did you close the app right after you click purchase or something?

**Comment by homeofpoe** [comment]
Account name is Riose.  I paid using Google Play balance. I do have adguard
running in the background. I did not close anything or swipe away from the
program while it was processing. I hope that helps!

**Comment by tripplehelix** [comment]
I just got the same 'autorenewing' error. Was checking my afk time, then switched to chat and it appeared.

**Comment by DexterHuang** [comment]
@homeofpoe  hey thanks so much for the report, I have found the problem and fixed it, I will manually send you Unit in game :D

**Comment by DexterHuang** [comment]
@homeofpoe  you show receive the Units now :)
