### ISSUE TITLE
Double pop-up to loot enemies afted defeat.

### ISSUE THREAD

**Issue by HoneySyrup** [DexterHuang/CyberCodeOnline#442]
Sometimes when you defeat an enemy and click loot all too fast, it will trigger the same screen to appear, but ater clicking loot all again, it will show an error. I'll be pending to post screenshots.

**Comment by tripplehelix** [comment]
I have experienced this on multiple occasions. I have moved this to the bug spreadsheet https://docs.google.com/spreadsheets/d/1cudIpT0gKAL48MgIaG22cSkj6jySpwxJ8zqboekG5K8/edit?usp=sharing
