### ISSUE TITLE
Error when viewing a profile in Friend List

### ISSUE THREAD

**Issue by Misaki290** [DexterHuang/CyberCodeOnline#459]
I clicked on a profile (forgot who he/she was) in my friend list and the error "Uh Oh, something went wrong" error appeared.
This is the hash/id of the error:

PkRpc3RhbmNlKXRocm93IG5ldyBSYW5nZUVycm9yKCJsb2NhbGUgbXVzdCBjb250YWluIGxvY2FsaXplLmZvcm1hdERpc3RhbmNlIHByb3BlcnR5Iik7dmFyIHY9T2JqZWN0KG8uYSkoZSx0KTtpZihpc05hTih2KSl0aHJvdyBuZXcgUmFuZ2VFcnJvcigiSW52YWxpZCB0aW1lIHZhbHVlIik7dmFyIHksZyxtPU9iamVjdChzLmEpKGgpO20uYWRkU3VmZml4PUJvb2xlYW4oaC5hZGRTdWZmaXgpLG0uY29tcGFyaXNvbj12LHY+MD8oeT1PYmplY3QoaS5hKSgKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpSYW5nZUVycm9yOiBJbnZhbGlkIHRpbWUgdmFsdWUKUmFuZ2VFcnJvcjogSW52YWxpZCB0aW1lIHZhbHVlCiAgICBhdCBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+QXBwTGF5b3V0LjZmYzg0NGQyLmNodW5rLmpzOjE6NDU2ODgzCiAgICBhdCBoIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+QXBwTGF5b3V0LjZmYzg0NGQyLmNodW5rLmpzOjE6NDU3OTM2KQogICAgYXQgZS52YWx1ZSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXQuZmY0OTI2OTQuY2h1bmsuanM6MToxMTkyMTApCiAgICBhdCByYSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuODVhYTg3ZDkuY2h1bmsuanM6MToxMjE4NjkpCiAgICBhdCBYbyAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjU5YzUyZWIyLmNodW5rLmpzOjE6MTEyMjY5KQogICAgYXQgYmwgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi41OWM1MmViMi5jaHVuay5qczoxOjE1ODc4NikKICAgIGF0IGJ1IChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uNTljNTJlYjIuY2h1bmsuanM6MToxNTE0MjMpCiAgICBhdCB5dSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjU5YzUyZWIyLmNodW5rLmpzOjE6MTUxMzQ4KQogICAgYXQgY3UgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi41OWM1MmViMi5jaHVuay5qczoxOjE0ODM1MCkKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi41OWM1MmViMi5jaHVuay5qczoxOjk5NTQw

**Comment by tripplehelix** [comment]
@DexterHuang has this issue been fixed?

**Comment by Misaki290** [comment]
> @DexterHuang has this issue been fixed?

The  problem doesn't appear for me, so I think that it has been fixed. I'll close the issue.
