### ISSUE TITLE
Display Ideas

### ISSUE THREAD

**Issue by matsu4ki** [DexterHuang/CyberCodeOnline#46]
Next to the item, add a emoji.
It is desirable to be able to switch between emoji mode and text only mode.

e.g. 

- 🗡 primaryWeapon
- 🔫 specialWeapon
- 💣 destructiveWeapon
- 🧢 helmet
- 👕 upperArmer
- 👖 lowerArmor
- 🥾 boots

**Comment by DexterHuang** [comment]
yes 👍  
i am planing to use more subtle svg icons for those ;)

**Comment by tripplehelix** [comment]
This is in the game now
