### ISSUE TITLE
Transactions always fail

### ISSUE THREAD

**Issue by Nero1163** [DexterHuang/CyberCodeOnline#460]
![Screenshot_20210318-214842_Google Play Store](https://user-images.githubusercontent.com/80932571/111720162-ba957a00-8833-11eb-8b20-634660fb0b4f.jpg)
![Screenshot_20210318-214826_Google Play Store](https://user-images.githubusercontent.com/80932571/111720169-bcf7d400-8833-11eb-897e-fcc7d20fd363.jpg)

Transactions always decline no matter what I'm attempting to buy. Both cards work everywhere else I've tried.

**Comment by tripplehelix** [comment]
Thank you i have added this to the bug tracker
