### ISSUE TITLE
Blocking people option

### ISSUE THREAD

**Issue by Misaki290** [DexterHuang/CyberCodeOnline#461]
Since there is a way to PM people privately there should be a way to block people as well.
Blocking from sending Mails and, if possible, even from seeing what they type in Global Chat.

I already had some bad experience with some people (won't say who, at this point, it doesn't matter) and this needs to be implemented badly.

**Comment by xnkzzxd** [comment]
I agree, so far, the player i met is wholesome :3

**Comment by tripplehelix** [comment]
Added this to the suggestions spreadsheet
