### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Rhezamon** [DexterHuang/CyberCodeOnline#462]
is:open label:bug hello, my in game name is Rhezamon and i got message error_quest_progresion or something like that when i finish kashi key fragments and i Don't get the next quest the yamesa key fragments is this where i report it? Thanks for the game it's amazing, just need some bug patch 🙂👍

**Comment by Rhezamon** [comment]
Thank you 😊😊😊

**Comment by tripplehelix** [comment]
You'll get the next key quest when you are high enough level.
