### ISSUE TITLE
Quick remove modules

### ISSUE THREAD

**Issue by kimileta** [DexterHuang/CyberCodeOnline#47]
Suggestion: Add an option to quick remove all attached modules from an item in your inventory. That way it's easier to move modules from one weapon to a newer weapon, rather than going in to the old weapon's module page and clicking on every individual module to detach them.

**Comment by s3rvant** [comment]
How about automatically removing attached modules when an item is moved to inventory?

In mobile interface equipping an item moves to screen to view that item's information so having the previous item automatically detach its modules would allow those same modules to immediately be available for adding to the newly equipped item.

**Comment by tripplehelix** [comment]
Added to #suggestions on discord.
