### ISSUE TITLE
Shield Overhaul and Additional Feat.

### ISSUE THREAD

**Issue by Alextherude** [DexterHuang/CyberCodeOnline#474]
Shield Mod/Stats on equip need an absolute overhaul buff as they're pretty much junk when compared to over mods with crit/crit dmg/dodge, etc.

Even if you min-max build to be all extra shields, best it'll do is tank one hit for you at the start of every combat, and that really doesn't seem very good. Maybe ramp up the shield HP by a lot, since there are in-game buffs for them.

Don't quite know if it's in progress, but maybe a few rare mini-boss types in dungeons. Can be given [Elite] prefix to signify higher drop rate for very rare equipments/loots.

Nice game you have here btw Dexter, hope it improves greatly in the future!

**Comment by tripplehelix** [comment]
Added this to be voted on discord.
