### ISSUE TITLE
A really wierd and rare tech scrap error 

### ISSUE THREAD

**Issue by Misaki290** [DexterHuang/CyberCodeOnline#478]
Some days ago when I tried to scrap multiple trash gear parts I encountered a really wierd error and I don't remember having until now or anybody complaining about having it.
Despite what the error said, I had only 3 Tech Scraps at the time.
Also, the error was gone after I restarted the app.
Still very wierd.
![Screenshot_20210409-003942](https://user-images.githubusercontent.com/79731146/114247964-1ff60a00-999f-11eb-9e35-6d86a00c9bef.png)

**Comment by tripplehelix** [comment]
Seems the game desynced with the server. Which is why refreshing fixed this. This is a long standing issue.
