### ISSUE TITLE
Duplicate Secret Key

### ISSUE THREAD

**Issue by phuc1710** [DexterHuang/CyberCodeOnline#479]
As a result of clearing the duplicative dungeons and my curiosity. I have 2 Flori key in secret key section inventory, and I kinda regret now. Could you please remove the duplicate key in my inventory? Also, I have a suggestion that the secret keys are not craftable from the terminal once you had them. Thank you very much for considering my suggestion.

Here is my screenshot of the duplicate secret key. My username is LilSheep.
![Dup key](https://user-images.githubusercontent.com/63486411/114265296-3a20fe00-9a1a-11eb-9edb-2cd291844f85.png)

**Comment by tripplehelix** [comment]
@DexterHuang Could you remove the dupe key for @phuc1710? While you're at it could you remove my duplicate Floranda key?

I have posted this suggestion to the discord for voting.

**Comment by tripplehelix** [comment]
https://discord.com/channels/742992894167744552/770950123396136981/830420022718496828

**Comment by andycandy-de** [comment]
Can you please also remove my duplicate key :-D TY
