### ISSUE TITLE
About the chat display

### ISSUE THREAD

**Issue by SupportCharacter** [DexterHuang/CyberCodeOnline#484]
I Play this game on mobile. I once put my thumb in front of the chat display while i was in a dungeon. It instantly felt quiet, like escaping a thunderstorm and closing the door behind you. Now it is an issue because sometimes you might want to concentrate on your gameplay with no distractions (the chat is the distraction) and sometimes you want the noise. I say put that in the top priorities, chopchop!

**Comment by SupportCharacter** [comment]
Btw. Nice work and take your Time Dexter.

**Comment by tripplehelix** [comment]
Added this for voting in the suggestions channel on discord.
