### ISSUE TITLE
BTC not received from items sold on player market while fighting monster in dungeon

### ISSUE THREAD

**Issue by YewMeng** [DexterHuang/CyberCodeOnline#489]
### Issue: 
Did not receive any BTC from my sale on player market even though I was notified with 2 transactions and the items were in fact disappeared from my stall. 
The transactions happened while I was killing a monster in CHALLENGE_LV_34_37 dungeon, where I received the bitcoins from the monster but not from the sales. 
I've also tried restarting the app a few times, but bitcoins hasn't change. BTC stayed around 90,000 BTC, even though I should've gained 339,993 BTC from the last 2 sales. 

### IGN: 
Lym0

### Transaction 1
> HBUNKNOWN have purchased 6 legendary helmet cache from your stall, you have earned 299994 BTC
today at 2:19 PM

### Transaction 2
>Sosig_Lord27 have purchased 1 Legendary ascot cap of Crit Chance from your stall, you have earned 39999 BTC
today at 2:20 PM

![Screenshot_20210416-151228](https://user-images.githubusercontent.com/32905510/114986194-48619500-9ec6-11eb-96c1-dab27a62ae5c.jpg)

**Comment by DexterHuang** [comment]
hello, thanks for the very detailed report :) I will send you the missing btc
