### ISSUE TITLE
Background sounds

### ISSUE THREAD

**Issue by SupportCharacter** [DexterHuang/CyberCodeOnline#497]
Some sounds in specific areas. Example, thunderstruck basketball court with rolling thunder background sound, maybe even some rain. There is a bar somewhere, there could be some relaxing jazz playing in the background, no need to be a lengthy track. Crowd noises and cars being driven or honking in urban areas. The Hyperloop should get a sound byte. Even if not done globally right away, we should experiment one right away. I vote the Hyperloop.

**Comment by tripplehelix** [comment]
Added to suggestions on discord
