### ISSUE TITLE
Global Skip Bug

### ISSUE THREAD

**Issue by Samek15** [DexterHuang/CyberCodeOnline#499]
Went to activate Global Skip for Community and didn't activate globally. Here is steps:

1. Short on bits
2. Redirected to shop
3. Bought bits 
4. Activated 180min Global Skip
5. Network Error message
7. Reboot App
8. Skip activates for me but not for anyone else.

**Comment by tripplehelix** [comment]
@DexterHuang @Samek15 has this issue been sorted?

**Comment by DexterHuang** [comment]
this shouldnt happen now, its long time ago
