### ISSUE TITLE
Equipment popup comparing inventory stats to equipped

### ISSUE THREAD

**Issue by xbenjii** [DexterHuang/CyberCodeOnline#5]
When hovering equipment in the inventory, it should show a popup on hover comparing stats to the equipped slot.

**Comment by xbenjii** [comment]
You could maybe add tiers of autoScrap too (destroy trash only, destroy common only)

**Comment by DexterHuang** [comment]
hmmm yeah, currently it only scrap common or below tier time, high tier time will always be kept

**Comment by hildjj** [comment]
Use diff format, as if it's a pull request.

**Comment by DexterHuang** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/18545294/90307796-552f8280-df0c-11ea-83cb-a1bccc80231d.png)
;)
