### ISSUE TITLE
Different max password lengths mobile/desktop

### ISSUE THREAD

**Issue by SitiSchu** [DexterHuang/CyberCodeOnline#501]
The mobile app/website allows signing up with a 64+ character password but the desktop site is limited to 64 characters. 

Workaround for this is resizing the browser window to get to the mobile site and login there.

**Comment by tripplehelix** [comment]
@DexterHuang this is the password issue I was referring to, has this now been fixed then as per our discussion?

@SitiSchu Once dex gives the all clear would you like to test this for us?

**Comment by DexterHuang** [comment]
this should be fixed, can anyone confirm ?@@

**Comment by SitiSchu** [comment]
I will try in a bit

**Comment by SitiSchu** [comment]
It works fine now with a 128 character password.
