### ISSUE TITLE
Dungeon enemy

### ISSUE THREAD

**Issue by jade8600** [DexterHuang/CyberCodeOnline#502]
A dungeon enemy got stuck in a triangular outcrop of wall tiles. There is no way to reach it.

**Comment by tripplehelix** [comment]
@DexterHuang This is also reported here: https://discord.com/channels/742992894167744552/770950101710667796/833549660576546826

**Comment by DexterHuang** [comment]
I think we need to remove the room

**Comment by tripplehelix** [comment]
Which room? The + one?

**Comment by tripplehelix** [comment]
OK I'll remove it.
