### ISSUE TITLE
Chat text automatically slide down

### ISSUE THREAD

**Issue by MagicZDS** [DexterHuang/CyberCodeOnline#529]
In web version, the text does not stay in place. It may be a good feature to always see the last comment, but when you need to see a previous one, the chat list keep sliding down. Perhaps a button like in Eclipse console pane would be usefull : 
![image](https://user-images.githubusercontent.com/40262363/115529183-f9837900-a292-11eb-9d0d-d029a28fd29c.png)

**Comment by tripplehelix** [comment]
Could you please post this suggestion to discord for voting in the suggestions channel.
