### ISSUE TITLE
Can't lock any equipment while they were equipped

### ISSUE THREAD

**Issue by Disivius** [DexterHuang/CyberCodeOnline#539]
![20210422_054658](https://user-images.githubusercontent.com/83016569/115717947-8714a680-a32f-11eb-8f6d-8e06b30fad7c.jpg)

Hey! Nothing major, can't lock equipment while one's wearing it, that's all, have a good day!

**Comment by tripplehelix** [comment]
Could you please post this suggestion to discord for voting in the suggestions channel.
