### ISSUE TITLE
Items, Armor Sets, Armor Classes, In-App Purchases Ideas

### ISSUE THREAD

**Issue by darkrevelations** [DexterHuang/CyberCodeOnline#542]
In order to create an other game aspect (collection of armor sets), I'd like to suggest the addition of several things.

### **ARMOR AND WEAPON SETS**

While no boost would be provided by the armor set, a specific set of armor might be titled something like "Veyrin's Nightmare Armor [type of armor]" (not that a player name would be necessary).

These sets would be comprised of weapons and armor. 

### **Rarity Modifiers Specific to sets**

Rare, Legendary, and Epic sets to back the sets idea.

### **In-App Purchase to Add Set to Game**

A multi-tier in-app donation purchase that allows you to add a set of your choosing (name + rarity based on purchase tier).

### **New File System Arrangement for Set Armor and Weapons**

A dedicated, locked file folder for sets of armor and weapons to prevent unpurchased additions.

### **Potential Set Bonuses for Items Added/Selected by Community**

Set bonuses (EXP bonus, attack bonus, defense bonus, etc.) that apply when you equip a full set of the same armor.

### **Boss Armor Drops/Sets**

Armor named after bosses that drop and guarantee a set bonus attribute and boosted stats with a <1% chance of drop.

**Comment by tripplehelix** [comment]
Could you please post this suggestion to discord for voting in the suggestions channel.
