### ISSUE TITLE
Event Specific MOBs, NPCs, and items

### ISSUE THREAD

**Issue by darkrevelations** [DexterHuang/CyberCodeOnline#543]
My suggestion is that for a week or so, we completely switch out the words file for an event specific words file that will use event related names. That, or incorporate a secondary words file for event days that will often spawn event related items, NPCs, and MOBs.

Essentially, exclusive play material only available during the events.

**Comment by tripplehelix** [comment]
Could you please post this suggestion to discord for voting in the suggestions channel.
