### ISSUE TITLE
World Lore - Lore Dungeons

### ISSUE THREAD

**Issue by darkrevelations** [DexterHuang/CyberCodeOnline#547]
> "There will be fun if for the birthday of the game every year we produce a part of a sort of main lore who explain everything of this world."

This was sent in the discord as a suggestion in the Dungeons channel.

Rather than a dedicated event, perhaps a storyline section could be added that gives an opportunity to learn about the world.

Set dungeons with many lore areas in set places, specific lore items, lore bosses, and more could be added to this concept. It could become a dedicated story mode that could also grow over time.

**Comment by tripplehelix** [comment]
Could you please post this suggestion to discord for voting in the suggestions channel.
