### ISSUE TITLE
Latency Issues Everywhere

### ISSUE THREAD

**Issue by darkrevelations** [DexterHuang/CyberCodeOnline#548]
Device: OnePlus 7t
Android Version: 11
Network Speeds: 256mb/s down 15 mb/s up.
Location (in case it is latency connecting to the server): Central United States
Issues:

Notable delays during battle. Attacks against enemy happen quickly. Returned attacks take several seconds.

Travel is delayed at times.

Dungeon battles ending with item drops will reopen or not close after I have taken the items.

Scrapping items takes a few seconds.

Movement in dungeons is sometimes laggy.

Lootboxes in dungeons take several seconds to load.

Chat messages can take several seconds to appear.

Selling items has a several second delay.

Pretty much delays everywhere.

**Comment by tripplehelix** [comment]
@DexterHuang Is there anything we can do about this. It's been standard since I started playing.

**Comment by DexterHuang** [comment]
I am working on the movement issue, that's the update that broke everything today, I'm deploying the update again right now 🙂

**Comment by DexterHuang** [comment]
movement is fast now
