### ISSUE TITLE
Infinite Dungeons - Survival

### ISSUE THREAD

**Issue by darkrevelations** [DexterHuang/CyberCodeOnline#554]
Multi-level dungeons with stairs that lead deeper. As you progress, enemies would grow strong. They'd start at level one and increase over time until they reach max player level.

There is no completion criteria. Rather, the dungeon will provide bonus EXP for each floor completed and will give an EXP boost for defeating enemies on each level.

After enemies reach max level, the dungeon will extend infinitely, the enemies remaining the same level but acquiring higher boosts to damage, defense, and resistances such as stun and crit avoidance.

**Comment by tripplehelix** [comment]
Could you please post this on Discord suggestions? Thanks, you can link to this suggestion if you want.
