### ISSUE TITLE
Suggestions after a few hours of playing

### ISSUE THREAD

**Issue by VxDman** [DexterHuang/CyberCodeOnline#564]
Not really an issue, more a set of suggestions:

On mobile:
- The interface in general should be less laggy, and sometimes I need to click twice on a button for some reason. It feels like every click makes a network call of some sort. Going between different menus / locations should be much smoother. I am abroad right now and will check from home (east US) to see if that improves.
- There should be a way to check active dungeons for a given level / challenge directly from the map interface. The tutorial led me in error because it shows that floating button right on the dungeon button, but I think it would actually be a great idea.
- During combat in dungeon, action of co-op players in the same combat as you don't show in the main text window but as notifications, which is weird. It would be better to have everything streamlined.
- A much larger item would be combat in general and especially in co-op. Maybe I'm not far enough into the game, but I'd love to see a bit more variety in the gameplay. Maybe skills, maybe some sorts of specialized weapons, maybe classes (I'm partial to the holy trinity, but this is not necessary). The time to kill would have to be increased for it to make sense.
- Farming in Adventure should have some kind of semi-auto mode, just to save mindless clicks on the primary attack. Of course I don't want it to be yet another auto farm "mmorpg", but there has to be a middle ground.

I tried the web-based client, and I love some of the ideas, but would love a toggle switch from the "IDE" interface to something more akin to the mobile interface. I don't mind code, but I find the mobile interface to be more enjoyable for a game, especially in combat.

Still figuring out the game so I'll update / use ingame mail to add onto this.

Great job so far though!

Just my 2 cents.

**Comment by tripplehelix** [comment]
All suggestions need adding to the discord under the suggestions channel use '-suggest' to post there. Some of what you suggested is already approved for adding to the game.

@DexterHuang I'm going to tag you just so you see this <3
