### ISSUE TITLE
Bug? 

### ISSUE THREAD

**Issue by Kyunbix** [DexterHuang/CyberCodeOnline#568]
Pmhhc0R1cmF0aW9uKCkmJnNldFRpbWVvdXQoZnVuY3Rpb24oKXtDLmEuc3RhcnROb3RpZmljYXRpb25VSSgpfSwxZTMpfSxbbi5nZXRTdGF0dXNOYW1lKCldKTt2YXIgaT1OLmlzUmVhZHkoKSx1PW4uZ2V0TG9jYXRpb24oKS5nZXRMaW5rcygpLmZpbmQoZnVuY3Rpb24oZSl7cmV0dXJuIGUuaXNCYWNrfSkscz11JiYhbi5pc0luRHVuZ2VvbigpLG09VnIoYy51c2VTdGF0ZSghMSksMiksZj1tWzBdLGQ9bVsxXTtyZXR1cm4gYy5jcmVhdGVFbGVtZW50KCIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IG4uZ2V0TG9jYXRpb24oLi4uKS5nZXRMaW5rcyBpcyBub3QgYSBmdW5jdGlvbgpUeXBlRXJyb3I6IG4uZ2V0TG9jYXRpb24oLi4uKS5nZXRMaW5rcyBpcyBub3QgYSBmdW5jdGlvbgogICAgYXQgaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuOGY1NDIwOTUuY2h1bmsuanM6MToxMDI0NjcKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35BcHBMYXlvdXQuZDBlOWU4YzIuY2h1bmsuanM6MToxNTkwCiAgICBhdCBhZSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5kMGU5ZThjMi5jaHVuay5qczoxOjE1OTA1KQogICAgYXQgZS50cmFjayAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5kMGU5ZThjMi5jaHVuay5qczoxOjI2NTg3KQogICAgYXQgaCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5kMGU5ZThjMi5jaHVuay5qczoxOjE1NjcpCiAgICBhdCBHciAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuOGY1NDIwOTUuY2h1bmsuanM6MToxMDIyMTMpCiAgICBhdCBYbyAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmFlZWFkOGEyLmNodW5rLmpzOjE6MTEyOTc1KQogICAgYXQgYmwgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hZWVhZDhhMi5jaHVuay5qczoxOjE1OTQ5MikKICAgIGF0IGJ1IChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uYWVlYWQ4YTIuY2h1bmsuanM6MToxNTIxMjkpCiAgICBhdCB5dSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmFlZWFkOGEyLmNodW5rLmpzOjE6MTUyMDU0KQ==

**Comment by tripplehelix** [comment]
This should have now been fixed. Feel free to reopen this issue if it has not.

**Comment by Kyunbix** [comment]
Yeah It's fixed. Thanks a lot!

pon., 26 kwi 2021, 14:55 użytkownik tripplehelix ***@***.***>
napisał:
