### ISSUE TITLE
Error when trying to launch the game

### ISSUE THREAD

**Issue by Karkeros** [DexterHuang/CyberCodeOnline#569]
Got this error code:
(good luck) 

Pmhhc0R1cmF0aW9uKCkmJnNldFRpbWVvdXQoZnVuY3Rpb24oKXtDLmEuc3RhcnROb3RpZmljYXRpb25VSSgpfSwxZTMpfSxbbi5nZXRTdGF0dXNOYW1lKCldKTt2YXIgaT1OLmlzUmVhZHkoKSx1PW4uZ2V0TG9jYXRpb24oKS5nZXRMaW5rcygpLmZpbmQoZnVuY3Rpb24oZSl7cmV0dXJuIGUuaXNCYWNrfSkscz11JiYhbi5pc0luRHVuZ2VvbigpLG09VnIoYy51c2VTdGF0ZSghMSksMiksZj1tWzBdLGQ9bVsxXTtyZXR1cm4gYy5jcmVhdGVFbGVtZW50KCIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IG4uZ2V0TG9jYXRpb24oLi4uKS5nZXRMaW5rcyBpcyBub3QgYSBmdW5jdGlvbgpUeXBlRXJyb3I6IG4uZ2V0TG9jYXRpb24oLi4uKS5nZXRMaW5rcyBpcyBub3QgYSBmdW5jdGlvbgogICAgYXQgaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuOGY1NDIwOTUuY2h1bmsuanM6MToxMDI0NjcKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35BcHBMYXlvdXQuZDBlOWU4YzIuY2h1bmsuanM6MToxNTkwCiAgICBhdCBhZSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5kMGU5ZThjMi5jaHVuay5qczoxOjE1OTA1KQogICAgYXQgZS50cmFjayAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5kMGU5ZThjMi5jaHVuay5qczoxOjI2NTg3KQogICAgYXQgaCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5kMGU5ZThjMi5jaHVuay5qczoxOjE1NjcpCiAgICBhdCBHciAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuOGY1NDIwOTUuY2h1bmsuanM6MToxMDIyMTMpCiAgICBhdCBYbyAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmFlZWFkOGEyLmNodW5rLmpzOjE6MTEyOTc1KQogICAgYXQgYmwgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hZWVhZDhhMi5jaHVuay5qczoxOjE1OTQ5MikKICAgIGF0IGJ1IChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uYWVlYWQ4YTIuY2h1bmsuanM6MToxNTIxMjkpCiAgICBhdCB5dSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmFlZWFkOGEyLmNodW5rLmpzOjE6MTUyMDU0KQ==

**Comment by pamdemonia** [comment]
I got one too... 

PnVsbCxjLmNyZWF0ZUVsZW1lbnQoYS5rLG51bGwsYy5jcmVhdGVFbGVtZW50KGFyLG51bGwpKSxjLmNyZWF0ZUVsZW1lbnQoYS5mLG51bGwsYy5jcmVhdGVFbGVtZW50KGEucSx7ZGlzYWJsZWQ6dC5nZXRTdGF0dXNOYW1lKCkuaW5kZXhPZigiQ09NQkFUIik+PTAsc2xvdDoiZml4ZWQiLGNvbG9yOiJwcmltYXJ5IixvbklvblJlZnJlc2g6ZnVuY3Rpb24oKXt2YXIgZSx0PShlPXJlZ2VuZXJhdG9yUnVudGltZS5tYXJrKGZ1bmN0aW9uIGUodCl7dmFyIG4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IENhbm5vdCByZWFkIHByb3BlcnR5ICdpbmRleE9mJyBvZiB1bmRlZmluZWQKVHlwZUVycm9yOiBDYW5ub3QgcmVhZCBwcm9wZXJ0eSAnaW5kZXhPZicgb2YgdW5kZWZpbmVkCiAgICBhdCBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL0FwcExheW91dE1vYmlsZS44ZjU0MjA5NS5jaHVuay5qczoxOjE0MjEyMwogICAgYXQgaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5kMGU5ZThjMi5jaHVuay5qczoxOjE1OTAKICAgIGF0IGFlIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+QXBwTGF5b3V0LmQwZTllOGMyLmNodW5rLmpzOjE6MTU5MDUpCiAgICBhdCBlLnRyYWNrIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+QXBwTGF5b3V0LmQwZTllOGMyLmNodW5rLmpzOjE6MjY1ODcpCiAgICBhdCBoIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+QXBwTGF5b3V0LmQwZTllOGMyLmNodW5rLmpzOjE6MTU2NykKICAgIGF0IGNvIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL0FwcExheW91dE1vYmlsZS44ZjU0MjA5NS5jaHVuay5qczoxOjE0MTg1MikKICAgIGF0IFhvIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uYWVlYWQ4YTIuY2h1bmsuanM6MToxMTI5NzUpCiAgICBhdCBibCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmFlZWFkOGEyLmNodW5rLmpzOjE6MTU5NDkyKQogICAgYXQgYnUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hZWVhZDhhMi5jaHVuay5qczoxOjE1MjEyOSkKICAgIGF0IHl1IChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uYWVlYWQ4YTIuY2h1bmsuanM6MToxNTIwNTQp

**Comment by tripplehelix** [comment]
This should have now been fixed. Feel free to reopen this issue if it has not.
