### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Luce3f4** [DexterHuang/CyberCodeOnline#570]
PnVsbCxjLmNyZWF0ZUVsZW1lbnQoYS5rLG51bGwsYy5jcmVhdGVFbGVtZW50KGFyLG51bGwpKSxjLmNyZWF0ZUVsZW1lbnQoYS5mLG51bGwsYy5jcmVhdGVFbGVtZW50KGEucSx7ZGlzYWJsZWQ6dC5nZXRTdGF0dXNOYW1lKCkuaW5kZXhPZigiQ09NQkFUIik+PTAsc2xvdDoiZml4ZWQiLGNvbG9yOiJwcmltYXJ5IixvbklvblJlZnJlc2g6ZnVuY3Rpb24oKXt2YXIgZSx0PShlPXJlZ2VuZXJhdG9yUnVudGltZS5tYXJ
Heres the error code

**Comment by tripplehelix** [comment]
This should have now been fixed. Feel free to reopen this issue if it has not.
