### ISSUE TITLE
Error code on opening app

### ISSUE THREAD

**Issue by jaythenerdkid** [DexterHuang/CyberCodeOnline#571]
Hi, just got this error code when opening the app on my phone (Pixel 4, Android 11). It's my first time running into this error. I clicked a push notification to check on my AFK progress and got this:

PnVsbCxjLmNyZWF0ZUVsZW1lbnQoYS5rLG51bGwsYy5jcmVhdGVFbGVtZW50KGFyLG51bGwpKSxjLmNyZWF0ZUVsZW1lbnQoYS5mLG51bGwsYy5jcmVhdGVFbGVtZW50KGEucSx7ZGlzYWJsZWQ6dC5nZXRTdGF0dXNOYW1lKCkuaW5kZXhPZigiQ09NQkFUIik+PTAsc2xvdDoiZml4ZWQiLGNvbG9yOiJwcmltYXJ5IixvbklvblJlZnJlc2g6ZnVuY3Rpb24oKXt2YXIgZSx0PShlPXJlZ2VuZXJhdG9yUnVudGltZS5tYXJrKGZ1bmN0aW9uIGUodCl7dmFyIG4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IENhbm5vdCByZWFkIHByb3BlcnR5ICdpbmRleE9mJyBvZiB1bmRlZmluZWQKVHlwZUVycm9yOiBDYW5ub3QgcmVhZCBwcm9wZXJ0eSAnaW5kZXhPZicgb2YgdW5kZWZpbmVkCiAgICBhdCBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL0FwcExheW91dE1vYmlsZS44ZjU0MjA5NS5jaHVuay5qczoxOjE0MjEyMwogICAgYXQgaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5kMGU5ZThjMi5jaHVuay5qczoxOjE1OTAKICAgIGF0IGFlIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+QXBwTGF5b3V0LmQwZTllOGMyLmNodW5rLmpzOjE6MTU5MDUpCiAgICBhdCBlLnRyYWNrIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+QXBwTGF5b3V0LmQwZTllOGMyLmNodW5rLmpzOjE6MjY1ODcpCiAgICBhdCBoIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+QXBwTGF5b3V0LmQwZTllOGMyLmNodW5rLmpzOjE6MTU2NykKICAgIGF0IGNvIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL0FwcExheW91dE1vYmlsZS44ZjU0MjA5NS5jaHVuay5qczoxOjE0MTg1MikKICAgIGF0IFhvIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uYWVlYWQ4YTIuY2h1bmsuanM6MToxMTI5NzUpCiAgICBhdCBibCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmFlZWFkOGEyLmNodW5rLmpzOjE6MTU5NDkyKQogICAgYXQgYnUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hZWVhZDhhMi5jaHVuay5qczoxOjE1MjEyOSkKICAgIGF0IHl1IChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uYWVlYWQ4YTIuY2h1bmsuanM6MToxNTIwNTQp

**Comment by ExanDeS** [comment]
got the same problem, maybe servers are down or idk

**Comment by jaythenerdkid** [comment]
> got the same problem, maybe servers are down or idk

yeah, looks like a few people have posted the same problem one after another, so must be a server-wide thing.

**Comment by Seo-na** [comment]
got the same problem, maybe servers are down or idk.
I'll be waiting for you.

**Comment by tripplehelix** [comment]
This should have now been fixed. Feel free to reopen this issue if it has not.
