### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by RaiTheBirds** [DexterHuang/CyberCodeOnline#590]
PmlwbWVudHMoKSk7dHJ5e2ZvcihyLnMoKTshKHQ9ci5uKCkpLmRvbmU7KXt2YXIgaT10LnZhbHVlO24rPShpLmdldE1heER1cmFiaWxpdHkoKS1pLmdldEN1cnJlbnREdXJhYmlsaXR5KCkpKmkubGV2ZWwqaS5nZXRUaWVyKCkuZ2V0UHJpY2VGYWN0b3IoKX19Y2F0Y2goYSl7ci5lKGEpfWZpbmFsbHl7ci5mKCl9cmV0dXJuIG49TWF0aC5jZWlsKG4vMTAwKX19LHtrZXk6ImdldERlc2NyaXB0aW9uIix2YWx1ZTpmdW5jdGlvbigpe3JldHVybiB0aGlzLm8KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IENhbm5vdCByZWFkIHByb3BlcnR5ICdnZXRQcmljZUZhY3Rvcicgb2YgdW5kZWZpbmVkClR5cGVFcnJvcjogQ2Fubm90IHJlYWQgcHJvcGVydHkgJ2dldFByaWNlRmFjdG9yJyBvZiB1bmRlZmluZWQKICAgIGF0IG8udmFsdWUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0Ljk3NzU3ZjJiLmNodW5rLmpzOjE6MjQ3MzQ0KQogICAgYXQgaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuMGJmMjZhOTEuY2h1bmsuanM6MToxNTg5OTkKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35BcHBMYXlvdXQuM2FjMjVlM2EuY2h1bmsuanM6MToxNTkwCiAgICBhdCBhZSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC4zYWMyNWUzYS5jaHVuay5qczoxOjE1OTA1KQogICAgYXQgZS50cmFjayAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC4zYWMyNWUzYS5jaHVuay5qczoxOjI2NTg3KQogICAgYXQgaCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC4zYWMyNWUzYS5jaHVuay5qczoxOjE1NjcpCiAgICBhdCBHbyAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuMGJmMjZhOTEuY2h1bmsuanM6MToxNTg0ODkpCiAgICBhdCBYbyAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmJiOWUzMGNjLmNodW5rLmpzOjE6MTEyOTc1KQogICAgYXQgYmwgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5iYjllMzBjYy5jaHVuay5qczoxOjE1OTQ5MikKICAgIGF0IGJ1IChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uYmI5ZTMwY2MuY2h1bmsuanM6MToxNTIxMjkp

**Comment by DexterHuang** [comment]
fixed
