### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Eksoss** [DexterHuang/CyberCodeOnline#597]
I leave many tabs open/saved, it happened after accessing the game tab.

Pi5jcmVhdGVFbGVtZW50KCJkaXYiLG51bGwpfSx0PT09TS5hLkRFU0tUT1AmJiFyJiZmdW5jdGlvbigpe3ZhciBlPWMubGF6eShmdW5jdGlvbigpe3JldHVybiBQcm9taXNlLmFsbChbbi5lKDApLG4uZSgxKSxuLmUoMiksbi5lKDQpXSkudGhlbihuLmJpbmQobnVsbCw1OTYpKX0pO3JldHVybiBjLmNyZWF0ZUVsZW1lbnQoZSxudWxsKX0oKSkpKX19LDYxOmZ1bmN0aW9uKGUsdCxuKXsidXNlIHN0cmljdCI7bi5kKHQsImEiLGZ1bmN0aW9uKCl7cmV0dXIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpDaHVua0xvYWRFcnJvcjogTG9hZGluZyBjaHVuayA0IGZhaWxlZC4KKG1pc3Npbmc6IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0RGVza3RvcC5lNGU4YjJhNy5jaHVuay5qcykKQ2h1bmtMb2FkRXJyb3I6IExvYWRpbmcgY2h1bmsgNCBmYWlsZWQuCihtaXNzaW5nOiBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL0FwcExheW91dERlc2t0b3AuZTRlOGIyYTcuY2h1bmsuanMpCiAgICBhdCBGdW5jdGlvbi5mLmUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS86MTo0MjA3KQogICAgYXQgaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXQuYjlhZTdjMmEuY2h1bmsuanM6MTo1NDI3MTQKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hN2FjMWFkNi5jaHVuay5qczoxOjE2MDEyNgogICAgYXQgYmwgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hN2FjMWFkNi5jaHVuay5qczoxOjE2MDI3MSkKICAgIGF0IGJ1IChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uYTdhYzFhZDYuY2h1bmsuanM6MToxNTIxMjkpCiAgICBhdCB5dSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmE3YWMxYWQ2LmNodW5rLmpzOjE6MTUyMDU0KQogICAgYXQgY3UgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hN2FjMWFkNi5jaHVuay5qczoxOjE0OTA1NikKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hN2FjMWFkNi5jaHVuay5qczoxOjEwMDI0NgogICAgYXQgdC51bnN0YWJsZV9ydW5XaXRoUHJpb3JpdHkgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hN2FjMWFkNi5jaHVuay5qczoxOjE3NTkxNSkKICAgIGF0IHFpIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uYTdhYzFhZDYuY2h1bmsuanM6MTo5OTk1Nik=

**Comment by DexterHuang** [comment]
Hey thanks for the report, this issue should be gone if you restart the app
😊
