### ISSUE TITLE
Dungeon List Shows Wrong number of enemies

### ISSUE THREAD

**Issue by Kaliora** [DexterHuang/CyberCodeOnline#599]
All dungeons in the dungeon list now show 0 enemies remaining, even if that's untrue.

**Comment by Misaki290** [comment]
> All dungeons in the dungeon list now show 0 enemies remaining, even if that's untrue.

Should have posted a screenshot.

**Comment by tripplehelix** [comment]
@DexterHuang is this counter going to return?

**Comment by DexterHuang** [comment]
It's not coming back 😁

**Comment by tripplehelix** [comment]
> It's not coming back 😁

Wow.... evil dex
