### ISSUE TITLE
Prompt on autoScrap before destroying

### ISSUE THREAD

**Issue by xbenjii** [DexterHuang/CyberCodeOnline#6]
Whenn clicking autoScrap, there should be a prompt showing what it is going to destroy (maybe with a checkbox to ignore in future)

**Comment by xbenjii** [comment]
You could maybe add tiers of autoScrap too (destroy trash only, destroy common only)

**Comment by hildjj** [comment]
> You could maybe add tiers of autoScrap too (destroy trash only, destroy common only)

that's an opportunity to add user-specified parameters.  UI could be the same as selecting from an enum list in a .ts project.

**Comment by tripplehelix** [comment]
This is already on Discord
