### ISSUE TITLE
Fix "crutial" 

### ISSUE THREAD

**Issue by felipe1982** [DexterHuang/CyberCodeOnline#603]
Crutial should be spelled crucial

**Comment by tripplehelix** [comment]
We will need more information. Where is this spelt wrong?

**Comment by felipe1982** [comment]
I am sorry, I do not remember. I think it was one of the Tips.

**Comment by nopeholmes** [comment]
Fixed in PR #605

**Comment by nopeholmes** [comment]
Already merged by @DexterHuang , you can close this issu @felipe1982
