### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by OnwardSix7** [DexterHuang/CyberCodeOnline#606]
I was in the studying printing and went to profile and it crashed

PiBsKGUpe0NsKG8scixhLGwsaSwibmV4dCIsZSl9ZnVuY3Rpb24gaShlKXtDbChvLHIsYSxsLGksInRocm93IixlKX1sKHZvaWQgMCl9KX19dmFyIE9sPWMubGF6eShmdW5jdGlvbigpe3JldHVybiBQcm9taXNlLmFsbChbbi5lKDEwKSxuLmUoMSldKS50aGVuKG4uYmluZChudWxsLDU5NSkpfSksUGw9Yy5tZW1vKGZ1bmN0aW9uKGUpe3ZhciB0LG4scixhLG8sbD1lLmlzTWUsaT1lLnBsYXllcix1PWUuZG9uYXRpb25UeXBlLHM9ZS5jb2xvcjtyZXR1cm4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpDaHVua0xvYWRFcnJvcjogTG9hZGluZyBjaHVuayAxMCBmYWlsZWQuCihtaXNzaW5nOiBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+TW9iaWxlUGxheWVyTGV2ZWxEZXRhaWxzLmM2NWY4MjY0LmNodW5rLmpzKQpDaHVua0xvYWRFcnJvcjogTG9hZGluZyBjaHVuayAxMCBmYWlsZWQuCihtaXNzaW5nOiBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+TW9iaWxlUGxheWVyTGV2ZWxEZXRhaWxzLmM2NWY4MjY0LmNodW5rLmpzKQogICAgYXQgRnVuY3Rpb24uZi5lIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vOjY1MTg6NDE3MCkKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0TW9iaWxlLmU0MjI4ZjliLmNodW5rLmpzOjE6MTc0ODA1CiAgICBhdCBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZDBmYWZiZGUuY2h1bmsuanM6MToxNjAxNDEKICAgIGF0IGJsIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZDBmYWZiZGUuY2h1bmsuanM6MToxNjAyODYpCiAgICBhdCBidSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmQwZmFmYmRlLmNodW5rLmpzOjE6MTUyMTQ0KQogICAgYXQgeXUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5kMGZhZmJkZS5jaHVuay5qczoxOjE1MjA2OSkKICAgIGF0IGN1IChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZDBmYWZiZGUuY2h1bmsuanM6MToxNDkwNzEpCiAgICBhdCBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZDBmYWZiZGUuY2h1bmsuanM6MToxMDAyNjEKICAgIGF0IHQudW5zdGFibGVfcnVuV2l0aFByaW9yaXR5IChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uZDBmYWZiZGUuY2h1bmsuanM6MToxNzU5MzApCiAgICBhdCBxaSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmQwZmFmYmRlLmNodW5rLmpzOjE6OTk5NzEp

**Comment by DexterHuang** [comment]
hello this issue should be resolve by restarting the app :)
