### ISSUE TITLE
an error :(

### ISSUE THREAD

**Issue by Murfex** [DexterHuang/CyberCodeOnline#622]
What happened:

I was just trying to check my email

Error code:

PnJlYXRlRWxlbWVudChhLnUse21vZGU6Im1kIixvbklvbkNoYW5nZTpmdW5jdGlvbihlKXtyZXR1cm4gcihOdC5maW5kSW5kZXgoZnVuY3Rpb24odCl7cmV0dXJuIHQuaWQ9PT1lLmRldGFpbC52YWx1ZX0pKX0sdmFsdWU6by5pZH0sTnQubWFwKGZ1bmN0aW9uKGUpe3ZhciB0PTA7cmV0dXJuIm1haWwiPT09ZS5pZCYmKHQ9Vi5hLmdldEFsbFVucmVhZENvdW50KCkpLCJub3RpLiI9PT1lLmlkJiYodD1sLmdldE5vdGlmaWNhdGlvbnMoKS5sZW5ndGgpLCIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IENhbm5vdCByZWFkIHByb3BlcnR5ICdpZCcgb2YgdW5kZWZpbmVkClR5cGVFcnJvcjogQ2Fubm90IHJlYWQgcHJvcGVydHkgJ2lkJyBvZiB1bmRlZmluZWQKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0TW9iaWxlLjI0NjkzYzE1LmNodW5rLmpzOjE6NTEzMTIKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35BcHBMYXlvdXQuZjVhYmY3MmIuY2h1bmsuanM6MToxNTkwCiAgICBhdCBhZSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5mNWFiZjcyYi5jaHVuay5qczoxOjE1OTA0KQogICAgYXQgZS50cmFjayAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5mNWFiZjcyYi5jaHVuay5qczoxOjI2NTg2KQogICAgYXQgaCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5mNWFiZjcyYi5jaHVuay5qczoxOjE1NjcpCiAgICBhdCBBdCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuMjQ2OTNjMTUuY2h1bmsuanM6MTo1MDk2NSkKICAgIGF0IFhpIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMGVjMWYzMDIuY2h1bmsuanM6MToxMzk5ODApCiAgICBhdCBGYSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjBlYzFmMzAyLmNodW5rLmpzOjE6MTQ4ODY4KQogICAgYXQgYnUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi4wZWMxZjMwMi5jaHVuay5qczoxOjE4NzcyOSkKICAgIGF0IGJsIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uMGVjMWYzMDIuY2h1bmsuanM6MToxNzkxMzQp

**Comment by DexterHuang** [comment]
fix being deployed now
