### ISSUE TITLE
combat progress lost on refresh - unable to heal

### ISSUE THREAD

**Issue by michaeldick** [DexterHuang/CyberCodeOnline#63]
The combat vs enemy is not working for me right now..
- I start a combat and deal / receive some damage. On page refresh (F5) I'm out of combat.

This happened after I had trouble using painAway
- fight with enemy
- try to use painAway
- health stays low, inventory shows same amount of painAway
- refesh page - out of combat and the "used" painAways are gone

I lost 5 painAway this way..

**Comment by DexterHuang** [comment]
hi, are you in nearby enemy combat or dungeon?

**Comment by michaeldick** [comment]
nearby enemy combat

**Comment by DexterHuang** [comment]
yes, refresh and out of combat is expected,
I am fixing painAway  now, you are not suppose to be able to use it during nearby combat, only in dungeon can use

**Comment by DexterHuang** [comment]
issue fixed
