### ISSUE TITLE
Fix errors in code

### ISSUE THREAD

**Issue by epixinvites** [DexterHuang/CyberCodeOnline#632]
![image](https://user-images.githubusercontent.com/54717060/116714109-fd886700-aa07-11eb-9df7-0da2f1882c68.png)
It should be `You picked up a Hash Processor` same goes with `You picked up an AI Core`. The other thing is `You received 3 Energy Cells`

You see, the a/an and the 's' and no 's' makes a big difference. I know it needs a bit of time to write an if else statement for these gramatical errors but it's worth the time trust me.

![image](https://user-images.githubusercontent.com/54717060/116836602-b8c42200-abf9-11eb-8c17-bba2b558ae22.png)
Inventory spelled wrong

**Comment by epixinvites** [comment]
![image](https://user-images.githubusercontent.com/54717060/116769442-b5e8f600-aa6e-11eb-8db9-78c51986aa2e.png)
Something like this.

**Comment by epixinvites** [comment]
![image](https://user-images.githubusercontent.com/54717060/116835506-62ed7b00-abf5-11eb-94ba-6fa1fffca5d8.png)

**Comment by epixinvites** [comment]
![image](https://user-images.githubusercontent.com/54717060/116836602-b8c42200-abf9-11eb-8c17-bba2b558ae22.png)
Inventory spelled wrong

**Comment by epixinvites** [comment]
Market Interface looks messy
![image](https://user-images.githubusercontent.com/54717060/116838036-7dc4ed00-abff-11eb-9f33-25ffa1ef2d44.png)

**Comment by epixinvites** [comment]
And the worst thing is this:
![image](https://user-images.githubusercontent.com/54717060/116947133-8a544e80-acae-11eb-8b03-4b876f31df14.png)
and
![image](https://user-images.githubusercontent.com/54717060/116947162-993b0100-acae-11eb-90d5-589ce5474baa.png)

**Comment by tripplehelix** [comment]
This can be corrected by us in the en.json in the new translations. Once the whole game is added we will be able to make these corrections. Someone has today, gone through the file and made a bunch of changes already.
