### ISSUE TITLE
Coherent name for *WeaponCache

### ISSUE THREAD

**Issue by cu39** [DexterHuang/CyberCodeOnline#64]
The names of `*WeaponCache` are not coherent as follows:

|`Inventory.ts`|`Molecular3dPrinter.ts`|
|----|----|
|`*SpecialWeaponCache`|`*SecondaryWeaponCache`|
|`*DestructiveWeaponCache`|`*TertiaryWeaponCache`|

It would be better to grep all sources because I might see Secondary-/Tertiary- naming in other places than 3dprinter (but I could not remember where I did.)

**Comment by DexterHuang** [comment]
fixed in pre-release :) thanks!
