### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by BegForLove** [DexterHuang/CyberCodeOnline#646]
PnJpbmciIT09dHlwZW9mIGUpdGhyb3cgRXJyb3IoYSgyODQpKTtpZighbi5fb3duZXIpdGhyb3cgRXJyb3IoYSgyOTAsZSkpfXJldHVybiBlfWZ1bmN0aW9uIGtpKGUsdCl7aWYoInRleHRhcmVhIiE9PWUudHlwZSl0aHJvdyBFcnJvcihhKDMxLCJbb2JqZWN0IE9iamVjdF0iPT09T2JqZWN0LnByb3RvdHlwZS50b1N0cmluZy5jYWxsKHQpPyJvYmplY3Qgd2l0aCBrZXlzIHsiK09iamVjdC5rZXlzKHQpLmpvaW4oIiwgIikrIn0iOnQsIiIpKX1mdW5jdGkKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpFcnJvcjogTWluaWZpZWQgUmVhY3QgZXJyb3IgIzMxOyB2aXNpdCBodHRwczovL3JlYWN0anMub3JnL2RvY3MvZXJyb3ItZGVjb2Rlci5odG1sP2ludmFyaWFudD0zMSZhcmdzW109RXJyb3IlM0ElMjBOZXR3b3JrJTIwRXJyb3ImYXJnc1tdPSBmb3IgdGhlIGZ1bGwgbWVzc2FnZSBvciB1c2UgdGhlIG5vbi1taW5pZmllZCBkZXYgZW52aXJvbm1lbnQgZm9yIGZ1bGwgZXJyb3JzIGFuZCBhZGRpdGlvbmFsIGhlbHBmdWwgd2FybmluZ3MuCkVycm9yOiBNaW5pZmllZCBSZWFjdCBlcnJvciAjMzE7IHZpc2l0IGh0dHBzOi8vcmVhY3Rqcy5vcmcvZG9jcy9lcnJvci1kZWNvZGVyLmh0bWw

**Comment by DexterHuang** [comment]
Hi does the error go away if you restart the app?
