### ISSUE TITLE
Stuck in dungeon combat with system error

### ISSUE THREAD

**Issue by hhravn** [DexterHuang/CyberCodeOnline#68]
In a combat, but cannot attack, getting the error `[system]:  TypeError:  Cannot  read  property  'shortId'  of  undefined` every time i try.

<img width="867" alt="Screenshot 2020-09-08 at 21 37 15" src="https://user-images.githubusercontent.com/516402/92520296-ab49ca00-f21b-11ea-8263-11a86c9d302f.png">

**Comment by DexterHuang** [comment]
Hi is it in dungeon or outside?

**Comment by hhravn** [comment]
Pretty sure it was inside a dungeon, but i'm not sure, sorry.

**Comment by DexterHuang** [comment]
i didnt see it last night lol it was 4am haha, are you able to leave the dungeon by escaping?

**Comment by hhravn** [comment]
@DexterHuang I didn't manage to escape, but managed to die (and leave the dungeon) after multiple attempts to escape. I'm not sure if it was the last enemy..

**Comment by DexterHuang** [comment]
If you manage to encounter this again, could you copy the network error, it contains stacks trace and stuff, cuz I am not sure what caused it :(

**Comment by DexterHuang** [comment]
this issue is fixed :)
