### ISSUE TITLE
AFK study not updating when finishing

### ISSUE THREAD

**Issue by xbenjii** [DexterHuang/CyberCodeOnline#7]
It is stuck on this screen, I can't click off it either (see toast on bottom right).
![image](https://user-images.githubusercontent.com/4347623/89885896-add8e580-dbc3-11ea-82f0-0f854053ea17.png)

**Comment by DexterHuang** [comment]
hmm is this reproduceable?

**Comment by xbenjii** [comment]
I couldn't reproduce, wasn't sure if I'd lost WS connection. Can close, might pop up later, might not :)
