### ISSUE TITLE
Pants is a helmet

### ISSUE THREAD

**Issue by MonstraG** [DexterHuang/CyberCodeOnline#713]
![Screenshot_2021-05-08-16-57-45-272_com cybercodeonline cybercode](https://user-images.githubusercontent.com/17963791/117538233-a8a7aa80-b01e-11eb-897d-4a29f7945ddc.jpg)

**Comment by tripplehelix** [comment]
This is not a bug. Do you not wear your pants on your head sometimes?

**Comment by Misaki290** [comment]
It's a feature. Not a bug.
