### ISSUE TITLE
Suggestion: multiple tabs opened side by side

### ISSUE THREAD

**Issue by asayuki** [DexterHuang/CyberCodeOnline#72]
It would be awesome if one could how multiple tabs opened side by side so you can, for example, browse your inventory at the same time you are browseing the weaponsmith or other.

Best regards. Awesome game!

**Comment by DexterHuang** [comment]
you already could do that :D

**Comment by asayuki** [comment]
I was thinking something more like this:
![cybercodeonline com](https://user-images.githubusercontent.com/999657/92932211-d6fbc880-f444-11ea-851d-d6004117b228.jpg)
:)
