### ISSUE TITLE
Suggestion: Audio notification when scavenge/work ends

### ISSUE THREAD

**Issue by yanko-ivanov** [DexterHuang/CyberCodeOnline#73]
Use case: I leave the game running in a pinned tab, and I usually leave it on scavenge or work for about two hours. Currently I've to check whether it has finished around the end. It would be useful if I had the option to get some kind of notification - audio, or a simple alert when the action was completed.

**Comment by DexterHuang** [comment]
yes, my initial plan is to use proper web notification for that(so you will receive even when you closed the tab), but the exactly how to do that effectively with firebase function still need to think about..

**Comment by DexterHuang** [comment]
now, the system will send a notification to your phone or browser 👍
