### ISSUE TITLE
Able to use city center services outside of city center

### ISSUE THREAD

**Issue by ceetee** [DexterHuang/CyberCodeOnline#74]
Steps to reproduce:
- Go to `SHANGRI_LA_CITY_CENTER`.
- Open a nearby service ~`Molecular3dPrinter.ts`~, `WeaponSmith.ts`, `TrinokyMart.ts`, or `Terminal.ts`.
- Do not close the service tab.
- Travel to one of the many stations `FLORI_STATION` for example.
- You are able to use the previously opened service tab from wherever you travel.

**Comment by DexterHuang** [comment]
Are you able to print item with molecular printer?

**Comment by ceetee** [comment]
I am not able to use the molecular printer, it gives an error message that there is no printer nearby.

I am able to use the weapon smith to sell and repair inventory.

**Comment by DexterHuang** [comment]
issue fixed in pre-release 👍
