### ISSUE TITLE
Typo in location name - can't find it in contribution/lang/en.json so can't fix it

### ISSUE THREAD

**Issue by Kusoneko** [DexterHuang/CyberCodeOnline#741]
Hello,

I noticed while playing on both mobile and desktop that the first zone in the 11-20 leveling area has the name "Snow Driven Kashi Resturant", this is a typo, the name should be "Snow Driven Kashi Rest**a**urant". I intended to make a PR to fix it, but apparently the actual name of things aren't in the localization files, and I can't find it anywhere, meaning it's presumably in the game's database instead or really anywhere else that isn't this repo.

Thanks,
Kusoneko.

**Comment by xaph** [comment]
Hi @DexterHuang 

I've added a PR for the fix of this:
https://github.com/DexterHuang/CyberCodeOnline/pull/855

**Comment by DexterHuang** [comment]
Thanks @xaph
