### ISSUE TITLE
Printing out lower level upgrade modules than current printing rank

### ISSUE THREAD

**Issue by cu39** [DexterHuang/CyberCodeOnline#75]
The opportunities to print upgrade modules (UM) will increase If lower level UMs are printable.

Given the printing rank is 20 and all equipments are level 19 or less, I do not intend to print UMs until most of 7 equipments become level 20 since UMs are printed out according to current rank and higher level UMs than equipments have nowhere to go. Actually levels of equipments are not flat most of the time.

**Comment by DexterHuang** [comment]
I am not very sure what are you trying to say here...

**Comment by cu39** [comment]
In short, sometimes I want to print out upgrade modules whose level is less than my current printing rank for my old (lower-level) equipments (I have to use them due to lack of resources etc.)

When I reach a new level I'm often in a dilemma to raise or keep my printing rank, while I STRONGLY want to raise it for the shiny-new-greater equipments ASAP.

It's difficult for me to explain the situation in detail but I hope this makes sense.

**Comment by cu39** [comment]
For example, both your level and PR are 8, so you go to the dungeon in Flori's main arsenal since its recommended level is 7+. You find there a new-rare-*level-7* weapon with 3 upgrade slots that is stronger than my old-common-level8 with single slot. Unfortunately you attached a level-8 (> 7) UM to it and don't have any UM <= 7, but you can't print the new ones since your PR is already 8.

**Comment by cu39** [comment]
If that type of dilemma (*should I raise PR or not?*) is an intended design (= the reason why you separate PR from player's level), there is no problem (a little irritating for me, though).

**Comment by DexterHuang** [comment]
Ahh i see what you mean, you have a low level item you want to keep but you cant make upgrades for it cuz ur PR too high
hmmm for now there is no way to choose the level of item you want to craft, but i dont see why we cant add that feature in,
but for now, you can buy it from market?

**Comment by cu39** [comment]
We'll be able to use our equipments to their full potential (all by ourselves) if the level is controllable on crafting (with slider UI etc.)

As you said the inconvenience about printing encourages us to go to the market to find UMs we can't print any more, though it's often difficult to find *just size* one for me at least (as OniOn, lvl 54) and probably for others now. More items on the market can resolve it indeed.

**Comment by BetaAndroid** [comment]
I think what he is saying is that if you have a 3d printer level like  20 you should be able to 3D print lower levels of equipment like lv19/18/17...etc
