### ISSUE TITLE
Randomize level of equipments in dungeon

### ISSUE THREAD

**Issue by cu39** [DexterHuang/CyberCodeOnline#76]
Players will be more motivated to enter dungeons if the level of treasures in dungeons is varied (in a limited range?)

Currently the level of equipment enemy drops or found in crate in dungeon is fixed to the recommended level of it. In this situation the benefit of entering dungeon varies according to player's level. Maximum when player = dungeon but decrease in other cases.

**Comment by DexterHuang** [comment]
good idea, implemented in pre-release
