### ISSUE TITLE
Suggestion: Crit chance and crit damage upgrade

### ISSUE THREAD

**Issue by taroj1205** [DexterHuang/CyberCodeOnline#77]
Add an upgrade that increases crit chance or crit damage.

**Comment by DexterHuang** [comment]
I like the idea of that, there was such upgrade but since been removed,
because the level 1 crit chance update is essentially the same as level 100 ones.

I couldn't think of a way to integrate it into upgrade modules in a more meaningful way

**Comment by DexterHuang** [comment]
Crit upgrade is added :)
