### ISSUE TITLE
Player Market Design

### ISSUE THREAD

**Issue by jeremy-j-ackso** [DexterHuang/CyberCodeOnline#79]
The new Player Market design is sooo much better.

One additional thing that would be helpful to have added is an array that shows all of the items you're currently trying to sell so that it's easier to see whether you've hit the 6 item max, what those 6 items are, and make it easier to pull them out of the market.

Bonus points for being able to change the asking price without removing the item from the market.

Extra bonus points for other players being able to place a bid that's below the asking price, that the seller then has the option to accept or decline, but auto-declines after maybe 12 or 24 hours.

**Comment by DexterHuang** [comment]
I have updated the UI to show your items in dedicated area :)
