### ISSUE TITLE
Dark Reader (chrome and ff extension) degrades UX in the left-hand ribbon

### ISSUE THREAD

**Issue by zamber** [DexterHuang/CyberCodeOnline#8]
Hey,
Dark Reader is an extension for auto-converting pages to a dark theme. It's open source and there should be some way to signal to it that a dark theme is natively implemented so it wouldn't apply it's filters (possibly with an empty prefers-color-scheme CSS media rule?).

https://github.com/darkreader/darkreader

on: https://prnt.sc/txuw1d
off: https://prnt.sc/txuw9y

**Comment by Gusted** [comment]
Hi!

https://github.com/darkreader/darkreader/pull/4106 resolves this issue!

Regards,
Gusted

**Comment by DexterHuang** [comment]
Cooooll👍👍👍👍

**Comment by tripplehelix** [comment]
Nice :)
