### ISSUE TITLE
Cyber Code

### ISSUE THREAD

**Issue by JOSEERICKMEDRANOCARRION** [DexterHuang/CyberCodeOnline#802]

**Comment by Kusoneko** [comment]
What is the actual issue here?

**Comment by epixinvites** [comment]
Just close it, probably a troll.

**Comment by Kusoneko** [comment]
Sure, that's all I have to do with my time, make troll issues. It's definitely not a real issue as shown by the screenshot attached.On May 21, 2021 9:27 p.m., The Wayfarrer ***@***.***> wrote:
Just close it, probably a troll.

**Comment by Kusoneko** [comment]
Sorry for the previous comment, I thought it was on another issue here, but yes this one should be closed, no content in the issue = no issue.

**Comment by Misaki290** [comment]
> _No description provided._

Don't troll post here. If you are bored do something else instead.

**Comment by Misaki290** [comment]
He is a troll, confirmed:
![IMG_20210522_232406](https://user-images.githubusercontent.com/79731146/119239949-59e92d00-bb55-11eb-9266-3d807ec13bb2.png)
![IMG_20210522_230238](https://user-images.githubusercontent.com/79731146/119239950-6077a480-bb55-11eb-888c-723adb7a2004.png)
![IMG_20210522_231154](https://user-images.githubusercontent.com/79731146/119239955-68cfdf80-bb55-11eb-9e1a-e5a56353acd7.png)
![IMG_20210522_231739](https://user-images.githubusercontent.com/79731146/119239961-6f5e5700-bb55-11eb-8e81-c7c7729f987a.png)
![IMG_20210522_231810](https://user-images.githubusercontent.com/79731146/119239969-75ecce80-bb55-11eb-8a62-b961e5e1e5db.png)

All he does is posting spammy issues on repositories.

**Comment by Misaki290** [comment]
I have reported the dude.
Next time, do something useful with your time.
![IMG_20210522_233134](https://user-images.githubusercontent.com/79731146/119240046-fc091500-bb55-11eb-8045-cce68068ebca.png)
