### ISSUE TITLE
[browser] It would be nice to be able to toggle in between the vs code version and the mobile version on the browser

### ISSUE THREAD

**Issue by LifeGiver2048** [DexterHuang/CyberCodeOnline#805]

**Comment by Skullbuns** [comment]
Try resizing the window to mobile dimensions and it should automatically switch! Unless you are talking about a separate button, in which case that could be useful.

**Comment by Kusoneko** [comment]
I'd assume they're asking for a separate button that switches the version without changing the window dimensions.

**Comment by DexterHuang** [comment]
You can post a suggestion on forum :D
