### ISSUE TITLE
[Mobile app] - New messages go under older ones (bug)

### ISSUE THREAD

**Issue by Misaki290** [DexterHuang/CyberCodeOnline#807]
On the mobile app and also in the browser mobile view, new messages doesn't dissapear but they go under older ones, so it's hard to see what messages you received. 
Also the notifications from the [SYSTEM].
I'll post some screenshots.

This is how it looks like:
![Screenshot_20210520-194644](https://user-images.githubusercontent.com/79731146/119019674-14d2c880-b9a6-11eb-8297-a23d1c505372.png)

This is how it should look like (I had to refresh the app to see these messages, but after a minute they go under old messages again):
![Screenshot_20210520-194700](https://user-images.githubusercontent.com/79731146/119019730-261bd500-b9a6-11eb-93df-cdccb9f7c05c.png)

I restarted/refreahed the app several times and the bug still doesn't go away.

**Comment by DexterHuang** [comment]
this should be fixed :)
