### ISSUE TITLE
Suggestion: Auction

### ISSUE THREAD

**Issue by taroj1205** [DexterHuang/CyberCodeOnline#81]
Add a feature that allows us create an auction.

**Comment by Joalex5134** [comment]
This would be a great idea for legendary items. You could make legendary not sellable in the market, they could only be auctioned.

An alternative would be to set a minimum and maximum value for items to be sold that scale with the items level and if you want to make more, you auction it.

**Comment by tripplehelix** [comment]
Added to discord #suggestions
