### ISSUE TITLE
Mobile - Crashes on Launch

### ISSUE THREAD

**Issue by EddieDover** [DexterHuang/CyberCodeOnline#827]
After an update, the game crashed. Now it crashes on launch with the following error. I'll try to reinstall. 

PjpmdW5jdGlvbihlKXtyZXR1cm4gZVtNYXRoLmZsb29yKHRoaXMuZ2V0UmFuZG9tKCkqZS5sZW5ndGgpXX19LHtrZXk6ImdldFdlaWdodGVkSXRlbSIsdmFsdWU6ZnVuY3Rpb24oZSl7cmV0dXJuIHRoaXMud2VpZ2h0ZWQoZSkuaXRlbX19LHtrZXk6IndlaWdodGVkIix2YWx1ZTpmdW5jdGlvbihlKXtpZighZXx8MD09PWUubGVuZ3RoKXJldHVybiBudWxsO3ZhciB0LG49ZS5zb3J0KGZ1bmN0aW9uKGUsdCl7dmFyIG4scjtyZXR1cm4obnVsbCE9PShuPWUKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IG51bGwgaXMgbm90IGFuIG9iamVjdCAoZXZhbHVhdGluZyAndGhpcy53ZWlnaHRlZChlKS5pdGVtJykKdmFsdWVAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXQuMWM1OWZiZGMuY2h1bmsuanM6MTo3NjEyNzgKdmFsdWVAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXQuMWM1OWZiZGMuY2h1bmsuanM6MTozOTgwNDUKdmFsdWVAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXREZXNrdG9wfkFwcExheW91dE1vYmlsZS5jZWRhYWU1NS5jaHVuay5qczoxOjEwNzQxOAp1c2VNZW1vQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hNjlhZGM1MS5jaHVuay5qczoxOjE0NTQ3MQpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL0FwcExheW91dE1vYmlsZS45N2FiZjM2Mi5jaHVuay5qczoxOjE5NDc4NQpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+QXBwTGF5b3V0LmUwZDM1ZmEyLmNodW5rLmpzOjE6MTU5MQphZUBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+QXBwTGF5b3V0LmUwZDM1ZmEyLmNodW5rLmpzOjE6MTU5MDkKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5lMGQzNWZhMi5jaHVuay5qczoxOjI2NTg5CmhAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5lMGQzNWZhMi5jaHVuay5qczoxOjE1NzIKWGlAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmE2OWFkYzUxLmNodW5rLmpzOjE6MTQwNTgxCmJ1QGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hNjlhZGM1MS5jaHVuay5qczoxOjE4NzA5OQpibEBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uYTY5YWRjNTEuY2h1bmsuanM6MToxNzk3MzYKeWxAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmE2OWFkYzUxLmNodW5rLmpzOjE6MTc5NjYxCmNsQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hNjlhZGM1MS5jaHVuay5qczoxOjE3NjY2MwpjbEBbbmF0aXZlIGNvZGVdCmh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hNjlhZGM1MS5jaHVuay5qczoxOjEyNzg1MgpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uYTY5YWRjNTEuY2h1bmsuanM6MToyMDM1MjEKWW9AaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmE2OWFkYzUxLmNodW5rLmpzOjE6MTI3Nzk5CkdvQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hNjlhZGM1MS5jaHVuay5qczoxOjEyNzczNAppbEBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uYTY5YWRjNTEuY2h1bmsuanM6MToxNzM0MzEKZW5xdWV1ZVNldFN0YXRlQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hNjlhZGM1MS5jaHVuay5qczoxOjEzMTU2MApodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uYTY5YWRjNTEuY2h1bmsuanM6MTo3NzU2OAp2YWx1ZUBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL2lvbmljLjg4YWJhMjFiLmNodW5rLmpzOjE6NTIwNjIKdmFsdWVAW25hdGl2ZSBjb2RlXQp2YWx1ZUBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL2lvbmljLjg4YWJhMjFiLmNodW5rLmpzOjE6NTQ2NjMKdmFsdWVAW25hdGl2ZSBjb2RlXQpyQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35BcHBMYXlvdXQuZTBkMzVmYTIuY2h1bmsuanM6MToxNjc2ODUKZm9yRWFjaEBbbmF0aXZlIGNvZGVdCm5vdGlmeUxpc3RlbmVyc0BodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+QXBwTGF5b3V0LmUwZDM1ZmEyLmNodW5rLmpzOjE6MTY3ODg1ClRAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5lMGQzNWZhMi5jaHVuay5qczoxOjE2ODkzMwpodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL3ZlbmRvcnN+QXBwTGF5b3V0LmUwZDM1ZmEyLmNodW5rLmpzOjE6MTY5OTMwCmNvbmZpcm1UcmFuc2l0aW9uVG9AaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5lMGQzNWZhMi5jaHVuay5qczoxOjE2NzYyMApwdXNoQGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35BcHBMYXlvdXQuZTBkMzVmYTIuY2h1bmsuanM6MToxNjk3MjkKdmFsdWVAaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXQuMWM1OWZiZGMuY2h1bmsuanM6MTo3MzYwNjMKaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuOTdhYmYzNjIuY2h1bmsuanM6MToyNzE3MzE=

**Comment by AuroraEndante** [comment]
Just got the same error on mobile. This is my copied code: 

PjpmdW5jdGlvbihlKXtyZXR1cm4gZVtNYXRoLmZsb29yKHRoaXMuZ2V0UmFuZG9tKCkqZS5sZW5ndGgpXX19LHtrZXk6ImdldFdlaWdodGVkSXRlbSIsdmFsdWU6ZnVuY3Rpb24oZSl7cmV0dXJuIHRoaXMud2VpZ2h0ZWQoZSkuaXRlbX19LHtrZXk6IndlaWdodGVkIix2YWx1ZTpmdW5jdGlvbihlKXtpZighZXx8MD09PWUubGVuZ3RoKXJldHVybiBudWxsO3ZhciB0LG49ZS5zb3J0KGZ1bmN0aW9uKGUsdCl7dmFyIG4scjtyZXR1cm4obnVsbCE9PShuPWUKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IENhbm5vdCByZWFkIHByb3BlcnR5ICdpdGVtJyBvZiBudWxsClR5cGVFcnJvcjogQ2Fubm90IHJlYWQgcHJvcGVydHkgJ2l0ZW0nIG9mIG51bGwKICAgIGF0IGUudmFsdWUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0LjFjNTlmYmRjLmNodW5rLmpzOjE6NzYxMjc4KQogICAgYXQgRnVuY3Rpb24udmFsdWUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0LjFjNTlmYmRjLmNodW5rLmpzOjE6Mzk4MDMwKQogICAgYXQgRnVuY3Rpb24udmFsdWUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0RGVza3RvcH5BcHBMYXlvdXRNb2JpbGUuY2VkYWFlNTUuY2h1bmsuanM6MToxMDc0MDIpCiAgICBhdCBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL0FwcExheW91dE1vYmlsZS45N2FiZjM2Mi5jaHVuay5qczoxOjE5NDgwOQogICAgYXQgT2JqZWN0LnVzZU1lbW8gKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hNjlhZGM1MS5jaHVuay5qczoxOjE0NTQ3MCkKICAgIGF0IE9iamVjdC50LnVzZU1lbW8gKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hNjlhZGM1MS5jaHVuay5qczoxOjgyMjQ4KQogICAgYXQgaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuOTdhYmYzNjIuY2h1bmsuanM6MToxOTQ3NzgKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35BcHBMYXlvdXQuZTBkMzVmYTIuY2h1bmsuanM6MToxNTkwCiAgICBhdCBhZSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5lMGQzNWZhMi5jaHVuay5qczoxOjE1OTA1KQogICAgYXQgZS50cmFjayAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5lMGQzNWZhMi5jaHVuay5qczoxOjI2NTg3KQ

**Comment by EddieDover** [comment]
Reinstalling the game fixes the issue. ¯\_(ツ)_/¯

**Comment by DexterHuang** [comment]
fixed :)
