### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Dansiman** [DexterHuang/CyberCodeOnline#828]
An hour or two ago I had closed the app. Just now, immediately upon opening the app I got a crash with the following code:

PjpmdW5jdGlvbihlKXtyZXR1cm4gZVtNYXRoLmZsb29yKHRoaXMuZ2V0UmFuZG9tKCkqZS5sZW5ndGgpXX19LHtrZXk6ImdldFdlaWdodGVkSXRlbSIsdmFsdWU6ZnVuY3Rpb24oZSl7cmV0dXJuIHRoaXMud2VpZ2h0ZWQoZSkuaXRlbX19LHtrZXk6IndlaWdodGVkIix2YWx1ZTpmdW5jdGlvbihlKXtpZighZXx8MD09PWUubGVuZ3RoKXJldHVybiBudWxsO3ZhciB0LG49ZS5zb3J0KGZ1bmN0aW9uKGUsdCl7dmFyIG4scjtyZXR1cm4obnVsbCE9PShuPWUKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IENhbm5vdCByZWFkIHByb3BlcnR5ICdpdGVtJyBvZiBudWxsClR5cGVFcnJvcjogQ2Fubm90IHJlYWQgcHJvcGVydHkgJ2l0ZW0nIG9mIG51bGwKICAgIGF0IGUudmFsdWUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0LjFjNTlmYmRjLmNodW5rLmpzOjE6NzYxMjc4KQogICAgYXQgRnVuY3Rpb24udmFsdWUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0LjFjNTlmYmRjLmNodW5rLmpzOjE6Mzk4MDMwKQogICAgYXQgRnVuY3Rpb24udmFsdWUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0RGVza3RvcH5BcHBMYXlvdXRNb2JpbGUuY2VkYWFlNTUuY2h1bmsuanM6MToxMDc0MDIpCiAgICBhdCBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL0FwcExheW91dE1vYmlsZS45N2FiZjM2Mi5jaHVuay5qczoxOjE5NDgwOQogICAgYXQgT2JqZWN0LnVzZU1lbW8gKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hNjlhZGM1MS5jaHVuay5qczoxOjE0NTQ3MCkKICAgIGF0IE9iamVjdC50LnVzZU1lbW8gKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi5hNjlhZGM1MS5jaHVuay5qczoxOjgyMjQ4KQogICAgYXQgaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuOTdhYmYzNjIuY2h1bmsuanM6MToxOTQ3NzgKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35BcHBMYXlvdXQuZTBkMzVmYTIuY2h1bmsuanM6MToxNTkwCiAgICBhdCBhZSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5lMGQzNWZhMi5jaHVuay5qczoxOjE1OTA1KQogICAgYXQgZS50cmFjayAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC5lMGQzNWZhMi5jaHVuay5qczoxOjI2NTg3KQ==

**Comment by DexterHuang** [comment]
hello this is fixed :)
