### ISSUE TITLE
Bug when in gang dungeon

### ISSUE THREAD

**Issue by leonval** [DexterHuang/CyberCodeOnline#829]
![image](https://user-images.githubusercontent.com/84886281/119754433-b4261d00-beca-11eb-869d-1126a0c165cd.png)

Error code :
PiBvKGUpe2RjKGwscixhLG8saSwibmV4dCIsZSl9ZnVuY3Rpb24gaShlKXtkYyhsLHIsYSxvLGksInRocm93IixlKX1vKHZvaWQgMCl9KX19dmFyIHZjPWMubGF6eShmdW5jdGlvbigpe3JldHVybiBQcm9taXNlLmFsbChbbi5lKDEwKSxuLmUoMSldKS50aGVuKG4uYmluZChudWxsLDYxNSkpfSksZ2M9Yy5tZW1vKGZ1bmN0aW9uKGUpe3ZhciB0LG4scixhLGwsbz1lLmlzTWUsaT1lLnBsYXllcix1PWUuZG9uYXRpb25UeXBlLHM9ZS5jb2xvcjtyZXR1cm4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpDaHVua0xvYWRFcnJvcjogTG9hZGluZyBjaHVuayAxMCBmYWlsZWQuCihlcnJvcjogaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3Jzfk1vYmlsZVBsYXllckxldmVsRGV0YWlscy5lZGFiZmY0ZS5jaHVuay5qcykKQ2h1bmtMb2FkRXJyb3I6IExvYWRpbmcgY2h1bmsgMTAgZmFpbGVkLgooZXJyb3I6IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35Nb2JpbGVQbGF5ZXJMZXZlbERldGFpbHMuZWRhYmZmNGUuY2h1bmsuanMpCiAgICBhdCBGdW5jdGlvbi5jLmUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS90YWJzL2NoYXQ6MTo0MzIyKQogICAgYXQgaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXRNb2JpbGUuZGRhNzE0OWUuY2h1bmsuanM6MToyMzAzNTkKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi45ZjIwMWUzOC5jaHVuay5qczoxOjE4Nzc4MQogICAgYXQgYnUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi45ZjIwMWUzOC5jaHVuay5qczoxOjE4NzkyNikKICAgIGF0IGJsIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uOWYyMDFlMzguY2h1bmsuanM6MToxNzk3ODQpCiAgICBhdCB5bCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLjlmMjAxZTM4LmNodW5rLmpzOjE6MTc5NzA5KQogICAgYXQgY2wgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi45ZjIwMWUzOC5jaHVuay5qczoxOjE3NjcxMSkKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi45ZjIwMWUzOC5jaHVuay5qczoxOjEyNzkwMQogICAgYXQgdC51bnN0YWJsZV9ydW5XaXRoUHJpb3JpdHkgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvbWFpbi45ZjIwMWUzOC5jaHVuay5qczoxOjIwMzU3MCkKICAgIGF0IEhvIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL21haW4uOWYyMDFlMzguY2h1bmsuanM6MToxMjc2MTEp

**Comment by DexterHuang** [comment]
hello this should be resolved :) try to resatrt

**Comment by leonval** [comment]
alr thanks :)
