### ISSUE TITLE
Suggestion: Comparing equipment

### ISSUE THREAD

**Issue by YamoJun** [DexterHuang/CyberCodeOnline#83]
I want to compare equipments without "upgrades".

**Comment by krozlink** [comment]
maybe show the upgrade bonus in brackets when doing a comparison
e.g maxShield: 88 (+12) would mean that the item is contributing 88 and upgrades are contributing 12

**Comment by DexterHuang** [comment]
@krozlink thats is excellent idea, i will add that

**Comment by DexterHuang** [comment]
implemented in pre-release ;)
