### ISSUE TITLE
crashing after every fight in dungeon

### ISSUE THREAD

**Issue by CookedPages** [DexterHuang/CyberCodeOnline#836]
I entered my first dungeon(first challenge dungeon) and was killed by the 'boss'

I was trying the dungeon to complete the 'dungeon friends' quest and that obvs didn't work. So now I have tried entering my own and other people's dungeons and when I either kill or sometimes just take damage from the enemy, I get the crash to this error message:

plz help I love the game but can't really play without a fix.

Error code: 

PmVlKGUsInRyYWl0IixxLGFlKGUpKSxlZShlLCJyYW5kb21HZW4iLFksYWUoZSkpLGV9cmV0dXJuIHQ9YSxyPVt7a2V5OiJnZW5lcmF0ZURhdGEiLHZhbHVlOmZ1bmN0aW9uKGUsdCxuKXt2YXIgcj1uZXcgdy5hKGUpLGk9dC5nZXRIZWFsdGhGYWN0b3IoKSxhPXQuZ2V0U2hpZWxkRmFjdG9yKCksbz10LmdldERhbWFnZUZhY3RvcigpLHU9ITEsYz1yLmNob29zZSh0LmdldE5hbWVzKCkpLGw9dC5nZXRUcmFpdHMoKSxzPW51bGw7ci5jaGFuY2UodC5nZXQKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF4KCgpUeXBlRXJyb3I6IENhbm5vdCByZWFkIHByb3BlcnR5ICdnZXRIZWFsdGhGYWN0b3InIG9mIG51bGwKVHlwZUVycm9yOiBDYW5ub3QgcmVhZCBwcm9wZXJ0eSAnZ2V0SGVhbHRoRmFjdG9yJyBvZiBudWxsCiAgICBhdCBGdW5jdGlvbi52YWx1ZSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXQuNWQwMTBkZWMuY2h1bmsuanM6MTozNjI2MTcpCiAgICBhdCBodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL0FwcExheW91dC41ZDAxMGRlYy5jaHVuay5qczoxOjM2MzMzOQogICAgYXQgUyAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9tYWluLmUwZjAyYjllLmNodW5rLmpzOjE6MTYwMzEpCiAgICBhdCBhLnZhbHVlIChodHRwczovL2N5YmVyY29kZW9ubGluZS5jb20vc3RhdGljL2pzL0FwcExheW91dC41ZDAxMGRlYy5jaHVuay5qczoxOjM2MzI4NykKICAgIGF0IGEudmFsdWUgKGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvQXBwTGF5b3V0LjVkMDEwZGVjLmNodW5rLmpzOjE6MzYzODg2KQogICAgYXQgaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy9BcHBMYXlvdXREZXNrdG9wLjcyMGQyMDVkLmNodW5rLmpzOjE6NzkxMDcKICAgIGF0IGh0dHBzOi8vY3liZXJjb2Rlb25saW5lLmNvbS9zdGF0aWMvanMvdmVuZG9yc35BcHBMYXlvdXQuOGZhYmQ4NGMuY2h1bmsuanM6MToxNTkwCiAgICBhdCBhZSAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC44ZmFiZDg0Yy5jaHVuay5qczoxOjE1OTA2KQogICAgYXQgZS50cmFjayAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC44ZmFiZDg0Yy5jaHVuay5qczoxOjI2NTg4KQogICAgYXQgaCAoaHR0cHM6Ly9jeWJlcmNvZGVvbmxpbmUuY29tL3N0YXRpYy9qcy92ZW5kb3JzfkFwcExheW91dC44ZmFiZDg0Yy5jaHVuay5qczoxOjE1Njcp

**Comment by hkelmonte** [comment]
I have the same problem
The code shown is exactly the same

**Comment by DexterHuang** [comment]
this is fixed :)
