### ISSUE TITLE
Dungeon Quest completion error

### ISSUE THREAD

**Issue by AuroraEndante** [DexterHuang/CyberCodeOnline#839]
I started and finished a coop challenge dungeon. The quest did not update upon completion to reflect that the dungeon had been cleared. I backtracked and checked every room and I hadn't missed anything.

Here's my screengrabs from mobile.

![dungeon error (1)](https://user-images.githubusercontent.com/84821313/120080814-85ee3c00-c088-11eb-9396-ea49e09ab18c.jpg)
![dungeon error (2)](https://user-images.githubusercontent.com/84821313/120080816-85ee3c00-c088-11eb-85d7-28b5519fa258.jpg)

**Comment by DexterHuang** [comment]
this should be fixed
