### ISSUE TITLE
Weird gang bug

### ISSUE THREAD

**Issue by Misaki290** [DexterHuang/CyberCodeOnline#842]
I have my own gang SYN_Symbiote and now I see that I am gangless.
If I go to a person that I know is in my gang, I see that the gang is still there.
But if I click on the "Gang" tag it prompts me to create a gang.
I don't remember leaving my gang.
What's going on???

Screenshots:
![Screenshot_20210529-175307](https://user-images.githubusercontent.com/79731146/120234954-b0dfb800-c261-11eb-8e25-bf89a94f9601.png)
![Screenshot_20210529-175323](https://user-images.githubusercontent.com/79731146/120234976-be953d80-c261-11eb-8afa-3ed63c8633cd.png)

**Comment by DexterHuang** [comment]
whats your in game name @Misaki290

**Comment by DexterHuang** [comment]
fixed your account :)
