### ISSUE TITLE
How To Understand It Completely 

### ISSUE THREAD

**Issue by Aawaraishq00007** [DexterHuang/CyberCodeOnline#856]
People Like It Pubg Mobile 

> `[invilove.com](https://www.invilove.com) @Aawaraishq0007` @Dearlove.com
![Uploading  ### 

- **_#Screenshot_20210606-103054_WhatsApp.jpg…]()

1. 

- [ ] 

_**

**Comment by Aawaraishq00007** [comment]
Completely forgot About It

**Comment by Misaki290** [comment]
Is this Spam or?

**Comment by DexterHuang** [comment]
yup, reported
