### ISSUE TITLE
Problem with item max amount.

### ISSUE THREAD

**Issue by jeremy-j-ackso** [DexterHuang/CyberCodeOnline#86]
Was trying to pick up some energy cells and got this error message:
![Screenshot from 2020-09-19 21-00-45](https://user-images.githubusercontent.com/17519041/93693315-69dad980-fabb-11ea-901a-0e9d9fe8f1e5.png)

**Comment by DexterHuang** [comment]
I believe your energy cell reached stack maximun, which is 1000
is it the case?

**Comment by jeremy-j-ackso** [comment]
It was actually at 999.

**Comment by DexterHuang** [comment]
yeah so, if you try to add 2 into the stack, it will fail because it will exceed the max amount

**Comment by jeremy-j-ackso** [comment]
Well, I was trying to add 1 into it. Sorry, should have specified that. I'll come back when/if I can duplicate it with more evidence. It's possible I saw something incorrectly.

**Comment by DexterHuang** [comment]
ahh i see, in that case it could be a >= kinda bug haha let check :)

**Comment by DexterHuang** [comment]
Well it is indeed a bug caused by I using ">" instead of ">=" HAHA
