### ISSUE TITLE
New Notifications options: "Never"

### ISSUE THREAD

**Issue by jeremy-j-ackso** [DexterHuang/CyberCodeOnline#87]
I'd like to have the option to Never receive Notifications from the app because I find them distracting when I'm trying to do other things. The "Not Now" option isn't clickable (in FF at least), and keeps popping up when I click away from the alert window, so it's not a permanent solution.

**Comment by DexterHuang** [comment]
Oh, yeah i should add a checkbox for never ask again,

what do you mean by FF?

**Comment by jeremy-j-ackso** [comment]
Firefox

**Comment by jeremy-j-ackso** [comment]
Seems to be better with your updates that include the "Never ask again" checkbox.

**Comment by DexterHuang** [comment]
:D yeah i added it, forgot to let you know here haha
it works right?

**Comment by jeremy-j-ackso** [comment]
Yep, it's much better now! Thanks!
