### ISSUE TITLE
Skip queue stuck at one person

### ISSUE THREAD

**Issue by tjefaz** [DexterHuang/CyberCodeOnline#882]
As per title - skip was triggered, and everyone's task seemed to have been accelerated, but the skip wouldn't finish and was stuck at "Accelerating 1 person" for all users. The user who was in Skip QUEUE had one of those names that kept changing, so I couldn't tell who it was. This happened just now. Not sure if it was resolved

**Comment by DexterHuang** [comment]
Hello this is fixed 👍

**Comment by tjefaz** [comment]
That was fast haha 😆
