### ISSUE TITLE
console.log is slowing down processing in upgrade modules page

### ISSUE THREAD

**Issue by rnitta** [DexterHuang/CyberCodeOnline#89]
<img width="668" alt="aaa" src="https://user-images.githubusercontent.com/31783570/94217079-1386f400-ff1c-11ea-9057-92fac98b6dce.png">

<img width="665" alt="スクリーンショット 2020-09-25 10 39 17" src="https://user-images.githubusercontent.com/31783570/94216979-cdca2b80-ff1b-11ea-9d5f-89e3602377fe.png">

**Comment by DexterHuang** [comment]
thank you @rnitta, it is fixed :)
