### ISSUE TITLE
AFK Study will not level up. 

### ISSUE THREAD

**Issue by BW0ng** [DexterHuang/CyberCodeOnline#9]
I queued up a bunch of AFK studies and it's not leveling up but rather just adding to the overall xp. 

<img width="693" alt="Screen Shot 2020-08-11 at 2 00 38 PM" src="https://user-images.githubusercontent.com/10983168/89937838-3d3dc300-dbdb-11ea-9d46-64ed3c5757ab.png">

**Comment by DexterHuang** [comment]
Ah, thanks, will fix it tomorrow, 
for now you can try update the exp by printing something, I think it should temporarily fix the long bar?

**Comment by BW0ng** [comment]
Yes, that did fix the long bar. Although I did have to print multiple times. Looks like it's only checking the next level and not adding any amount of levels.

**Comment by DexterHuang** [comment]
Yeah, i think that was the problem, btw is the afk thing overpowered? Seems like you leveled multiple time in one go

**Comment by BW0ng** [comment]
I think it might be a tad overpowered since most afk things you want to be at a percentage of what you would get when you are being active. I did 2.5 hours worth and got 5056 xp. It's nice since I can just set that while I'm doing work rather than having to check in every 15 minutes. 

With that being said, I do thing that the printing might be a little underpowered, since I would usually associate being able to have a similar +/- 1-2 levels of gear as my character level. This morning I was around character level 11 and gear level 6.

**Comment by DexterHuang** [comment]
Yes that's very good point, I think might have overbuffed it abit, what level is your printing now? And what's ur your normal level? 

For printing exp, I have buffed this few hours again, hopefully it's at better spot now

**Comment by BW0ng** [comment]
Right now printing (level 8) and character (12). However, I haven't actually been doing anything other than AFK printing today.
