### ISSUE TITLE
Bug: For mentions, Tab doesn't autocomplete the suggested username.

### ISSUE THREAD

**Issue by vanessasickles** [DexterHuang/CyberCodeOnline#94]
**Current Behavior:**
* Type @ in chat and begin typing a username to mention.
* Suggestions for autocompletion of usernames pop up.
* Press Tab. Focus on the page goes to the SSL/address bar.

**Expected Behavior:**
* Tab should auto-complete the suggestion.

**Comment by DexterHuang** [comment]
tab completed is added :)
