### ISSUE TITLE
Broken time selection

### ISSUE THREAD

**Issue by jeremy-j-ackso** [DexterHuang/CyberCodeOnline#96]
Anywhere I put the slider for `deployFarmBot()` only allows 15m.
![Screenshot from 2020-09-28 08-45-30](https://user-images.githubusercontent.com/17519041/94447554-1b86a400-0167-11eb-904b-a1caf0ec01bd.png)

**Comment by DexterHuang** [comment]
I think thats because you only have 1 AI Core?

**Comment by jeremy-j-ackso** [comment]
Ah, ok. That makes sense. I didn't realize it was one ai core/15 minutes.
