### ISSUE TITLE
@Tag sorting delay

### ISSUE THREAD

**Issue by vxgxbxnd** [DexterHuang/CyberCodeOnline#987]
I noticed one frequent issue I have is when I start tagging someone. Initially, they'll float to the top, but when I try to click on them the list will sort again, causing me to tag the wrong person. This double-sorting happens every time and I see other people mis-tagging because of it. The only fix I can think of is waiting a few seconds for the list to sort yet again before I select the person.

I recommend sticking with the initial sorting as it is more accurate on who I'm trying to tag rather than re-sort and losing the person I'm trying to tag. Either way, a second sorting shouldn't happen. Just throws everything off.

https://user-images.githubusercontent.com/88697977/129942513-4fd2229e-230e-4243-9983-e2526bb746ac.MOV

**Comment by Lux-Sakura** [comment]
![Untitled](https://user-images.githubusercontent.com/88697977/129942537-32f1ed48-e139-45b4-85b9-e3b4a923da73.png)
