### ISSUE TITLE
Add job for bitcoins

### ISSUE THREAD

**Issue by wizarduss** [DexterHuang/CyberCodeOnline#99]
I think it could be useful to have a job (at shangri-la) to gain bitcoin, would also potentially increase the market usage, as right now I mostly don't have the money to buy anything.

**Comment by wizarduss** [comment]
Or at the very least something that increases a bit more with the prices.. Shop items are about 100k now (lvl 16), and by the time I'd have that, I would be several levels higher

**Comment by DexterHuang** [comment]
Added bitcoin mining ;)
